- main.go
- pkg/html/html.go
- pkg/util/utils.go
- scripts/fetchdata.sh
also switches to using the json bug search api and changes the data fetch interval to 12 hours
> Add separate top ten lists for test failures with bugs and without bugs

- main.go
- pkg/html/html.go
Defining list of supported releases in code is not great, we might think of having some YAML file config and an observer that will restart sippy when the config change (that will list all supported releases).
> Add landing page with list of releases

- pkg/html/html.go
- pkg/util/utils.go
Added to testgrids just now: https://github.com/kubernetes/test-infra/pull/17806
I think it makes sense to show metal and metal-ipi separately, since they're very different.
> Add metal-ipi as a potential platform

- README.md
Catching up with 251c855266 (add 4.6 to dashboard view, 2020-06-02) and the subsequent 4.2 restoration from 6795065b0e (improve the readme, 2020-06-02).
> README: Add 4.6, drop 4.1

- pkg/html/html.go
- Truncate the summary to 255 characters when opening a Bugzilla
- Send the version when opening a Bugzilla
> Truncate Summary and Send Version to Bugzilla

- main.go
- pkg/html/html.go
- pkg/util/utils.go
adds banner like:
if any bz lookups failed on the latest refresh
> add warning banner when bz lookups fail

- pkg/util/utils.go
I suspect that many ovn failures are specific to ovn.  Having a platform checks the general feature and classifies the top failures so we can quickly compare.
> add ovn as a platform

- pkg/util/utils.go
Now trying to do with a regex.
> skip overly broad upgrade test that is now subdivided

- pkg/util/utils.go
The pass rates are very different and the top failing test cases are different, so we have to attack them differently.
> add ocp and origin platforms

- main.go
- pkg/util/utils.go
This tracks the known install and upgrade junit tests and follows the know setup container junit to try to determine whether an install failed, whether the infra failed, or whether the upgrade failed.
It seems to be showing a tough set of infra problems on some platforms.
> add synthetic junit tests for infra, install, and upgrade

- main.go
- pkg/testgridanalysis/testgridanalysisapi/types.go
- pkg/util/utils.go
This presentation is more what people expect and simplifies some logic of the processing and transformation.  It also gets us ready for building out test results by job and unifying aggregration types.
> organize job run results by job

- main.go
- pkg/api/api.go
- pkg/apis/sippyprocessing/v1/types.go
- pkg/html/html.go
- pkg/util/utils.go
We can create different coloriziation rules too. I'm biased towards making infrequent jobs more forgiving in terms of going yellow or red since an off day has a bigger impact.
> separate infrequent jobs into a different table section

- pkg/html/jobresult.go
a 30% pass rate is too low for reliable signal.  a 60% failure rate is still very frequent, but potentially good enough to consider reliable.
> make colors relate to developer actions

- main.go
- pkg/api/api.go
- pkg/apis/sippyprocessing/v1/types.go
- pkg/html/html.go
- pkg/testgridanalysis/testgridanalysisapi/types.go
- pkg/testgridanalysis/testreportconversion/by_component.go
- pkg/testgridanalysis/testreportconversion/test_report.go
Removes by-sig, which we never reported in html.
Removes by-job, which is replaced by searching frequent and infrequent failures.  I'm open to combining them into a single categorization.
This is reducing duplicate accounting as we process testgrid and move us towards a pipeline that looks like:
1. parse testgrid into `job -> job run -> test results` (RawJobResult)
1. RawJobResult to processedJobResult by looking up bugzilla and doing frequency computation
1. RawJobResult to allTestResult (not done yet)
2. various filtering and sorting based on processedjobresults and alltest results.
2. display of the json.
> remove old category slicing

- main.go
- pkg/api/api.go
- pkg/apis/sippyprocessing/v1/types.go
- pkg/html/failing_tests.go
- pkg/html/html.go
- pkg/testgridanalysis/testgridanalysisapi/types.go
- pkg/testgridanalysis/testreportconversion/by_component.go
- pkg/testgridanalysis/testreportconversion/by_tests.go
- pkg/testgridanalysis/testreportconversion/test_report.go
- pkg/util/utils.go
ByAll was filtered and didn't include all the results.  The new ByTest does include them and uses the same datatype as the top failing test calculations.
This completes the main changes to the processing pipeline.  From here it is recutting an sorting.
> replace byAll with ByTest which actually includes all tests

- pkg/testgridanalysis/testidentification/platforms.go
This provided value a couple weeks back, but hasn't been important recently.
> remove ocp and origin variants

- main.go
- pkg/api/api.go
- pkg/html/failing_tests.go
- pkg/html/fastest_moving_jobs.go
- pkg/html/html.go
- pkg/html/jobaggregationresult.go
- pkg/testgridanalysis/testgridanalysisapi/types.go
- pkg/testgridanalysis/testgridconversion/doc.go
- pkg/testgridanalysis/testgridconversion/synthentic_tests.go
- pkg/testgridanalysis/testgridconversion/to_raw_data.go
- pkg/util/utils.go
This separates the data from a particular run from the configuration used to produce data on a repeating cycle.
> Refactor to make it easier to tie webserver hits to results produced.

- main.go
- pkg/sippyserver/analyzer.go
- pkg/sippyserver/server.go
- pkg/testgridanalysis/testgridhelpers/testgridhelpers.go
The configuration itself doesn't vary today, but the release data does. Since it is fully independent, we can re-use the configuration and pass the data use to select the data itself. This will allow very easy parallelization in the future.
Also stop using maps for for release+variant to days and track variant days as a struct.
> refactor analyzer to support re-use across releases

- pkg/html/html.go
- pkg/sippyserver/analyzer.go
- pkg/testgridanalysis/testgridanalysisapi/types.go
- pkg/testgridanalysis/testgridconversion/synthentic_tests.go
- pkg/testgridanalysis/testgridconversion/to_raw_data.go
- pkg/testgridanalysis/testidentification/test_identification.go
- pkg/testgridanalysis/testreportconversion/testresult.go
Makes the infra, install, upgrade calculation more clear. This uncovered calculation problems where certain platforms never had infra report success or failure.  This very slightly pushes the infra percentages, but makes a fairly  large shift in install (vsphere-upi and metal are installing quite well).  It's pushing upgrade down.
Not all containers are named setup anymore.  Some jobs are currently missing an install step.  That's weird.
> refine install, upgrade, infra

- main.go
- pkg/api/api.go
- pkg/html/failing_bzcomponents.go
- pkg/html/failing_tests.go
- pkg/html/html.go
- pkg/sippyserver/analyzer.go
- pkg/sippyserver/server.go
- pkg/testgridanalysis/testgridconversion/to_raw_data.go
- pkg/testgridanalysis/testreportconversion/test_report.go
This makes -1 mean, "most recent available time" and uses an offset instead of endDay.  This allows `./sippy --local-data historical-data/4.5GA --release 4.5 --server --start-day=-1` to allow visiting http://localhost:8080/?release=4.5 to "just work", making these urls very easy to build.
> convert to startday and offset

- pkg/api/api.go
- pkg/apis/sippyprocessing/v1/types.go
- pkg/html/html.go
- pkg/html/jobaggregationresult.go
- pkg/html/jobresult.go
- pkg/testgridanalysis/testreportconversion/by_platform.go
- pkg/testgridanalysis/testreportconversion/jobresult.go
Updates the value in parens to indicate what the pass rate is for jobs that started to run the installer and got at least the bootstrap kube-apiserver up and running.  Given infrastructure failures between 10-15%, this has a meaningful impact on the pass rates of many platforms and jobs.  
We still separately track infrastructure/bootstrapping failures to drive them out, but the number in parens can be thought of as, "after a customer gets an install to start, what are the odds he will be successful".
The previous check was, "if all the tests that have bugs associated with them started passing, what would our pass rate be".  In order to be interpreted as "known failures that have been triaged and deferred" 
1. bugs associated with failing tests are mapped correctly
2. bugs associated with …
> use parens to indicate pass rate if infrastructure worked

- pkg/testgridanalysis/testidentification/component.go
Fixing a bug from 0ff36998d4 (#69) to avoid:
```console
$ go test ./...
pkg/testgridanalysis/testidentification/component.go:168:10: Errorf format %q reads arg #1, but call has 0 args
pkg/testgridanalysis/testidentification/component.go:176:10: Errorf format %q reads arg #1, but call has 0 args
...
```
> pkg/testgridanalysis/testidentification: Fix "not a valid bugzilla component" Errorf

- pkg/testgridanalysis/testreportconversion/by_platform.go
- pkg/testgridanalysis/testreportconversion/jobresult.go
- pkg/testgridanalysis/testreportconversion/test_report.go
This reduces the call sites for looking up bugs from the cache and instead forces a reference from a single source.
> only lookup bugs once and reuse the mapping afterwards

- Dockerfile
- pkg/testgridanalysis/testgridanalysisapi/types.go
- pkg/testgridanalysis/testgridconversion/synthentic_tests.go
- pkg/testgridanalysis/testgridconversion/to_raw_data.go
- pkg/testgridanalysis/testreportconversion/by_component.go
Per openshift/release#12298, the test-case is really about whether the operator has any sad conditions at gather-time, regardless of whether those gathers occured after a failed install or not.
[1]: https://github.com/openshift/release/pull/12298
> pkg/testgridanalysis: Generic handling for sad-operator test-case

- pkg/testgridanalysis/testidentification/platforms.go
- pkg/testgridanalysis/testreportconversion/by_tests.go
- pkg/testgridanalysis/testreportconversion/test_report.go
- pkg/testgridanalysis/testreportconversion/testresult.go
ovirt upgrade has never worked.  Jobs which never worked should be visible in sippy so we can identify and address problems, but using them as indicators to aggregations like platforms and top level indicators pulls averages in unreasonable ways.
This creates a category of jobs called "never-stable" and displays them, but removes them from other aggregations.
> exclude never stable jobs from aggregrations for platforms or top level indicators

- pkg/testgridanalysis/testreportconversion/by_tests.go
if a job didn't run a test, that job should not be included in job list. This happens for our synthetic jobs like install, upgrade, and infra.
> don't include job results for tests that aren't run on the job

- pkg/html/fastest_moving_jobs.go
- pkg/testgridanalysis/testreportconversion/jobresult.go
- pkg/testgridanalysis/testreportconversion/test_report.go
- pkg/testgridanalysis/testreportconversion/testresult.go
This prevents lots of zero run tests from showing up on the job because of the way filtering works.
> filter the fastest moving jobs view for tests with few runs

- pkg/testgridanalysis/testidentification/platforms.go
move it to never passed.  if it starts working, then we'll move it back.
> triple upgrade never worked

- pkg/html/generichtml/bugs.go
- pkg/html/generichtml/jobaggregationresult.go
- pkg/html/generichtml/jobresult.go
- pkg/html/generichtml/testresult.go
- pkg/html/installhtml/install_by_operators.go
- pkg/html/installhtml/install_html.go
- pkg/html/installhtml/upgrade_by_operators.go
- pkg/html/installhtml/upgrade_html.go
- pkg/html/installhtml/util.go
- pkg/html/releasehtml/failing_bzcomponents.go
- pkg/html/releasehtml/failing_tests.go
- pkg/html/releasehtml/fastest_moving_jobs.go
- pkg/html/releasehtml/html.go
- pkg/html/releasehtml/top_level_indicators.go
- pkg/sippyserver/install_details.go
- pkg/sippyserver/server.go
- pkg/testgridanalysis/testreportconversion/by_platform.go
- pkg/testgridanalysis/testreportconversion/by_tests.go
- pkg/testgridanalysis/testreportconversion/jobresult.go
- pkg/testgridanalysis/testreportconversion/testresult.go
Adds an endpoint at /upgrades?release=4.6 to show an upgrade job table (like the install table) and includes upgrade related tests and upgrade jobs.  It's a nice view for targeting upgrades specifically.
> add upgrade report

- pkg/html/installhtml/install_by_operators.go
- pkg/html/installhtml/upgrade_by_operators.go
- pkg/html/installhtml/upgrade_html.go
- pkg/html/installhtml/util.go
- pkg/testgridanalysis/testgridconversion/synthentic_tests.go
- pkg/testgridanalysis/testgridconversion/to_raw_data.go
- pkg/testgridanalysis/testidentification/test_identification.go
- pkg/testgridanalysis/testreportconversion/by_component.go
- pkg/testgridanalysis/testreportconversion/testresult.go
adding more data to the grid for upgrades.  It has made several things really pop out
1. apiserver availability is very high on all platforms except Azure
1. apiserver availability suddenly dropped on azure
3. the "wait for SDN to be available" was extremely helpful, but we need to add it for oauth-apiserver
4. cluster upgrades suddenly  (in the past week) got much slower on azure 
5. upgrades on aws suddenly got less reliable this past week
6. upgrades on gcp suddenly got less reliable this past week.
> refine data for upgrades

- pkg/html/installhtml/upgrade_by_operators.go
- pkg/testgridanalysis/testidentification/test_identification.go
we were missing some that were added during 4.6 and refine "where did the upgrade fail".
> show additional upgrade related tests

- pkg/buganalysis/cache.go
- pkg/sippyserver/analyzer.go
- pkg/testgridanalysis/testreportconversion/jobresult.go
- pkg/testgridanalysis/testreportconversion/testresult.go
This allows a job with environment containing "job=\<jobName\>=all" to accept blame for every failing test in the job.  This is more consistent than using platforms, while still keeping a list that is tractably long.
https://bugzilla.redhat.com/show_bug.cgi?id=1883693 is my practice bug
/hold  
Hold until I can see proof that this functions.  I think the ci search cache fills every hour or so.
> allow a single BZ to be blamed for all job failures

- pkg/apis/sippyprocessing/v1/types.go
- pkg/html/installhtml/finalhealth_by_operators.go
- pkg/html/installhtml/finalhealth_html.go
- pkg/html/installhtml/util.go
- pkg/html/releasehtml/top_level_indicators.go
- pkg/sippyserver/install_details.go
- pkg/sippyserver/server.go
- pkg/testgridanalysis/testgridanalysisapi/types.go
- pkg/testgridanalysis/testgridconversion/synthentic_tests.go
- pkg/testgridanalysis/testgridconversion/to_raw_data.go
- pkg/testgridanalysis/testidentification/test_identification.go
- pkg/testgridanalysis/testreportconversion/by_component.go
- pkg/testgridanalysis/testreportconversion/test_report.go
- pkg/testgridanalysis/testreportconversion/testresult.go
Adds final operator health as a top level indicator and corrects the virtual vs real tests for install and upgrade on consumption.
> add final operator health tests

- pkg/testgridanalysis/testgridconversion/to_raw_data.go
Imagine cases where the content includes days you aren't going to analyze.  I found this because of all the "zero runs" showing up as zero percent.
> some tests can be in testgrid and not run at all in the selected window

- pkg/testgridanalysis/testidentification/platforms.go
ovirt is still a little under 50%, but this one is over 70% now.
> triple upgrade is working 70% of the time

- pkg/html/generichtml/decorations.go
- pkg/html/generichtml/jobaggregationresult.go
- pkg/html/generichtml/jobresult.go
- pkg/html/generichtml/testresult.go
- pkg/html/installhtml/test_detail.go
- pkg/html/installhtml/test_detail_html.go
- pkg/html/installhtml/util.go
- pkg/html/releasehtml/failing_tests.go
- pkg/sippyserver/install_details.go
- pkg/sippyserver/server.go
- pkg/testgridanalysis/testreportconversion/testresult.go
Adds test details buttons for each aggregation we have.  It allows a button from any level to say, "are the problems on this test, job, or platform different by platform" in a quick chart
> Test details for test sections

- pkg/testgridanalysis/testgridconversion/synthentic_tests.go
the promotion jobs only do work if there is a diff.  When there is no diff, they never install a cluster.  When they don't install a cluster, we don't get a positive, "the infra worked" signal.
> fix handling for promotion jobs that don't always set up a cluster

- pkg/testgridanalysis/testidentification/platforms.go
3.11 job name is periodic-ci-openshift-origin-release-3.11-e2e-gcp so the current regex misses it.
@deads2k as an aside, it's probably worth us thinking about what to do in the case of "0 runs" both current and previous week for a given variant, as happens here:
https://sippy.ci.openshift.org/?release=3.11
Hiding it is a little scary since if something stops running, we lose sight of it.  But it's not hard to imagine that the set of valid variants evolves from release to release and keeping a bunch of scary looking empty red rows around for that reason doesn't seem ideal in terms of bringing visibility to the things we do care about.
> Make gcp variant regex match 3.11 jobs

- main.go
- pkg/buganalysis/cache.go
- pkg/sippyserver/server.go
adds --skip-bug-lookup as an arg that will skip over the ci-search bz lookup.
This reduces startup analysis time substantially, useful when iterating on code
that is not related to the bug assocation/reporting.
> add option to disable bugzilla lookups to speed up debug iteration

- pkg/testgridanalysis/testgridconversion/synthentic_tests.go
fixes the 3.11 sippy dashboard
> Add 3.11 to list of jobs w/ no setup container

- pkg/testgridanalysis/testidentification/test_identification.go
Temporary fix to remove these warnings for now, in the long-term we should find a smarter way to detect when we fail during setup.
> Add some additional non-standard setup container names

- pkg/testgridanalysis/testgridconversion/synthentic_tests.go
The upgrade rollback jobs for 4.6 and 4.7 are just broken and
we should still see the setup container
> Do not ignore upgrade-rollback in container setup results

- pkg/html/generichtml/html.go
Looks like this at the bottom of the page:
> Add links to historical data and release dashboard to footer

- main.go
- pkg/html/releasehtml/html.go
- pkg/sippyserver/analyzer.go
- pkg/sippyserver/install_details.go
- pkg/sippyserver/server.go
- pkg/testgridanalysis/testgridhelpers/testgridhelpers.go
- pkg/testgridanalysis/testreportconversion/test_report.go
Refactors the args to allow execution like `./sippy --server --local-data ../data-dir --dashboard=kube-master=sig-release-master-blocking,sig-release-master-informing=` that allows wiring against kubernetes (or non-openshift releases).
The `--release` flag still work and pipes to this new and specific mechanism.
> allow sippy to wire against kube

- pkg/html/generichtml/testresult.go
- pkg/html/releasehtml/failing_bzcomponents.go
- pkg/html/releasehtml/failing_tests.go
- pkg/html/releasehtml/fastest_moving_jobs.go
- pkg/html/releasehtml/html.go
- pkg/html/releasehtml/top_level_indicators.go
This leaves the header at the top in place, but it hides the empty tables at least.
> elide sections without data

- pkg/testgridanalysis/testidentification/ocp_variants.go
TestGrid PR: https://github.com/openshift/release/pull/13978
It makes sense to show metal-assisted separately from other metals since they're very different.
> Add metal-assisted variant

- pkg/buganalysis/cache.go
This should make the `/detailed` endpoint much quicker, as the previous
behavior was searching for every single bug every time it was loaded
with absolutely no caching.
> Check bug cache for bugs before searching again

- pkg/html/generichtml/bugs.go
- pkg/util/utils.go
also properly filter CLOSED (not just VERIFIED) bugs from consideration
for test failure causality
> decorate bug links based on bug status

- pkg/testgridanalysis/testreportconversion/by_component.go
Currently when viewing the /detailed endpoint sippy will panic and the content will not be served
> Add guard for bug.Component to prevent panic when loading /detailed endpoint

- pkg/testgridanalysis/testgridhelpers/testgridhelpers.go
without grid=old the testgrid summary might not show the
most recent results and if the user doesn't recognize this
they may be confused and think the job hasn't run recently
or not realize the current state of the job.
this is a known issue I guess and has some discussion
here: https://github.com/GoogleCloudPlatform/testgrid/issues/211
> Use grid=old for links given in summaries

- pkg/testgridanalysis/testgridhelpers/testgridhelpers.go
- pkg/testgridanalysis/testgridhelpers/testgridhelpers_test.go
Some kube jobs ran afoul of string concat.  This adds test and replaces the offending methods.
> build URLs with escaping

- pkg/testgridanalysis/testidentification/test_identification.go
- pkg/testgridanalysis/testreportconversion/by_variant.go
- pkg/testgridanalysis/testreportconversion/jobresult.go
These errors cause bad numbers of infrastructure failures, which in turn
cause bad numbers in parens.
This PR adds a couple common cases and then skips adding invalid numbers
of infrastructure failures when jobs don't have setup/install.
> handle missing setup tests in kube tests

- pkg/testgridanalysis/testgridconversion/ocp_synthentic_tests.go
the prefix constant already includes a trailing space, so this was extraneous and caused confusion when doing ci search lookups.
> Remove extraneous space in synthetic test names

- main.go
- pkg/apis/sippyprocessing/v1/types.go
- pkg/sippyserver/analyzer.go
- pkg/sippyserver/server.go
- pkg/testgridanalysis/testidentification/test_identification.go
- pkg/testgridanalysis/testreportconversion/by_tests.go
- pkg/testgridanalysis/testreportconversion/jobresult.go
- pkg/testgridanalysis/testreportconversion/test_report.go
- pkg/testgridanalysis/testreportconversion/testresult.go
This allows the variant view (the big table) work for kube and openshift releases.
If you go commit by commit, the first one is a rename to clarify the meaning of two logically different values.
> properly set the report name

- pkg/html/installhtml/upgrade_by_operators.go
- pkg/testgridanalysis/testidentification/test_identification.go
This will allow us to report upgrade pass rates properly again. I also added a guard so that if no jobs report starting upgrade the upgrade page doesn't die
> Include testsuite prefix in upgrade test names

- pkg/testgridanalysis/testgridconversion/to_raw_data.go
This makes it so that when searching for bugs/in search.svc.ci results will actually be found. The approach is kind of overkill but I thought the regex test name parser could be generally useful in the future and is not too bad in terms of maintenance burden.
> Remove suite from test name when loading testgrid data

- pkg/testgridanalysis/testgridconversion/ocp_synthentic_tests.go
These jobs don't run from ci-operator it seems so we don't get
the junit to look for a setup container. This will ignore
those jobs to prevent them from being warnings for missing
a setup to indicate a successful install.
> Ignore looking for setup container in ocp-osd jobs

- pkg/testgridanalysis/testidentification/test_identification.go
We get errors on 4.8 sippy that "periodic-ci-openshift-release-master-ocp-4.8-e2e-ovirt" is missing a test setup job to indicate successful installs on the sippy release pages.
We moved to use ipi-intall-install recently and therefore needed this change
> update ovirt install test

- pkg/testgridanalysis/testidentification/ocp_variants.go
oVirt ported to workflows and changed the name of the periodic jobs to end with e2e-ovirt:
- periodic-ci-openshift-release-master-origin-4.*-stable-to-4.*-ci-e2e-ovirt-upgrade
- periodic-ci-openshift-release-master-ocp-4.*-e2e-ovirt
> edit ovirt variant regex

- pkg/testgridanalysis/testidentification/ocp_variants.go
Jobs have been recently renamed, so we need to update variant patterns.
> Update patterns for variants

- pkg/html/releasehtml/top_level_indicators.go
Add a link for the top-level indicator Infrastructure to its details by variants.
> Allow to see Infrastructure details by variants

- pkg/testgridanalysis/testidentification/test_identification.go
I believe this will resolve the message the 4.8 sippy homepage: https://sippy.ci.openshift.org/?release=4.8
> Add single node container to list of custom job setup containers

- main.go
- pkg/testgridanalysis/testgridconversion/to_raw_data.go
new output produced here is consumed by https://github.com/openshift/origin/pull/25946
> Add output for canary(aka highly reliable) tests

- pkg/api/api.go
- pkg/apis/sippy/v1/types.go
- pkg/apis/sippyprocessing/v1/types.go
- pkg/buganalysis/cache.go
- pkg/html/generichtml/bugs.go
- pkg/html/generichtml/testresult.go
- pkg/html/releasehtml/failing_tests.go
- pkg/testgridanalysis/testreportconversion/testresult.go
List test name matching bugs that are targeted to the same release as the report as linked.
List test name matching bugs that are not targeted to the same release as the report as associated
fixes https://github.com/openshift/sippy/issues/128
>     List bugs targeted to a different release than the one being reported on

- pkg/buganalysis/cache.go
- pkg/testgridanalysis/testreportconversion/testresult.go
also strip out the useless "Pod" test result which matches all bugs
when it fails.
fixes https://github.com/openshift/sippy/issues/217
> Filter out spurious BZ data from ci-search

- pkg/apis/sippyprocessing/v1/types.go
- pkg/buganalysis/cache.go
- pkg/html/generichtml/bugs.go
- pkg/html/generichtml/jobresult.go
- pkg/html/generichtml/testresult.go
- pkg/html/releasehtml/html.go
- pkg/testgridanalysis/testreportconversion/jobresult.go
this will help us track bugs reported against permfailing jobs
sample row:
bugs are linked to jobs by putting the following text in a bug's environment field:
`job=$JOBNAME=all`
e.g.:
```
job=periodic-ci-openshift-release-master-nightly-4.8-e2e-metal-assisted-ipv6=all
```
> Add linked/associated bug lists to job reports

- pkg/api/jobs.go
- pkg/apis/testgrid/v1/types.go
- pkg/html/releasehtml/jobs.go
- pkg/sippyserver/server.go
- pkg/testgridanalysis/testgridanalysisapi/types.go
- pkg/testgridanalysis/testgridconversion/ocp_synthentic_tests.go
- pkg/testgridanalysis/testgridconversion/to_raw_data.go
- pkg/testgridanalysis/testidentification/test_identification.go
- static/jobs.css
- static/jobsdashboard.mjs
A new dashboard (similar to TestGrid) with all jobs.
This PR adds two new endpoints:
* `/api/jobs` that returns a JSON with statuses of all jobs
* `/jobs` with React app that shows data from `/api/jobs`
> Add dashboard for jobs statuses

- pkg/testgridanalysis/testgridanalysisapi/types.go
- pkg/testgridanalysis/testgridconversion/ocp_synthentic_tests.go
- pkg/testgridanalysis/testgridconversion/to_raw_data.go
- pkg/testgridanalysis/testreportconversion/jobresult.go
without this change, every single run (whether successful or not) of a job with "no known setup container" was being treated as an infrastructure failure.  Which results in more infra failures than total job run failures.
this pr:
1) automatically marks infra successful if the job succeeded
2) is more nuanced about handling jobs that have explicitly declared they don't have a setup container
> Better handling of infra failure computation for jobs with no known setup container

- pkg/html/generichtml/decorations.go
It's better to have white list of allowed symbols. The current implementation does not delete `/` from test names and generates names from `Suite:openshift/conformance/parallel` that don't work on Chrome.
> Filter unknown symbols from CSS class names

- pkg/html/releasehtml/html.go
- pkg/html/releasehtml/releases.go
- pkg/sippyserver/server.go
Also default the "detailed" view to the first release in the array (which presumably is sorted correctly).
@wking @smarterclayton
> Print all releases as links from top of PrintHtmlReport

- pkg/html/releasehtml/html.go
- pkg/testgridanalysis/testreportconversion/by_tests.go
- static/jobsdashboard.mjs
This commit adds the filter value into the URL as a parameter, so that it can be preserved when the link is shared.
Also all links from the job grid will be opened in a new tab.
> Pass JobsGrid filter through URL parameters

- pkg/testgridanalysis/testidentification/test_identification.go
Should fix this warning in https://sippy.ci.openshift.org/?release=4.8:
```
Warning: Analysis Error
"periodic-ci-openshift-release-master-ci-4.8-e2e-aws-hypershift" is missing a test setup job to indicate successful installs
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.8-e2e-aws-hypershift/1396468580492513280#1:build-log.txt%3A20
/cc @ironcladlou
> Identify Hypershift setup container

- pkg/testgridanalysis/testgridconversion/ocp_synthentic_tests.go
this was causing issues when we sent the search string to ci-search and got no results
> remove extraneous whitespace in test name

- pkg/api/jobs.go
- pkg/apis/testgrid/v1/types.go
- pkg/testgridanalysis/testgridconversion/to_raw_data.go
Sippy references the old Prow URL, which results in a dead link on some reports. Updates all references from https://prow.svc.ci.openshift.org to https://prow.ci.openshift.org.
> update prow url

- pkg/html/generichtml/bugs.go
- pkg/html/generichtml/html.go
This PR updates the "Open A Bug" URLs to add `sippy@dptools.openshift.org` to the CC list on newly created bugs.  This will allow our automation to receive updates, from Bugzilla, and automatically process any Sippy bugs that get "Closed as Duplicate" by updating the Duped BZ with the following information:
1. Any "[sig-sippy]" entries in the Environment Field
1. Adding `sippy@dptools.openshift.org` to the CC list
Flagging this as [WIP] while we demo this feature to any interested stakeholders.
> Enabling the DPCR Bugzilla Updater integration

- pkg/buganalysis/cache.go
Running the CLI reporting panics due to unnitialized jobBlockers.
```
[jdiaz@minigoomba sippy (master *%=)]$ ./sippy --local-data ./sdata
--release 4.9
panic: assignment to entry in nil map
goroutine 1 [running]:
github.com/openshift/sippy/pkg/buganalysis.(*bugCache).UpdateJobBlockers(0xc00011e4c0,
0xc0069b4000, 0x7b, 0x7b, 0x0, 0x0)
/home/jdiaz/projects/sippy/src/github.com/openshift/sippy/pkg/buganalysis/cache.go:122
+0x315
github.com/openshift/sippy/pkg/sippyserver.updateBugCacheForJobResults(0x93b268,
0xc00011e4c0, 0xc000116240, 0x7, 0xc0033a4000, 0x7b)
/home/jdiaz/projects/sippy/src/github.com/openshift/sippy/pkg/sippyserver/analyzer.go:142
+0x24d
github.com/openshift/sippy/pkg/sippyserver.(*TestReportGeneratorConfig).prepareTestReportFromData(0xc00875f808,
0xc000142060, 0x3, …
```
> ensure to initialize jobBlockers for new bugCache

- pkg/testgridanalysis/testidentification/ocp_variants.go
This adds the list of jobs that are currently below 40% passing rate,
the majority of which are near or at zero percent for at least the
last 14 days. Once jobs exceed 40% pass rate over the last 7 days, they
can "graduate" and be listed under their typical variant in sippy.
> Add never-stable jobs to sippy for 4.9

- pkg/testgridanalysis/testidentification/test_identification.go
This clears up most of the complaints about a job "missing a test
setup job to indicate successful installs".
Also, the list was almost alphabetical...make it so.
xref: https://issues.redhat.com/browse/TRT-32
> add some additional custom container setup names

- pkg/html/releasehtml/html.go
This seem to be the problem we were facing:
- sippy was returning 404 on the main page
- as a result GCP ingress was marking the backends as unhealthy
@deads2k - assuming you agree with this change, will you be able to also build a new image (so that I can deploy it in k8s cluster)?
> Return status 200 on main sippy page

- pkg/testgridanalysis/testidentification/test_identification.go
This adds the API availability tests to TRT curated, and removes the 4.6
tests.
> Add some curated TRT tests for API availability

- pkg/html/generichtml/errors.go
- pkg/html/generichtml/jobaggregationresult.go
- pkg/html/releasehtml/html.go
- pkg/html/releasehtml/variants.go
- pkg/sippyserver/server.go
This adds a new page to view all jobs for a specific variant. When
expanding the job details from the main page, the first few results
are shown. This adds a link to view all job results.
If you look at the production sippy, and expand the never-stable
variant, you'll see a "Plus N jobs" -- but there's no way to view them. This
links that message to a new page at `/variants?release=4.9&variant=never-stable`,
which lists all the jobs for that variant.
> Add a new variants page

- pkg/sippyserver/analyzer.go
- pkg/sippyserver/server.go
- pkg/sippyserver/server_test.go
To get better test coverage, I added some smoke tests to the `sippyserver` module. Right now, it only checks for the HTTP status returned from the HTTP request given certain args. In the future, it could also examine the returned payload. `go test -cover` indicates this covers 93.2% of code in the `sippyserver` module.
> adds smoke tests for sippyserver

- Dockerfile
> Update sippy to use ubi:8 image

- Dockerfile
- Dockerfile.buildroot
In order to use ubi:8 as a build root, we need
git pre-installed per the CI documentation[1], as
well as any other deps needed to build the project.
There doesn't seem to be any ready-made image in
the cluster I can use for this, since we need
both npm and go.
[1] https://docs.ci.openshift.org/docs/architecture/ci-operator/#build-root-image
> Add image for build root

- sippy-ng/src/__snapshots__/App.test.js.snap
- sippy-ng/src/constants.js
- sippy-ng/src/helpers.js
- sippy-ng/src/jobs/JobDetailTable.js
- sippy-ng/src/jobs/VariantCards.js
- sippy-ng/src/jobs/__snapshots__/JobsDetail.test.js.snap
- sippy-ng/src/releases/__snapshots__/ReleaseOverview.test.js.snap
If you click on the job name from a page like
https://sippy.ci.openshift.org/sippy-ng/jobs/4.9/detail?job=periodic-ci-openshift-release-master-nightly-4.9-e2e-metal-single-node-live-iso,
it doesn't filter the jobs list to only show that one job.  The new job/test
filtering is more clunky, so this adds some helpers, too.
> Fix link from "job runs" page back to job list

- pkg/api/job_runs.go
- sippy-ng/src/helpers.js
- sippy-ng/src/jobs/JobRunsTable.test.js
- sippy-ng/src/jobs/__snapshots__/JobRunsTable.test.js.snap
- sippy-ng/src/releases/Install.css
- sippy-ng/src/releases/Install.js
- sippy-ng/src/releases/Upgrades.css
- sippy-ng/src/releases/Upgrades.js
- sippy-ng/src/releases/__snapshots__/Install.test.js.snap
- sippy-ng/src/releases/__snapshots__/Upgrades.test.js.snap
- sippy-ng/src/tests/TestTable.js
A handful of minor fixes:
- Fix divs for install and upgrade. This prevents the browser from rendering two sets of horizontal scroll
bars.
- Ensure stable Date.now for consistent snapshots
- Job runs sort before limit
- Tests link to runs sorted by date
> Minor fixes: table layouts, sorting, test links

- sippy-ng/src/__snapshots__/App.test.js.snap
- sippy-ng/src/helpers.js
- sippy-ng/src/jobs/JobTable.js
- sippy-ng/src/jobs/__snapshots__/JobTable.test.js.snap
- sippy-ng/src/releases/ReleaseOverview.js
- sippy-ng/src/releases/__snapshots__/ReleaseOverview.test.js.snap
- sippy-ng/src/tests/TestByVariantTable.css
- sippy-ng/src/tests/TestTable.css
- sippy-ng/src/tests/TestTable.js
- sippy-ng/src/tests/__snapshots__/TestTable.test.js.snap
Data grid tables don't support dynamic row heights, which is why I used
the ellipsis and tooltip, but I realize I don't need dynamic row heights
they can all be the same size, just taller.
This also fixes the test-by-variant table which isn't data grid and can
have dynamic heights.
I also removed the decimal points.
fixes #266 
Release dashboard, compare with [this page](https://sippy.ci.openshift.org/sippy-ng/)
Test page, compare with [this page](https://sippy.ci.openshift.org/sippy-ng/tests/4.9?sortField=net_improvement&sort=asc&filters=%7B%22items%22%3A%5B%7B%22id%22%3A1%2C%22columnField%22%3A%22current_runs%22%2C%22operatorValue%22%3A%22%3E%3D%22%2C%22value%22%3A%2210%22%7D%5D%7D)
Test-by-variant, compare with [this page](https://sippy.ci.openshift.org/sippy-ng/tests/4.9/details?test=A …
> Fix wrapping of test names

- sippy-ng/src/__snapshots__/App.test.js.snap
- sippy-ng/src/jobs/JobTable.css
- sippy-ng/src/jobs/JobTable.js
- sippy-ng/src/jobs/__snapshots__/JobTable.test.js.snap
- sippy-ng/src/releases/__snapshots__/ReleaseOverview.test.js.snap
This shows the number of runs in the cell that contains the percentage,
this was previously in a tooltip but some people didn't find it, so I
guess that's not very discoverable.
> Show runs in the percentage cell for job tables

- pkg/testgridanalysis/testidentification/ocp_variants.go
- sippy-ng/__recordings__/TestAnalysis_2684695171/should-render-correctly_3267003315/recording.har
- sippy-ng/__recordings__/app_527074092/should-render-correctly_3267003315/recording.har
- sippy-ng/__recordings__/release-overview_3101569358/should-render-correctly_3267003315/recording.har
- sippy-ng/src/__snapshots__/App.test.js.snap
- sippy-ng/src/constants.js
- sippy-ng/src/helpers.js
- sippy-ng/src/jobs/__snapshots__/JobRunsTable.test.js.snap
- sippy-ng/src/jobs/__snapshots__/JobTable.test.js.snap
- sippy-ng/src/jobs/__snapshots__/JobsDetail.test.js.snap
- sippy-ng/src/releases/ReleaseOverview.js
- sippy-ng/src/releases/__snapshots__/Install.test.js.snap
- sippy-ng/src/releases/__snapshots__/ReleaseOverview.test.js.snap
- sippy-ng/src/releases/__snapshots__/Upgrades.test.js.snap
- sippy-ng/src/tests/__snapshots__/TestAnalysis.test.js.snap
- sippy-ng/src/tests/__snapshots__/TestsDetail.test.js.snap
- I haven't found being more liberal with adding jobs to the never-stable
list to be particularly helpful, especially with so many failing. I
think each should be investigated, and a bug filed -- and then added to
the never-stable list.
- Exclude never-stable jobs from home page widgets
- Adds a new techpreview variant, for TPNU jobs (being added in https://github.com/openshift/release/pull/19845)
> Reconsider use of never-stable, add techpreview variant

- pkg/testgridanalysis/testidentification/ocp_variants.go
This adds a few jobs to never-stable that have been investigated,
failed for a long period of time (~2 weeks), and have a bug.
> Update never-stable with jobs that have new bugs

- pkg/testgridanalysis/testidentification/ocp_variants.go
- pkg/testgridanalysis/testidentification/test_identification.go
- resources/deploymentconfig.yaml
- scripts/fetchdata.sh
- sippy-ng/src/helpers.js
- sippy-ng/src/jobs/__snapshots__/JobRunsTable.test.js.snap
- sippy-ng/src/tests/__snapshots__/TestAnalysis.test.js.snap
Also removes 3.11, there doesn't appear to be any data for it for some time.
> Add 4.10 to Sippy

- sippy-ng/README.md
- sippy-ng/package-lock.json
- sippy-ng/package.json
- sippy-ng/src/__snapshots__/App.test.js.snap
- sippy-ng/src/datagrid/GridToolbarFilterDateUtils.js
- sippy-ng/src/datagrid/GridToolbarFilterItem.js
- sippy-ng/src/datagrid/GridToolbarFilterMenu.js
- sippy-ng/src/datagrid/utils.js
- sippy-ng/src/helpers.js
- sippy-ng/src/jobs/JobAnalysis.js
- sippy-ng/src/jobs/__snapshots__/JobAnalysis.test.js.snap
- sippy-ng/src/jobs/__snapshots__/JobRunsTable.test.js.snap
- sippy-ng/src/jobs/__snapshots__/JobTable.test.js.snap
- sippy-ng/src/releases/__snapshots__/ReleaseOverview.test.js.snap
- sippy-ng/src/setupTests.js
- sippy-ng/src/tests/__snapshots__/TestTable.test.js.snap
When I added the date/time filtering, I couldn't figure out how to get the picker in UTC, but I found [this issue](https://github.com/mui-org/material-ui-pickers/issues/2098#issuecomment-695360012) which showed extending DateFnUtils and forcing a specific time zone. With this change, the entire UI should be consistently in UTC. 
Where it's possible to add them, there are tooltips showing the local time (via `toLocaleString()`).
This also updates the docs to include some information about the test snapshots and how time is handled.
> Show everything in UTC, with local tooltips where possible

- pkg/testgridanalysis/testidentification/test_identification.go
Sippy is complaining, see https://sippy.ci.openshift.org/sippy-ng/release/4.9
Not sure about periodic-ci-openshift-multiarch-master-nightly-4.9-ocp-e2e-serial-remote-libvirt-s390x yet -- it's using ipi-install-libvirt-install, which is already listed.
> Add install setup test step for openstack proxy jobs

- pkg/testgridanalysis/testidentification/ocp_variants.go
- Assisted IPv6 is passing again
- aws-compact* is passing
- OSD 4.10 is passing (but not 4.9)
> Update never-stable jobs

- pkg/testgridanalysis/testreportconversion/jobresult.go
- sippy-ng/src/datagrid/utils.js
- The 3.11 page isn't loading because the stats package is returning NaN for the quartiles since we only have one job, and NaN's aren't marshallable to JSON.
- The filter tooltip incorrectly omits "not" when explaining a filter (e.g. name not equals "foo")
> Fix a couple of bugs

- sippy-ng/src/__snapshots__/App.test.js.snap
- sippy-ng/src/jobs/JobTable.js
- sippy-ng/src/jobs/__snapshots__/JobTable.test.js.snap
- sippy-ng/src/releases/__snapshots__/ReleaseOverview.test.js.snap
- sippy-ng/src/tests/TestTable.js
- sippy-ng/src/tests/__snapshots__/TestTable.test.js.snap
This change keeps 1 digit after the decimal point, so values that were
being rounded to 100% will now correctly show something like 99.7%.
fixes #291
> Don't round percentages in job/test tables

- sippy-ng/src/releases/ReleaseOverview.js
- sippy-ng/src/releases/TopLevelIndicators.js
> Hide release indicators when there's no data (e.g. for kube)

- go.mod
- go.sum
- pkg/testgridanalysis/testgridconversion/to_raw_data.go
Fix sippy for an upstream testgrid change to Overall test name.
Late yesterday a prod push in testgrid rolled out a change which caused
the Overall test name to change to [jobName].Overall. As a result sippy
could no longer detect jobs completing and assumed everything was still
running.
This change adjusts our code to look for both formats when searching for
the Overall test, which is used to determine success/failure.
> Fix sippy for an upstream testgrid change to Overall test name.

- main.go
- pkg/sippyserver/analyzer.go
- pkg/sippyserver/server.go
- pkg/sippyserver/server_test.go
- scripts/fetchdata-kube.sh
- scripts/fetchdata.sh
Goal is to move the expensive report generation from server startup, where we're stuck waiting roughly 2 minutes per --release with sippy down entirely, to the slower fetchdata scripts. This wait is extremely painful for developing on sippy.
Adds a new --gen-reports command which is to be run separately from --fetch-data, as we may want to run it against a snapshot of historical restored testgrid data.
With this change and using just --release 4.10, sippy api server startup time goes from 2m to 9s.
> Speedup sippy API startup by pre-generating reports

- pkg/sippyserver/server.go
Fix rollout bug when sippy exits with no data.
> speedup nodata fix

- main.go
- pkg/sippyserver/analyzer.go
- pkg/sippyserver/server.go
- pkg/sippyserver/server_test.go
- resources/deploymentconfig.yaml
- scripts/fetchdata-kube.sh
- scripts/fetchdata.sh
- Revert "Bump memory for the fetchdata container, which now generates all reporting data."
- Revert "Fix rollout bug when sippy exits with no data."
- Revert "Restore bugCache.Clear()"
- Revert "Lint fix."
- Revert "Fix unit tests for report loading."
- Revert "Break --gen-reports out into a separate invocation for restoring historical testgrid --local-dir."
- Revert "Move report generation to fetch-data scripts."
> revert speedup

- resources/service-historical.yaml
- resources/service.yaml
oc apply is complaining:
The Service "sippy" is invalid: spec.ports[0].name: Required value
> Add name to sippy service

- resources/deploymentconfig.yaml
Accidentally added to fetchdata container, not the API.
> Fix metrics port for sippy.

- main.go
Apparently this empty log line is worthy of a panic.
Job periodic-ci-openshift-release-master-nightly-4.10-e2e-gcp-rt has bad status FLAKY
panic: runtime error: index out of range [-1]
goroutine 1 [running]:
k8s.io/klog.(*loggingT).printf(0x1dac200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/sippy/vendor/k8s.io/klog/klog.go:704 +0x17a
k8s.io/klog.Verbose.Infof(...)
/go/src/sippy/vendor/k8s.io/klog/klog.go:1176
main.(*Options).Run(0xc0001e2000, 0x0, 0x0)
/go/src/sippy/main.go:214 +0x545
main.main.func1(0xc0001e8000, 0xc0001f2000, 0x0, 0x11)
/go/src/sippy/main.go:77 +0xd7
github.com/spf13/cobra.(*Command).execute(0xc0001e8000, 0xc000138010, 0x11, 0x11, 0xc0001e8000, 0xc000138010)
/go/src/sippy/vendor/github.com/spf13/cobra/command.go:844 +0x2c2 …
> Fix crash in fetchdata container.

- pkg/api/releases.go
- pkg/db/models/release_tag.go
- sippy-ng/src/releases/ReleasePayloadAcceptance.js
This distinguishes between no payload, and rejected payloads.
- Rejected payloads are red.
- Accepted payloads in the last 24 hours are green.
- When we haven't had a payload in several days, but the most recent one
was accepted, we mark it as a warning.
A tooltip also now tells you how many of the most recent payloads
had that status (e.g. The last 9 payloads were rejected.)
> Distinguish between no payload and rejected payloads

- pkg/api/releases.go
- pkg/bigqueryexporter/bigquery.go
- pkg/db/db.go
We're failing to insert job runs because the size of the insert is now
greater than 65,535 (max of int16). This changes the insert to go in
batches.
More importantly, we also only fetch what is exactly needed from
BigQuery.  If our DB is already populated, there's no need to pull
everything from BQ - this gets the highest ID from postgres, and fetches
only the newer records from BQ.
Note: BigQuery does not support autoincrementing primary keys, so we use
`ROW_NUMBER() OVER(...)` -- this produces stable ID's if we do not
remove older records. Currently, we use BQ as append-only and for the
foreseeable future will probably maintain release information
indefinitely (it's not a lot of data).
> db sync: batch insertions and only fetch what is needed from bigquery

- pkg/testgridanalysis/testidentification/ocp_variants.go
- Graduate e2e-metal-ipi-compact and e2e-aws-workers-rhel8.
- Add the almost always permafailing jobs to a list that needs
investigation as TRT has time. They've been close to 0% for a relatively
long period of time, and are causing noise for us.
- This also adds the AWS and metal UPI jobs which are being migrated to
step registry based jobs, and the template jobs have been permafailing.
> Update never-stable for December 1st

- pkg/testgridanalysis/testidentification/ocp_variants.go
This adds the long-term 0% jobs from 4.9 to never-stable. The 4.10
companion jobs are listed with the 4.9 jobs. They may not be failing for
the same reasons but it's likely.
> Add 4.9 permafailing jobs to never-stable

- resources/deploymentconfig.yaml
The new load-database command does the same in-memory computation as the
API server does today, and with a limit of 500M is getting killed before
it can complete. As such our postgres db is likely not being populated
with testgrid data right now. Rest of the script is functioning as
before so no impact to sippy right now.
> Bump fetchdata memory limit to 3G.

- resources/persistentvolumeclaim-data.yaml
- resources/persistentvolumeclaim-db.yaml
we were getting alerts for KubePersistentVolumeUsageCriticalCustomer.
> Increase PVC storage request size

- pkg/testgridanalysis/testidentification/ocp_variants.go
These are all now >25% pass rate per:
https://sippy.ci.openshift.org/sippy-ng/jobs/4.10?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22variants%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22never-stable%22%7D%5D%7D&sort=desc
> Move some improved jobs out of never-stable.

- sippy-ng/src/tests/TestAnalysis.js
- sippy-ng/src/tests/TestAnalysis.test.js
This will allow us to see trends by variant instead of just by job
previously.
> Add Pass Rate By Variant to test analysis page.

- pkg/testgridanalysis/testidentification/ocp_variants.go
Reverts openshift/sippy#351
Metal jobs start passing now.
> Revert "Add all bare metal jobs to never stable due to eol for centos8"

- pkg/api/filterable.go
Some have snuck into origin, the whitespace is filtered out when we
build our filter string in the UI, resulting in no response when trying
to load the test details/analysis page in the UI.
Fix by trimming the test names in memory. Will go fix in master for
origin test names as well.
> Fix filtering for tests with trailing whitespace.

- pkg/testgridanalysis/testgridconversion/to_raw_data.go
- pkg/testgridanalysis/testreportconversion/jobresult.go
We updated for testgrid change in Oct from displaying "Overall" to what
we thought was "jobname.Overall". This is generally consistent but it
turns out prow jobs can specify a testgrid-tab-name annotation, which
changes the test name to that value.Overall, causing sippy to think it
has mass infrastructure failures.
Fix by just looking for suffix ".Overall", this looks consistent across
all our tests.
> Fix upstream kube job processing.

- pkg/api/jobs.go
- pkg/apis/api/types.go
Uses a very fast query crafted by @stbenjam, serializes to the existing API type, and does in-memory filtering.
This can build a report across 4.6-4.10 in about 50ms on my laptop.
> postgres jobs query

- pkg/sippyserver/server.go
- Make release/health endpoitn always available since data comes from DB
- Ensure /api/releases endpoint returns ordered results (e.g. 4.11, 4.10, 4.9)
> Miscellaenous fixes for release endpoints

- pkg/api/job_runs.go
I missed this last week when fixing this API.
> Include test failures in api job run result

- pkg/api/health.go
- pkg/api/job_analysis.go
- pkg/api/job_runs.go
- pkg/api/jobs.go
- pkg/api/releases.go
- pkg/api/tests.go
- pkg/db/query/job_queries.go
- pkg/db/query/test_queries.go
- pkg/filter/filterable.go
- pkg/filter/filterable_test.go
- pkg/html/installhtml/install_by_operators.go
- pkg/html/installhtml/util.go
- pkg/sippyserver/server.go
- pkg/testgridanalysis/testgridanalysisapi/types.go
- pkg/testgridanalysis/testgridconversion/ocp_synthetic_tests.go
- pkg/testgridanalysis/testreportconversion/jobresult.go
Skipped two portions of this that appear unused, the two day statistics,
and the variant health (number of variants whose jobs fully pass over
80%, 60%, or less (fail)).
Refactored filtering out to it's own package due to cyclical imports.
Trending towards moving DB query functions to the db package.
Refactored job report query to be more usable without an http request.
> Port /api/health to db.

- pkg/sippyserver/dbloader.go
These jobs are using randomized test names such as:
assisted-service-64996486bb-lnsms_minikube."github.com/openshift/assisted-service/internal/bminventory.(*bareMetalInventory).V2PostStepReply"
Team is notified, we will manually clean dbs, for now we skip processing
them.
> Skip assisted jobs for time being.

- pkg/db/loader/loader.go
- pkg/sippyserver/dbloader.go
- pkg/testgridanalysis/testgridconversion/kube_synthetic_tests.go
- pkg/testgridanalysis/testgridconversion/ocp_synthetic_tests.go
- pkg/testgridanalysis/testgridconversion/to_raw_data.go
Previously we processed all testgrid job data for a dashboard, then
loaded each into the database. This change adjusts so we read one job at
a time, load it into the db, and then move on to the next.
In local testing this cuts memory use from about 2GB down to about
550MB.
> Load only one testgrid job at a time for memory use.

- scripts/fetchdata.sh
This reverts commit 5b183e76a37bdb93d6e423bb96e11a143d9ebba1.
This didn't seem to help as we were already largely loading one
dashboard at a time. The issue was that 4.11 alone could still blow
memory as we do load every job within that dashboard at once. This has
now been changed to only ever load one testgrid job from one dashboard
at a time.
This needs reverting as we're now doing the full bugzilla update every
invocation.
> Revert "Load releases to the db serially (separate invocations)"

- scripts/fetchdata.sh
We're spending 20 minutes every hour doing this due to the increase in
number of tests. We'll be moving to Jira soon regardless, so no point
investing in this right now.
> Disable bugzilla syncing.

- pkg/api/job_analysis.go
- sippy-ng/src/jobs/Jobs.js
- sippy-ng/src/releases/Install.js
- sippy-ng/src/releases/Upgrades.js
- sippy-ng/src/releases/__snapshots__/Install.test.js.snap
- sippy-ng/src/releases/__snapshots__/Upgrades.test.js.snap
- sippy-ng/src/tests/Tests.js
We may bring some of these back at some point, but for now they are
unweildy, non-functional, and we suspect largely unused.
> Remove some unused secondary UI tabs on Install/Upgrade/Tests pages.

- pkg/sippyserver/dbloader.go
If a job was running when we first saw it, it would be recorded as a
failure and never updated. Running jobs should be skipped.
Our job runs are totally hosed in the db and we will have to rebuild. 111474 of 115769 got recorded like this. Basically everything after the first import.
> Fix running jobs getting recorded in db.

- pkg/testgridanalysis/testgridconversion/ocp_synthetic_tests.go
Previously this was only added in some cases, openshift-tests should
work would be added only if we ran a test that looked like it came from
that suite. This code was new in the postgres work and made the
assumption that if we didn't mark the syntehtic test a fail, it must
have been a pass, when in fact it was intended to have a third didn't
run state.
> Fix addition of synthetic tests for every job run.

- pkg/sippyserver/dbloader.go
Since #382 landed, we should be removing the randomly generated test
names.
> Sync assisted jobs again

- pkg/sippyserver/server.go
I had added code to ensure the releases are sorted, but it doesn't
handle alpha releases, like upstream kube uses. This only casts to an
int array if it contains a '.', which is probably a good enough
heruistic to determine if it's a version or branch name.
> Allow releases to be non-integer values

- pkg/api/job_runs.go
- pkg/api/releases.go
- pkg/apis/api/types.go
- pkg/db/db.go
- sippy-ng/src/helpers.js
- sippy-ng/src/jobs/JobRunsTable.js
*NOTE*: This requires dropping the job runs materialized view to update it.
If you look at tests that mostly flake -- https://sippy.dptools.openshift.org/sippy-ng/tests/4.11/analysis?test=[sig-arch][Late]%20clients%20should%20not%20use%20APIs%20that%20are%20removed%20in%20upcoming%20releases%20[Suite:openshift/conformance/parallel] is a good example, clicking on "All job runs" doesn't show any results (or at least, very few).
We're definitely interested to see jobs where tests flaked, so this adds that option.
For the above test, we now get results like this:
> Allow searching job runs by flakes

- pkg/apis/api/types.go
- sippy-ng/src/helpers.js
- sippy-ng/src/tests/TestTable.js
This show the flake % in a tool tip, and link to runs/flakes separately. I *think* this is better than the current view (click image below to embiggen).
> Show flake % in tool tip and link to runs/flakes separately

- sippy-ng/src/helpers.js
- sippy-ng/src/jobs/JobAnalysis.js
- sippy-ng/src/jobs/JobRunsTable.js
- sippy-ng/src/jobs/JobTable.js
- sippy-ng/src/releases/ReleasePayloadJobRuns.js
- sippy-ng/src/releases/ReleasePayloadPullRequests.js
- sippy-ng/src/releases/ReleasePayloadTable.js
- sippy-ng/src/tests/TestTable.js
- sippy-ng/src/workloadmetrics/WorkloadMetricsTable.js
A follow-up to ensure square brackets are quoted in JSON encoded
URI params.
> Use custom serializer for use-query-params

- pkg/filter/filterable.go
Filtering from the release tag page is broken, since it expects
to get a filterable passed it, but release tag doesn't send one. This
adds a nil check and default value.
See https://sippy.dptools.openshift.org/sippy-ng/release/4.11/tags, and
try to filter by tag name "contains", e.g. :https://sippy.dptools.openshift.org/sippy-ng/release/4.11/tags?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522release_tag%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%25222022-05-01%2522%257D%255D%252C%2522linkOperator%2522%253A%2522and%2522%257D
> Allow filterable to be empty on SQL filtering

- sippy-ng/src/jobs/JobTable.js
The autocomplete I added last week requires you to enter the full name
of a job to work.  So, you can't easily filter on a substring (e.g. name
contains aws), this disables it until I figure out how I get it to
behave correctly.
> Disable autocomplete on job names

- pkg/api/health.go
- pkg/api/releases.go
- pkg/api/releases_test.go
- pkg/apis/api/types.go
- pkg/apis/sippy/v1/types.go
- pkg/db/models/releases.go
- pkg/db/query/payload_queries.go
- pkg/db/query/release_queries.go
- pkg/sippyserver/server.go
Refactor for release health query re-use.
Display warnings on releaes overview pages if we detect an RHCOS version that doesn't seem to match the release it's in a payload for. (i.e. release 4.11 should match RHCOS version 411.86.202205030351-0)
Adds a gauge metric for the count of warnings per release. It won't tell you what's wrong, but it will tell you something is and can link you to the overview where you get the details easily.
> rhcos ver check

- sippy-ng/src/App.js
- sippy-ng/src/components/Sidebar.js
Opening these is a very common first two clicks that are probably not
necessary and we can spare the real estate by default.
> Open sidebar and expand first release by default.

- sippy-ng/src/App.js
- sippy-ng/src/components/Sidebar.js
- sippy-ng/src/helpers.js
Use some default filters on Jobs and Tests.
Remove links to workload metrics (broken) and legacy interface (gone)
> Cleanup side bar

- DEVELOPMENT.md
I noticed when I was trying to create a migration for https://github.com/openshift/sippy/pull/379/files#diff-2a6d9a9f885f73e1ce4ac191e98863e8dfb0edbb1ca1881062b74a72c1108e42.
When creating a new migration, you need to specify it is a `sql`
migration. The default is go, and trying to migrate in our current
configuration results in an error:
```
2022/05/18 08:15:37 goose run: ERROR
dbmigration/20220518081530_prow_job_kind.go: failed to run Go migration:
Go functions must be registered and built into a custom binary (see
https://github.com/pressly/goose/tree/master/examples/go-migrations)
```
> Clarify migration command

- pkg/api/job_analysis.go
- sippy-ng/src/datagrid/GridToolbarFilterDateUtils.js
When adjusting time in the filters dialog, the clock shows local time
but the field shows UTC. This fixes it so everything is correctly in
UTC.
> Show UTC consistently on job analysis

- pkg/api/job_analysis.go
This surfaced when I was working locally with a backup of the prod db,
not sure why it doesn't show up in prod initially but it looks like this
can crash in some cases due to the missing UTC in key.
> Fix a crash in some situations due to missing UTC() usage.

- main.go
- scripts/fetchdata-prow.sh
This adds a script to sync prow data, and also makes some small changes
to the main.go for using env var for google credentials, and not
requiring a data dir when operating in Prow-only mode.
> Add script for fetching prow data, and some adjustments to sippy arguments

- pkg/prowloader/gcs/gcs_jobrun.go
I have an example of the Prow censor finding a secret integer value in
the `time` field of a junit test, which makes it unparsable:
```
time="2022-05-31T18:09:14.954Z" level=warning msg="failed to get junit
test suites: error parsing content for jobrun strconv.ParseFloat:
parsing \"0.0XXXXX687\": invalid syntax in file
pr-logs/pull/openshift_installer/5951/pull-ci-openshift-installer-master-e2e-crc/1531677474260258816/artifacts/junit_operator.xml
path
pr-logs/pull/openshift_installer/5951/pull-ci-openshift-installer-master-e2e-crc/1531677474260258816"
```
This error is fatal and causes the prow importer to stop. This makes it
non-fatal. We log it but continue on.
> Skip bad junits instead of failing the whole import

- dbmigration/20220602115442_fix_job_run_matview_counts.sql
[TRT-255](https://issues.redhat.com//browse/TRT-255)
The original logic in this matview was bugged where things were being
double counted. This moves the aggregation to the subqueries, resulting
in a simpler and also accurate count of failed and flaked tests.
Old incorrect count:
```
-[ RECORD 1 ]----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------
id                     | 1530459072720015360
[...]
test_flakes            | 248
test_failures          | 248
```
New correct count:
```
-[ RECORD 1 ]----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------
id …
```
> Fix job run page counts

- sippy-ng/src/tests/TestTable.js
As with #420, filtering on test substrings is also broken and this is a
fairly useful feature. Disabling as well until it's known how to make it
work for both use cases.
> Disable test table name autocomplete.

- sippy-ng/src/components/Sidebar.js
- sippy-ng/src/constants.js
- sippy-ng/src/releases/ReleaseOverview.js
Bumps the >= 1 current runs filter up to roughly once per day for both tests and jobs on the overview, and the tests sidebar link.
Also filters out openshift-tests should work, I'm less sure about this one but looking by variant, it does fill up the results and hide the actual tests we'd go after. It's somewhat interesting, but I think more interesting is what tests are causing the overall tests should work to change it's pass rate.
> Improve default test table filters.

- dbmigration/20220603154712_fix_job_run_matview_results.sql
[TRT-286](https://issues.redhat.com//browse/TRT-286)
Small tweak to the matview to LEFT JOIN instead of just plan JOIN on
flaked/failed tests.
Join alone requires an entry in both tables, meaning the mat view table
currently only has job runs where we have BOTH failure and flaked tests.
This excludes a ton of jobs, but it was noticed because we have no
install or upgrade tests which don't have flakes on those, thus they're
entirely omitted.
> Job run matview should LEFT JOIN on failed/flakes

- main.go
- pkg/sippyserver/dbloader.go
- pkg/testgridanalysis/testgridconversion/to_raw_data.go
- resources/deploymentconfig.yaml
Also drops --end-day which was can be accomplished with --num-days.
This change makes it possible to load historical data into the sippy db, even if we can't yet view the UI once done.
> Hookup -start-day and --num-days for load-database, improve help.

- sippy-ng/src/helpers.js
- sippy-ng/src/tests/TestAnalysis.js
- sippy-ng/src/tests/TestTable.js
This ensures that square brackets are encoded. While not required, it
makes the links compatible with markdown and jira.
> Safe-encode string param for test analysis page

- sippy-ng/src/jobs/JobStackedChart.js
Follow-up for [TRT-259](https://issues.redhat.com//browse/TRT-259)
This plots a second axis on the stacked chart for job run results
that shows the total count of job runs for that period.
> Show run line on job stacked chart

- pkg/prowloader/gcs/gcs_jobrun.go
- pkg/prowloader/prow.go
- Oof, some bad handling of prow job run ID's needed serious refactoring.  Prow job runs table has duplicates :facepalm: 
- Reduced some memory usage
- Create tests in batches like we do for testgrid
- Skip running jobs - we only want jobs in a terminal state
> Fix some things in prow-based sippy

- sippy-ng/src/components/Sidebar.js
Currently if you visit a 4.10 link, the 4.11 release is expanded in the
sidebar: https://sippy.dptools.openshift.org/sippy-ng/jobs/4.10
This tries to get the release from the URL and expand that one on first
loading of a link like the above. Using a React context would be better,
but unfortunately we're pretty deeply tied to passing release as a prop
(inaccessible to the sidebar).
> Guess which release to open in sidebar

- main.go
- scripts/fetchdata-kube.sh
- scripts/fetchdata-prow.sh
- scripts/fetchdata.sh
We try to infer the mode based on the dashboards available, but this
doesn't work in Sippy prow (it did locally for me since I had testgrid
data around...).
This changes --variant to --mode, which selects both the variant and
synthetic test manager.
> Explicity set mode for synthetic tests

- pkg/testidentification/ocp_variants.go
Sippy is uncertain with the data due to naming convention. 
Fixes name for heterogeneous jobs https://github.com/openshift/release/pull/29684
> Updating variant heterogeneous

- pkg/api/health.go
[TRT-323](https://issues.redhat.com//browse/TRT-323)
When providing statistics about installs, upgrade-minor installs a
previous release and should not be counted against the current release.
> Exclude minor upgrades from installation stats

- pkg/api/tests.go
- sippy-ng/src/components/PassRateIcon.js
- sippy-ng/src/datagrid/GridToolbar.js
- sippy-ng/src/datagrid/GridToolbarViewSelector.js
- sippy-ng/src/datagrid/GridView.js
- sippy-ng/src/tests/TestTable.js
[TRT-301](https://issues.redhat.com//browse/TRT-301)
This adds a "View" toolbar item, that allows customizing which columns
are shown. This lets us on the test page create working and flakes
views, for example.
> Add UI mechanism for customized views

- pkg/apis/prow/prow.go
- pkg/db/db.go
- pkg/db/models/prow.go
- pkg/prowloader/prow.go
[TRT-278](https://issues.redhat.com//browse/TRT-278)
This saves the PR data for a prow job run.  This will eventually allow
us to do analysis on how many retests  it takes to land certain PR's.
It also lets us know which org/repo is linked to a presubmit job.
> Save PR data for prow imported job runs

- pkg/db/query/payload_queries.go
- pkg/sippyserver/metrics/metrics.go
Part of [TRT-376](https://issues.redhat.com//browse/TRT-376)
This adds a metric for the number of hours since the last OS upgrade.
The idea is we can alert when we haven't gotten a new OS in a certain
number of hours.
> Add metric for hours since last OS upgrade

- pkg/api/releases.go
- pkg/apis/api/types.go
- pkg/db/models/prow.go
Added better insight into number of times a test failed across the
requested number of most recent payloads, and a blocker score indicating
how likely this is to be a payload blocker.
> Improvements for experimental payload stream analysis API.

- pkg/db/models/prow.go
I tried to do some direct queries on prow_job_run_tests by test_id and
wow is it slow.
We should merge this early morning or at the end of the day, takes about 30 minutes to run.
> Add some missing indexes on ID's

- pkg/api/health.go
- pkg/testgridanalysis/testreportconversion/jobresult.go
- pkg/testidentification/ocp_variants.go
- sippy-ng/src/components/Sidebar.js
- sippy-ng/src/constants.js
- sippy-ng/src/helpers.js
- sippy-ng/src/releases/ReleaseOverview.js
- sippy-ng/src/tests/TestAnalysis.js
[TRT-404](https://issues.redhat.com//browse/TRT-404)
When the first techpreview jobs got added they were nearly always
failing so it was added to our default filters along with never-stable.
That's no longer the case, so this changes makes it get treated like any
other variant.
> No longer consider techpreview unstable

- pkg/releasesync/changelog_parser.go
[TRT-414](https://issues.redhat.com//browse/TRT-414)
Sippy prow isn't currently syncing due to this error:
```
panic: ERROR: insert or update on table "release_tag_pull_requests" violates foreign key constraint "fk_release_tag_pull_requests_release_pull_request" (SQLSTATE 23503)
```
The release controller has a bug when merging from upstream repos: it
assumes a mentioned PR belongs to the openshift fork, and makes a link
to it, despite the PR actually belonging to upstream.
If you look at
https://arm64.ocp.releases.ci.openshift.org/releasestream/4.12.0-0.nightly-arm64/release/4.12.0-0.nightly-arm64-2022-07-24-180825,
gcp-pd-csi-driver lists PR 1 multiple times, but only 1 refers to the
actual first PR to openshift, the other is from upstream.
This change will just unbreak fetching data, …
> Ensure we don't add duplicate PR's

- pkg/db/models/releases.go
- scripts/rejected-payloads.md
- scripts/rejected-payloads.py
- sippy-ng/src/releases/ReleasePayloadTable.js
[TRT-416](https://issues.redhat.com//browse/TRT-416)
- Add a new failed payload categorization for cloud quota issues.
- Sort payloads by tag descending.
- List descriptions for payload reject reasons and fix dangerous list() override.
- Display the list of failed jobs and the tests that failed within them (max 5) once a payload is selected to categorize.
- Allow adding a note for why payload was categorized as it was (optional).
- Display notes from TRT for reject reason as a tooltip in UI table.
- Reorder payload categorize script slightly to put most relevant info at the top.
> new payload category

- pkg/synthetictests/ocp_synthetic_tests.go
- pkg/synthetictests/ocp_synthetic_tests_test.go
- pkg/testgridanalysis/testgridconversion/to_raw_data.go
Sippy prow is missing some synthetic test data because the suite isn't
removed like it is on TestGrid. I attempted to fix this in
https://github.com/openshift/sippy/pull/488, but I didn't realize
the synthetic test generation code was adding the sippy suite name to
the test name directly *as well as* the junit testsuite.
This ensures junits are correct: suite name only in the testsuite, and
where required for testgrid, joins them.
> Correctly handle suite names for prow

- pkg/prowloader/prow.go
[TRT-439](https://issues.redhat.com//browse/TRT-439)
Prow-based sippy doesn't ignore skipped test cases, but instead
considers them a success. This is throwing off success percentages
for tests that have criteria that gets them skipped. This was hard to
spot since *most* conformance tests run on *most* jobs, so the numbers
between the two sippys are very close except on certain tests.
For example sippy-prow says `Cluster topology single node tests Verify
that OpenShift components deploy one replica in SingleReplica topology
mode` has thousands of runs in the last 7 days, but testgrid sippy only
shows 160. It's been counted on all the platforms it was skipped (i.e.
all HA job runs).
> Ignore skipped test cases

- pkg/api/tests.go
- pkg/apis/api/types.go
- pkg/db/matviews.go
- sippy-ng/package-lock.json
- sippy-ng/src/tests/TestTable.js
Reverts openshift/sippy#518
Any test that doesn't have a suite name ends up excluded from the matview, resulting in a bunch of missing data:
```
sippy_openshift=> SELECT * FROM prow_test_report_7d_matview WHERE release = '4.12' AND name LIKE '%cluster install%';
id | name | suite_name | previous_successes | previous_flakes | previous_failures | previous_runs | current_successes | current_flakes | current_failures | current_runs | variants | release 
----+------+------------+--------------------+-----------------+-------------------+---------------+-------------------+----------------+------------------+--------------+----------+---------
(0 rows)
```
I think it needs to be a LEFT JOIN [here](https://github.com/openshift/sippy/pull/518/files#diff-7fa1b9fbef139e2c0d9eadf51d97fa898c9360bcfcbd …
> Revert "Differentiate on test suite in NURPs test tables."

- config/openshift-customizations.yaml
The auto config generator isn't pulling the 3.11 jobs out of the release
repo, they might be configured differently.  This adds them manually.
> Add 3.11 jobs for Sippy

- pkg/db/db.go
- pkg/db/functions.go
- pkg/db/matviews.go
Possible alternative to #532 which would preserve ability to update indicies without requiring a matview update.
This change returns a bool when we update schema that will be true if we detected a schema change and did an update. This can be passed to as a force to the index schema update telling it to sync regardless if we see a hash change or not.
> Fix loss of indicies when matviews change.

- pkg/sippyserver/metrics/metrics.go
- pkg/sippyserver/parameters.go
- pkg/util/utils.go
[TRT-328](https://issues.redhat.com//browse/TRT-328)
This adds a new pass ratio metric for build cluster health, e.g.:
```
sippy_build_cluster_pass_ratio{cluster="build01",period="default"} 0.7524868344060854
sippy_build_cluster_pass_ratio{cluster="build01",period="twoDay"} 0.7578231292517007
sippy_build_cluster_pass_ratio{cluster="build02",period="default"} 0.8801810385898047
sippy_build_cluster_pass_ratio{cluster="build02",period="twoDay"} 0.8487348734873487
sippy_build_cluster_pass_ratio{cluster="build03",period="default"} 0.8037963761863675
sippy_build_cluster_pass_ratio{cluster="build03",period="twoDay"} 0.7949526813880127
sippy_build_cluster_pass_ratio{cluster="build04",period="default"} 0.8026266416510319
sippy_build_cluster_pass_ratio{cluster="build04",period="twoDay"} 0.7825 …
```
> Add metrics for build cluster health

- pkg/db/models/releases.go
This syntax resulted in a column named: prow_job_run_id,index:unique
We needed the semi-colon to tell gorm to separate the two, index and
unique are related thus the use of a comma, but if you're moving to a
different directive you  need to use semi-colon.
This error is completely silent because the old prow_job_run_id column
still exists, won't show up in prow or any dev setup that uses a prod
db. If you make a fresh db it will though.
We've got some bad data to cleanup since this change merged.
> Fix broken columns on release_job_runs.

- config/openshift-customizations.yaml
[TRT-503](https://issues.redhat.com//browse/TRT-503)
The openshift/windows* repos all use presubmits in the format of
`<branch>-<platform>-e2e` instead of `<branch>-e2e-<platform>`. This
adjusts the regex for presubmits to capture those.
> Adjust presubmit regex to pull in additional jobs

- pkg/prowloader/prow.go
We're creating some tests that start with a period currently.
> Don't add '.' to test name if there is no suite

- pkg/api/job_analysis.go
- pkg/apis/sippyprocessing/v1/types.go
- pkg/prowloader/testconversion/testconversion.go
- pkg/synthetictests/ocp_synthetic_tests.go
[TRT-526](https://issues.redhat.com//browse/TRT-526)
Currently in prow-based Sippy, CI infrastructure failures are showing up
as a general non-e2e failure ('f'). This is because failed and errored
are considered the same. Instead, an errored prow job should be
considered a failure before setup (a.k.a. likely CI infra).
TestGrid sippy had no way to know this as it had no distinct error state, it
just say a failed job without install results, which it called JobNoResults. This
change also renames it to more correctly be failure before setup (which is
how the UI shows it).
> Show CI infra failures as overall status 'n'

- pkg/db/query/test_queries.go
- sippy-ng/src/tests/TestAnalysis.js
- sippy-ng/src/tests/TestTable.js
Fixes [TRT-536](https://issues.redhat.com//browse/TRT-536) and [TRT-486](https://issues.redhat.com//browse/TRT-486)
- Joins using `=` will not work when the fields are null, which is the case for tests without a suite.  A workaround for this is joining on `x.a IS NOT DISTINCT FROM y.a`.
- UI clean up test filter list, only show nurps with runs, etc.
> Fix test queries to show nurp when suites are null, and misc ui clean-ups

- pkg/db/matviews.go
Refreshing the matviews for tests are now taking about 40 minutes each. Looking at the query, I noticed we are not including a WHERE clause to filter out older runs. The timestamp filtering only happens in the COALESCE, meaning postgres has to loop over all of the rows for all tests from all runs from all time.
The difference here is substantial. Matview refresh time goes from 40 minutes to about 4.
Old costs:
```
GroupAggregate  (cost=26144776.29..119329657.85 rows=254166812 width=331)
```
This version:
```
GroupAggregate  (cost=6592283.66..17031032.88 rows=30129839 width=331)
```
> Improve performance of test 7d and 2d matviews by 10x

- pkg/synthetictests/ocp_synthetic_tests.go
`if result.Errored` needed to go before the Running case to be detected.  We never hit this case currently.
> Fix CI infra failure logic

- pkg/sippyserver/server.go
If a user tries to access a UI page that's non-existent, Sippy panics. It should just return a gentler 404 instead.
```
2022/09/13 18:37:21 http: panic serving 10.129.2.9:42468: open repositories/Presubmits/: invalid name
goroutine 5758 [running]:
net/http.(*conn).serve.func1()
/usr/lib/golang/src/net/http/server.go:1802 +0xb9
panic({0x11df800, 0xc000ced9e0})
/usr/lib/golang/src/runtime/panic.go:1047 +0x266
github.com/openshift/sippy/pkg/sippyserver.(*Server).Serve.func1({0x1c15668, 0xc0006d6540}, 0xc004452b00)
/go/src/sippy/pkg/sippyserver/server.go:747 +0x268
net/http.HandlerFunc.ServeHTTP(0x0, {0x1c15668, 0xc0006d6540}, 0x6320cde1)
/usr/lib/golang/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0006d6540, {0x1c15668, 0xc0006d6540}, 0xc004452b00) …
```
> Sippy should not panic if path is not found

- sippy-ng/src/App.js
Adds a floating action button to open a GitHub issue. We could link to jira, but it's a bit more difficult for non-Red Hatters to contribute if Kube sippy becomes more commonly used.  Open to changing it if we prefer to direct people to jira.
We can also always triage them and move them jira if we'll take action on it.
> Add a feedback button on Sippy

- pkg/api/job_runs.go
- pkg/apis/api/types.go
- pkg/sippyserver/parameters.go
- pkg/sippyserver/server.go
- sippy-ng/src/jobs/JobRunsTable.js
Part of [TRT-314](https://issues.redhat.com//browse/TRT-314)
Loading the job runs page takes a lot of memory, since we have 80K rows
and we're sending them all to the client. It causes a big spike in Sippy
memory usage.
This enables server-side pagination for job runs. I only did one page since
it's the worst offender, but we should convert most API's I think.  Perhaps
a good issue for someone not familiar with sippy to tackle, since the blueprint
is in this PR for how to do the rest of the pages.
> Enable job runs pagination to be server-side

- DEVELOPMENT.md
- Makefile
- main.go
- scripts/e2e.sh
- test/e2e/jobs_test.go
- test/e2e/util/e2erequest.go
Very basic for now, make e2e will run the script which:
- builds sippy
- launches a postgresql container
- imports last 12 hours of job data from prow for an old release, 4.7 (roughly 5 minutes on my system)
- launches the sippy api in a subprocess and gives it a little time to start up and refresh views
- runs e2e tests defined as standard go tests, which hit the API.
Only one test now that lists job reports and checks it got something back. My plan is to get this in as it covers a lot of ground and we can expand to other tests as we go in future.
[TRT-246](https://issues.redhat.com//browse/TRT-246)
> Very basic e2e tests for presubmit job.

- pkg/api/job_runs.go
[TRT-576](https://issues.redhat.com//browse/TRT-576) - fixes showing build cluster job runs when there is no release associated.
> TRT-576 add check for release

- scripts/fetchdata.sh
There's some weird payload that's preventing sippy from syncing, it's list of pull requests is really huge, and then things end up getting killed on the INSERT due to OOM.
It's Saturday so I'm just going to disable it so prow syncing continues to work, and then we can sort it out on Monday.
```
2022/10/01 12:16:46 /go/src/sippy/pkg/releasesync/releasesync.go:97 record not found
[1.140ms] [rows:0] SELECT * FROM "release_pull_requests" WHERE url = 'https://github.com/openshift/kubernetes/pull/97965' AND name = 'ibm-vpc-block-csi-driver-operator' AND "release_pull_requests"."deleted_at" IS NULL ORDER BY "release_pull_requests"."id" LIMIT 1
2022/10/01 12:16:46 /go/src/sippy/pkg/releasesync/releasesync.go:75
[6.725ms] [rows:36] INSERT INTO "release_repositories" …
```
> Temporarily disable release syncing

- pkg/releasesync/releasesync.go
- scripts/fetchdata.sh
[TRT-585](https://issues.redhat.com//browse/TRT-585)
When creating release tags that include multiple revendors of libraries
with large numbers of commits (say, kube), we're trying to create it
all in one single INSERT which doesn't work well. We need to tell gorm
to create things in batches.
`CreateBatchSize` works for releations (in this case PR's).
> Sync release tag associations in batches

- pkg/prowloader/github/github.go
- pkg/prowloader/github/github_test.go
- pkg/prowloader/prow.go
[TRT-585](https://issues.redhat.com//browse/TRT-585)
We track PR's based off the PR and the HEAD SHA.  We used to query GitHub for each SHA, instead of just once per PR. This adjusts the caching and syncing logic to ensure we only hit the API once for a PR.
GitHub limits us to 5,000 requests per hour. We know more SHA's than that now, so we're hitting the limits.  We have much fewer distinct PR's, so this should fix the rate limiting.
> Only call GitHub once per PR

- pkg/releasesync/changelog_parser.go
[TRT-585](https://issues.redhat.com//browse/TRT-585)
https://ppc64le.ocp.releases.ci.openshift.org/releasestream/4.12.0-0.nightly-ppc64le/release/4.12.0-0.nightly-ppc64le-2022-09-30-200103 had 235,000 pull requests in it's diff, and it made sippy quite unhappy.
We could probably improve the release syncing code to handle this better, but for now just set an upper bound of what's reasonable.
> Set an upper bound on PR's for a release tag

- pkg/db/loader/issue_types_internal.go
- pkg/db/loader/issues.go
- pkg/sippyserver/dbloader.go
- pkg/sippyserver/dbloader_test.go
Jira issues are annotated with incident=variants=xxxx. We will get jira cards with this annotation and parse the variants. Any jobs whose variants is a superset of the issue variant will include the corresponding issue in bug_jobs table.
> Get issues by variants

- pkg/db/models/prow.go
- pkg/db/models/releases.go
- scripts/clear-constraints-for-cascading.sql
[TRT-599](https://issues.redhat.com//browse/TRT-599)
Note: proposed process after merging is 1) scale openshift and kube sippys down, 2) run scripts/clear-constraints-for-cascading.sql, 3) wait for image to be rebuilt, 4) scale back up
When deleting a DB row that has relations, these are not automatically deleted and the foreign key constraints prevent you from actually deleting the row. We need to cascade the deletes, however gorm does not support patching constraints[1], therefore we have to delete them.
There's a one-time SQL script in scripts/ that we can run to clear the constraints, which gorm wil re-add back. I've tested this on a production database restore and it seems to do what I expect. We could write our own migrator, but it looks somewhat challenging, and this is probably a …
> Cascade delete for all relevant DB models

- test/e2e/util/e2erequest.go
This helps out [TRT-246](https://issues.redhat.com//browse/TRT-246) and let's us remove the sed in the sippy-e2e-commands.sh script in [this PR](https://github.com/openshift/release/pull/32818/files).
If no environment variables are set, you get the existing behavior.
If you do this, you will get to use those values:
```
export SIPPY_ENDPOINT=sippy-server-postgres.apps-crc.testing
export SIPPY_API_PORT=80
```
> Allow use of environment variables for sippy e2e test

- go.mod
- go.sum
- pkg/api/job_runs.go
- pkg/api/job_runs_test.go
- pkg/apis/api/types.go
- pkg/db/models/prow.go
- pkg/sippyserver/server.go
- vendor/github.com/stretchr/testify/assert/assertion_compare.go
- vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
- vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
- vendor/github.com/stretchr/testify/assert/assertion_format.go
- vendor/github.com/stretchr/testify/assert/assertion_order.go
- vendor/github.com/stretchr/testify/assert/assertions.go
- vendor/github.com/stretchr/testify/require/doc.go
- vendor/github.com/stretchr/testify/require/forward_requirements.go
- vendor/github.com/stretchr/testify/require/require.go
- vendor/github.com/stretchr/testify/require/require.go.tmpl
- vendor/github.com/stretchr/testify/require/require_forward.go
- vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
- vendor/github.com/stretchr/testify/require/requirements.go
- vendor/gopkg.in/yaml.v3/decode.go
- vendor/gopkg.in/yaml.v3/parserc.go
- vendor/modules.txt
Done for [TRT-591](https://issues.redhat.com//browse/TRT-591) as part of epic TRT-601. 
This API will analyze the test failures within a job run, classify each as high/medium/low risk based on their pass rates over the past week, and set an overall risk for the jobrun itself. Future logic may be added to make this more intelligent in the future. No test failures = no risk. Mass test failures = high risk, regardless if they were all low risk failures. (we do not analyze each test failure if more than 20) 
Risk levels are represented as an integer for programatic interpretation, as well as a human readable string. Determinations are also accompanied by human readable "reasons" for display.
If we cannot find test results over past week for a test failure, we classify as Unknown, and that is …
> Add API for analyzing risk of test failures in a job run

- pkg/testidentification/ocp_variants.go
[TRT-621](https://issues.redhat.com//browse/TRT-621)
This adds a variant for new microshift jobs, and marks them as never-stable so they are excluded from overall metrics until they're stable.
> Add microshift variant, and mark those jobs as never-stable

- pkg/sippyserver/metrics/metrics.go
50% previously, which was roughly the test failing somewhere in two
consecutive payloads. Raising this to 3 before we alert as we've seen
this flaking and want to tone down our alerting.
[TRT-642](https://issues.redhat.com//browse/TRT-642)
> Raise the score required to consider a test blocking a payload stream.

- resources/deploymentconfig.yaml
- scripts/fetchdata-testgrid.sh
- scripts/fetchdata.sh
Regarding TRT-648.
I wonder if deploymentconfig.yaml is used because the one in [continuous-release-jobs repo](https://github.com/openshift/continuous-release-jobs/blob/ad0c0f453828ddbd5a96a55bcbd38a0b0e67b1ea/config/clusters/dpcr/services/sippy/deploymentconfig.yaml) seems the be the in use when we deploy on the DPCR cluster.  I include it in this PR and if it makes sense to delete it, I will.
this PR is related: https://github.com/openshift/continuous-release-jobs/pull/1237
> Get sippy ready for 4.13

- pkg/db/models/prow.go
- pkg/db/query/test_queries.go
This speeds up the durations API by indexing prow job runs on the date contained in a time stamp.  See https://gist.github.com/cobusc/5875282
Without this index:
```
Planning Time: 2.047 ms
Execution Time: 14451.498 ms
```
With the index:
```
Planning Time: 2.768 ms
Execution Time: 12.823 ms
```
> Add index on timestamp by date

- DEVELOPMENT.md
- Dockerfile
- e2e-scripts/run-e2e.sh
- e2e-scripts/sippy-e2e-sippy-e2e-setup-commands.sh
- e2e-scripts/sippy-e2e-sippy-e2e-test-commands.sh
Re: [TRT-638](https://issues.redhat.com//browse/TRT-638)
* The trailing `/` on Dockerfile was needed because `minikube image build` fails on it missing.
* The `sippy-e2e-*-command.sh` scripts are pulled from the version in [this PR](https://github.com/openshift/release/pull/33653) where they have been tested in prow.
* `run-e2e.sh` is introduced to make is easier to run the scripts locally.
This will do nothing with CI unless this [release PR](https://github.com/openshift/release/pull/33694) merges.
> Be able to run sippy-e2e locally from sippy repo

- Makefile
- hack/go-lint.sh
Local developers may have various different versions of go and golangci-lint installed. For consistency, we should run it from a container that matches the versions used in CI.
This does require a user to have working rootless containers on their machine.
> Move lint to container for consistency

- pkg/api/job_runs.go
- pkg/api/job_runs_test.go
- pkg/apis/api/types.go
[TRT-679](https://issues.redhat.com//browse/TRT-679)
- Add CompareRelease field to risk analysis API
- risk analysis: Treat 0 runs the same as no results
- risk analysis: skip openshift-tests should work
> risk analysis fixes

- scripts/sql/find-job-runs-with-alert.sql
- scripts/sql/find-job-runs-with-pathological-event.sql
- scripts/sql/most-common-alerts.sql
- scripts/sql/most-common-pathological-events.sql
Adds an sql query for both firing alerts, and pathologically repeating events.
[TRT-723](https://issues.redhat.com//browse/TRT-723)
> Add sql queries for aggregating most common backstop issues

- pkg/api/job_runs.go
This was causing Cluster should remain functional during upgrade to show up in the risk analysis with unknown state, because we don't import this in sippy.
[TRT-703](https://issues.redhat.com//browse/TRT-703)
> Skip ignored tests during risk analysis

- main.go
- pkg/db/db.go
- pkg/db/models/models.go
- pkg/snapshot/snapshot.go
Query various overview health APIs, store the resulting JSON in the db.
We can later use this data via scripts or the UI to compare current
release vs past releases on their GA date.
Implemented in a fashion such that we could take snapshots at other
arbitrary times if desired.
[TRT-727](https://issues.redhat.com//browse/TRT-727)
> Add support for GA snapshots.

- sippy-ng/src/jobs/JobTable.js
Currently we always render the TestGrid button regardless of whether Sippy knows the testgrid link for that job.  This change makes it only render when we know the URL. This will make it easier to identify jobs where we don't know the TG dashboard, as well as not showing on jobs that will never have one (e.g. presubmits).
> Only render testgrid link when present

- pkg/db/matviews.go
- pkg/db/query/test_queries.go
[TRT-784](https://issues.redhat.com//browse/TRT-784)
The number of runs, successes, failures, etc are scaled by the number of open bugs. Each bug causes new rows to be created with the LEFT JOIN.
We only really noticed because of how many bugs pathological events has, making ovirt appear to have way too many runs. The good thing is the percentages are accurate (all values are scaled by the # of open bugs).
The bug count was also summed and showed aggregated, causing pathological events to show up with 1200+ open bugs (we're not *quite* there yet).
> Fix counts on test materialized views

- pkg/sippyserver/server.go
- vendor/github.com/prometheus/client_golang/prometheus/push/push.go
- vendor/modules.txt
[TRT-738](https://issues.redhat.com//browse/TRT-738)
If SIPPY_PROMETHEUS_PUSHGATEWAY environment variable is set, metrics will be pushed to a prometheus pushgateway when refreshing materialized views.
> Add support for sending matview metrics to prometheus pushgateway

- sippy-ng/src/tests/TestAnalysis.js
TRT-843
Currently test names aren't being URI encoded for the bugs API, causing errors when there's characters like `#` in a test name.
Example: https://sippy.dptools.openshift.org/sippy-ng/tests/4.13/analysis?test=Create%20the%20different%20workloads%20from%20Add%20page.Create%20the%20different%20workloads%20from%20Add%20page%20Create%20Sample%20Application%20from%20Add%20page%3A%20GS-03-TC05%20(example%20%231)
> Test analysis page should URI encode test names for bugs API

- main.go
- pkg/db/query/misc_queries.go
- pkg/sippyserver/metrics/metrics.go
- pkg/testidentification/kube_variants.go
- pkg/testidentification/no_variants.go
- pkg/testidentification/ocp_variants.go
- pkg/testidentification/variants.go
[TRT-858](https://issues.redhat.com//browse/TRT-858)
This adds new metrics for per-platform infrastructure success rates. This is a global value not constrained by releases, but we could scope it by release if we thought it was useful.
This metric is the true success rate, so alerts based on this value will be taking into account both failures and flakes (i.e. retrying infra worked). This will let us make sure that we don't excessively start flaking on infra and not detect the problem.
> Add infrastructure success metrics

- pkg/db/query/misc_queries.go
I had made this consistent so everything uses 'current' for the 7 day period, but missed one place.
This also adds timestamps so we can see how long building these stats takes in the log.
> Fix rename of default -> current for infra success metrics

- pkg/prowloader/github/github.go
- pkg/prowloader/github/github_test.go
[TRT-859](https://issues.redhat.com//browse/TRT-859)
I believe we want the html url for the pull request info:
```
$ curl https://api.github.com/repos/openshift/cluster-resource-override-admission-operator/pulls/101 > x.json
$ cat x.json |jq .url
"https://api.github.com/repos/openshift/cluster-resource-override-admission-operator/pulls/101"
$ cat x.json |jq .html_url
"https://github.com/openshift/cluster-resource-override-admission-operator/pull/101"
```
The .html_url is the html link to the pull request which is what a user would want to click on vs. the other link in .url which is the raw api endpoint.
> Retrieve html url so that we can link to the actual PR in sippy UI

- pkg/api/health.go
- pkg/apis/api/types.go
- pkg/db/query/test_queries.go
- sippy-ng/src/components/SummaryCard.js
- sippy-ng/src/releases/InstallTopLevelIndicators.js
- sippy-ng/src/releases/TopLevelIndicators.js
- test/e2e/releases_test.go
Infrastructure is the only one that flakes at the moment, but this changes the view to show working (success + flakes) as well as showing flakes in the chart. The current view shows success % only, and shows failure percentage incorrectly
New view:
> Move release indicators to  "working" percentage and include flakes

- pkg/api/health.go
- pkg/api/job_runs.go
- pkg/api/job_runs_test.go
- pkg/apis/api/types.go
- pkg/db/models/prow.go
- pkg/prowloader/gcs/gcs_jobrun.go
- pkg/prowloader/prow.go
- pkg/prowloader/prow_test.go
- pkg/sippyserver/dbloader.go
- pkg/sippyserver/server.go
- pkg/testidentification/kube_variants.go
- pkg/testidentification/no_variants.go
- pkg/testidentification/ocp_variants.go
- pkg/testidentification/ocp_variants_test.go
- pkg/testidentification/variants.go
Addresses [TRT-838](https://issues.redhat.com/browse/TRT-838) as well as [TRT-800](https://issues.redhat.com/browse/TRT-800)
- Missing variant data like presubmit / agnostic tests
- Missing data all together - Sets Risk Level MissingData
- Missing tests - Sets Risk Level IncompleteTests
- Missing variant match on TestRuns, secondary pass looking for the first super set of variants
- Accepts job variant data on incoming test-failures-summary data for risk analysis
- Performs secondary pass to match test run when we don't have complete variant data for a match
- Looks for new job-variants.json on import to fill in variant data from cluster info when available
> TRT-800: Missing variant data during Risk analysis

- pkg/testidentification/ocp_variants.go
- pkg/testidentification/ocp_variants_test.go
Only use the cluster variant value if the jobNameVariant is missing or there is no conflict.
Short term fix will need a longer term plan.
> TRT-800: Defer to jobNameVariant if there is a conflict

- main.go
- pkg/api/jobs.go
- pkg/api/test_analysis.go
- pkg/db/query/test_queries.go
- pkg/sippyserver/server.go
- sippy-ng/src/tests/TestAnalysis.js
- sippy-ng/src/tests/TestPassRateCharts.js
- sippy-ng/src/tests/TestStackedChart.js
[TRT-808](https://issues.redhat.com//browse/TRT-808)
Currently the test analysis page generates the by-variant and by-job views by hitting one API that queries the DB in sequence (one after the other). 
This change:
- Splits the API so there's variant and job-based api endpoints meaning the UI can load them in parallel.  
- Optimizes some of the queries to be a little more efficient. This does seem to improve the responsiveness of the test analysis page a bit.
- Adds an overall stacked chart so we can visualize flakes better (this loads fast)
> Test analysis refactor

- pkg/db/matviews.go
- pkg/db/query/test_queries.go
- sippy-ng/src/components/Sidebar.js
- sippy-ng/src/constants.js
- sippy-ng/src/releases/PayloadMiniCalendar.js
- sippy-ng/src/releases/PayloadStreamOverview.js
- sippy-ng/src/releases/ReleaseOverview.js
- sippy-ng/src/tests/TestAnalysis.js
- sippy-ng/src/tests/TestStackedChart.js
- sippy-ng/src/tests/Tests.js
[TRT-837](https://issues.redhat.com//browse/TRT-837)
This moves the filtering of aggregation from test results from being hardcoded to being done in the UI.  By moving it to the UI, the filter can be removed and you can view tests for only aggregation. We need to do this because there are tests that *only* appear in aggregation (e.g. the new disruption tests).
Aggregated will be filtered out by default, but users wanting to see the aggregated results can add a filter for `variants contains aggregated`.
The reason for needing a default exclusion is because the jobs that make up an aggregated run are already tracked in Sippy. We are injecting unwanted hysteresis that will cause changes to pass rates to lag behind if you do not filter it out. The effect is probably small. 
Here's an example: …
> Change how aggregated variants are filtered out

- pkg/api/releases_test.go
- pkg/releasesync/releasesync.go
[TRT-904](https://issues.redhat.com//browse/TRT-904)
The OS changed from "Red Hat Enterprise Linux CoreOS" to "CentOS Stream CoreOS". Sippy is now reporting `unable to parse OpenShift version from OS version` because the OS version isn't populated.
> Handle change in OS component name

- pkg/releasesync/releasesync.go
[TRT-903](https://issues.redhat.com//browse/TRT-903)
A phase change is detected when the phase, as indicated by the release-controller, is different from that which was recorded in the sippyDB; this happens when a payload is force accepted or rejected.
Existing code updates the phase in the sippyDB to match what is in the release-controller.
This PR sets the "Forced" flag to true so that the sippy UI will show the payload as forced accepted or force rejected.
> Update the 'Forced' flag when release tag's phase change is detected

- sippy-ng/src/build_clusters/BuildClusterDetails.js
[TRT-955](https://issues.redhat.com//browse/TRT-955)
For the build cluster, the query is for [periodic jobs](https://github.com/openshift/sippy/blob/d6f82be99bbb7c170bf580a80febf6cedbc36644/pkg/db/query/build_clusters.go#L66) only.  This makes the query for the JobsTable match.
> Make Jobs table match query for build clusters

- pkg/api/health.go
- pkg/api/install.go
- pkg/api/upgrade.go
- pkg/sippyserver/metrics/installupgradesuccess.go
- pkg/testidentification/test_identification.go
- sippy-ng/src/helpers.js
- sippy-ng/src/releases/Install.js
- sippy-ng/src/tests/TestAnalysis.js
- sippy-ng/src/tests/TestByVariantTable.js
[TRT-565](https://issues.redhat.com//browse/TRT-565)
We were not correctly excluding upgrade-minor and aggregated from install statistics in many places.
- upgrade-minor installs the previous release and should not be counted.
- The reason for excluding aggregated is a little more subtle, but it injects unwanted hysteresis that will cause changes to pass rates to lag behind if we do not filter it out.
Here's an example:
The follow test runs 10x and passes 7.
[sig-pizza] Pizza should be delivered within 30 minutes
It has a pass rate of 70%, in line with historical results.
If it is aggregated, we have an 11th entry in Sippy of a pass. Sippy actually thinks the test passed 8 times out of 11 -- a pass rate of 72.7%.
> Fix installation logic determination

- sippy-ng/src/releases/ReleasePayloadTable.js
[TRT-985](https://issues.redhat.com//browse/TRT-985)
Fix incorrect url for checking RHCOS versions in payload stream listing.
> Link to the previous_os_url when showing payloads

- scripts/sql/test-duration-stats.sql
For [TRT-1003](https://issues.redhat.com//browse/TRT-1003)
Example output:
```
$ sippy_openshift=> select * from pg_temp.calculate_percentiles('Cluster upgrade.[sig-cluster-lifecycle] Cluster completes upgrade');
platform   | cni |    upgrade    |  percentile_50   |  percentile_99   |  percentile_100
-------------+-----+---------------+------------------+------------------+------------------
aws         | ovn | upgrade-minor | 75.5037481587333 | 91.1699486471667 | 148.836387897583
aws         | sdn | upgrade-minor | 66.3346064770833 | 130.001002921867 | 133.506777134567
aws         | ovn | upgrade-micro |    46.6700414857 | 77.6712774810667 | 77.6712774810667
aws         | sdn | upgrade-micro |    40.8344902655 | 69.3367003545333 |    70.1701065424
azure       | ovn | upgrade-minor | …
```
> Add a sql script demonstrating how to calculate test duration percentiles

- pkg/prowloader/testoutputmetadata.go
- pkg/prowloader/testoutputmetadata_test.go
[TRT-1015](https://issues.redhat.com//browse/TRT-1015)
This allows us to process metadata for all pathological tests.  There used to be only two of them; there are now 126:
```
sippy_openshift=> select count(*) from tests where name  LIKE '%pathological%';
count 
-------
126
```
Using this regex will allow us to get the 124 new ones.
> Use regex for metadata extractor function for pathological tests

- sippy-ng/src/component_readiness/CompCapTestRow.js
- sippy-ng/src/component_readiness/CompReadyCapCell.js
- sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
- sippy-ng/src/component_readiness/CompReadyTestCell.js
- sippy-ng/src/component_readiness/CompReadyTestReport.js
- sippy-ng/src/component_readiness/CompReadyUtils.js
- sippy-ng/src/component_readiness/CompTestRow.js
- sippy-ng/src/component_readiness/ComponentReadiness.js
[TRT-1068](https://issues.redhat.com//browse/TRT-1068)
This is dependent on https://github.com/openshift/sippy/pull/1003
I tested this against PR1003 and traversed all 5 pages and got no errors from the API.
> Ignore disruption by default an match api parameter names in ComponentReadiness UI

- sippy-ng/src/index.js
Not a complete fix for the back button, but partially fixes it. One issue is successive calls to set query params each create a history entry. This turns on batching which makes consecutive calls only affect the URL once.  Not all our calls are consecutive so we'd have to fix that to get the back button working completely I think.
> Enable batching for query params (back button)

- sippy-ng/src/component_readiness/AdvancedOptions.js
- sippy-ng/src/component_readiness/CompReadyProgress.js
- sippy-ng/src/component_readiness/CompReadyTestDetailRow.js
- sippy-ng/src/component_readiness/CompReadyTestReport.js
- sippy-ng/src/component_readiness/ComponentReadiness.css
- sippy-ng/src/component_readiness/ComponentReadiness.js
* Updated Advanced Option parameters per discussions
* Use "Loading ..." instead of asterisks to match typical look/feel of loading pages
* Display rows of 20 ProwJobRun links to allow fitting of many
* Sort rows of component names on first page (without regard to case)
> Add ComponentReadiness UI updates from feedback

- pkg/apis/api/types.go
- pkg/releasesync/release_dates.go
- pkg/sippyserver/server.go
- sippy-ng/src/component_readiness/CompReadyMainInputs.js
- sippy-ng/src/component_readiness/ReleaseSelector.js
[TRT-1065](https://issues.redhat.com//browse/TRT-1065)
- Adds GA dates to Sippy's release API
- Uses those dates by default for GA'd releases in component readiness
- Add quick links for 2 weeks, 4 weeks, and GA - 4 weeks
> Use GA dates in component readiness

- sippy-ng/src/jobs/JobStackedChart.js
- sippy-ng/src/tests/TestStackedChart.js
Sets constraints on the stacked chart axes. This makes it a little less panic inducing when a test drops from 99.9% to 99.6% and the chart axis goes from 99.5 to 100.
- Job stacked chart should always start at 0
- Test stacked charts are relative, but will never be less than 80 (so no drastic-looking drops)
> Adjust stacked chart axes

- sippy-ng/src/component_readiness/CompReadyTestDetailRow.js
- sippy-ng/src/component_readiness/ComponentReadiness.css
It's a little easier for me to read if all the cell data is aligned to the top.
Before:
After:
> Align test detail rows on top

- sippy-ng/src/component_readiness/CompReadyCell.js
- sippy-ng/src/component_readiness/CompReadyRow.js
- sippy-ng/src/component_readiness/CompReadyUtils.js
- sippy-ng/src/component_readiness/CompSeverityIcon.js
- sippy-ng/src/component_readiness/ComponentReadiness.js
[TRT-1062](https://issues.redhat.com//browse/TRT-1062)
More page 1 features to allow users to focus on what they care about.
I focus only on the components/rows to avoid too many filters.  If we really want to filter on red columns, we can do that separately.
> Allow selecting only red components

- pkg/api/component_report.go
- pkg/apis/api/types.go
- sippy-ng/src/component_readiness/CompCapTestRow.js
- sippy-ng/src/component_readiness/CompReadyEnvCapability.js
- sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
- sippy-ng/src/component_readiness/CompTestRow.js
If you look at this page:
https://sippy.dptools.openshift.org/sippy-ng/component_readiness/capability?baseEndTime=2023-05-16%2023%3A59%3A59&baseRelease=4.13&baseStartTime=2023-04-18%2000%3A00%3A00&capability=Other&component=Networking%20%2F%20cluster-network-operator&confidence=95&groupBy=cloud%2Carch%2Cnetwork&ignoreDisruption=true&ignoreMissing=false&minFail=3&pity=5&sampleEndTime=2023-06-05%2023%3A59%3A59&sampleRelease=4.14&sampleStartTime=2023-05-08%2000%3A00%3A00
You'll notice a lot of duplicate tests. It's because we consider same named tests from different suites as different tests (it's possible two suites could define a generic test like "TestClusterCreate" and we want to make sure we're not combining results from different suites).
This adds the suite name to the API, and shows …
> Show test suite and name in component readiness

- sippy-ng/src/pull_requests/PullRequestsTable.js
This allows searching by number (which is sometimes easier to remember and quicker to key in for a filter).
> All searching Pull Requests by PR number

- pkg/testidentification/ocp_never_stable.txt
- scripts/update-neverstable.sh
Locales impact sorting.  My local fedora uses en_US.utf8. UBI9 uses C.utf8 -- these produce different results.  Force C.utf8 for everybody.
> Use consistent locale in update-neverstable.sh

- sippy-ng/src/component_readiness/CompReadyTestReport.js
[TRT-1110](https://issues.redhat.com//browse/TRT-1110)
The `process.env.REACT_APP_API_URL` variable is empty in production mode so we have to account for this when creating a `URL` object as that requires a full URL.
> Add hostname if missing when creating URL object

- sippy-ng/src/helpers.js
JIRA's behavior has changed, and it's now eating URL's with curly braces in them. These should get encoded too.
> Encode curly brances as well

- sippy-ng/src/component_readiness/CompReadyTestReport.js
Release GA dates seem spread across about 5 months so I use 20 weeks as the window before GA and 1 week after GA.  This will allow us to translate more date ranges to human consumable verbiage like "x weeks before 4.y GA date".
Releases under development (not GA yet) are also handled.
[Example url](http://localhost:3002/sippy-ng/component_readiness/test_details?arch=amd64&baseEndTime=2023-05-16%2023%3A59%3A59&baseRelease=4.13&baseStartTime=2023-04-16%2000%3A00%3A00&capability=Other&component=Monitoring&confidence=95&environment=ovn%20no-upgrade%20amd64%20vsphere-upi%20standard&excludeArches=ppc64le%2Cs390x%2Carm64&excludeClouds=alibaba%2Covirt%2Copenstack&excludeVariants=single-node%2Ctechpreview&groupBy=cloud%2Carch%2Cnetwork&ignoreDisruption=true&ignoreMissing=false&minFail=3&network=ovn …
> Widen date window for more human readable date summaries

- pkg/testidentification/ocp_variants.go
Per the PPC team, regressions in the libvirt ppc jobs do not impact our release readiness.  Because of this, we don't want them to disruption the signal of other ppc or other libvirt jobs in our standard summarization or regression analysis.  The team can still inspect their results by checking a job filter in sippy, but the rest of the org will have a cleaner ship/no-ship analysis to watch and focus their efforts on.
> remove jobs without release impact from sippy main page

- pkg/api/jira.go
We need an initialized slice so we return `[]` not null. The calendar locks up on months without any incidents at the moment.
> Fix bug in the calendaring api

- pkg/api/component_report.go
[TRT-1139](https://issues.redhat.com//browse/TRT-1139)
Using the simpler fix for DISTINCT(file_path) doesn't seem to work for
all pages. We have the  unfortunate scenario where we're getting duplicated test results in many places, which is caused by both retried failures and a bug in openshift-tests that causes duplicates (https://issues.redhat.com/browse/OCPBUGS-16039).
> Dedupe junit table results in component readiness

- sippy-ng/src/component_readiness/CompReadyTestReport.js
[TRT-1064](https://issues.redhat.com//browse/TRT-1064)
Do a sort before rendering so those with significant == True bubble to the top.
> Show statistically significant test summary rows first

- pkg/apis/api/types.go
- pkg/sippyserver/pr_commenting_processor.go
Updated commenting to include more details on the failed test, risk reasons and open bugs.
Stacking the tests/reasons/bug to utilize vertical space over horizontal:
Job Failure Risk Analysis for sha: 79d237196d93eb92ed58c66497d8718259264226
| Job Name | Failure Risk |
|:---|:---|
|[pull-ci-openshift-origin-master-e2e-gcp-ovn-upgrade](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/28075/pull-ci-openshift-origin-master-e2e-gcp-ovn-upgrade/1682395379418533888)|<b>High</b><br>[sig-api-machinery] disruption/cache-oauth-api connection/reused should be available throughout the test:<br>This test has passed 99.88% of 827 runs on jobs ['periodic-ci-openshift-release-master-nightly-4.14-e2e-gcp-ovn-upgrade' 'periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn-upgrade'] in …
> TRT-1125: add test names, risk reasons and openbugs for pr comments

- pkg/sippyserver/pr_commenting_processor.go
Substitutes &#45; for - in links to prevent openshift-ci bot from updating the comment when it detects a valid JIRA reference.
Job Failure Risk Analysis for sha: e2cad6663c9186b487ec56daf33c671e69e09475
| Job Name | Failure Risk |
|:---|:---|
|[pull-ci-openshift-origin-master-e2e-openstack-ovn](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/28120/pull-ci-openshift-origin-master-e2e-openstack-ovn/1686778922848489472)|**High**<br>28 tests failed in this run: High|
|[pull-ci-openshift-origin-master-e2e-gcp-ovn](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/28120/pull-ci-openshift-origin-master-e2e-gcp-ovn/1686778918683545600)|**Medium**<br>*[sig-instrumentation] Prometheus [apigroup:image.openshift.io] when installed on the cluster should report …
> TRT-1125: Add escape for - in links

- pkg/db/models/releases.go
- scripts/rejected-payloads.md
- scripts/rejected-payloads.py
- scripts/requirements.txt
- sippy-ng/src/releases/ReleasePayloadTable.js
[TRT-1186](https://issues.redhat.com//browse/TRT-1186)
TODO:
sample output for multiple reasons:
```
$ ./rejected-payloads.py -d $DSN --days 4 list -s nightly -r 4.12 --all
index     release tag                                       phase               reject reasons      note
1         4.12.0-0.nightly-2023-08-08-180643                Rejected            TEST_FLAKE          test flakes are flaky
2         4.12.0-0.nightly-2023-08-08-180641                Rejected            TEST_FLAKE          this is multiple lines
PRODUCT_REGRESSION  
TEST_REGRESSION     
CLOUD_QUOTA         
```
> Allow multiple reasons for a payload reject in script and UI

- pkg/api/releases.go
- pkg/db/matviews.go
- pkg/db/models/releases.go
- pkg/db/query/payload_queries.go
- pkg/sippyserver/server.go
- sippy-ng/package-lock.json
- sippy-ng/src/releases/PayloadTestFailures.css
- sippy-ng/src/releases/PayloadTestFailures.js
- sippy-ng/src/releases/ReleasePayloadDetails.js
New Tab on the page to view a particular payload, that lists all tests that failed across all jobs in the payload, how many times, and which jobs it failed in. 
Helpful just to quickly show the tests that may be failing in multiple
jobs.
> Add a new view for each test that failed in all jobs on a payload

- pkg/jiraloader/jiraloader.go
[TRT-1194](https://issues.redhat.com//browse/TRT-1194)
If we removed the incident label from a jira, we want to make sure we update the database row still. So, we keep track of jira incidents we didn't see yet and then query jira to figure out what happened. If the jira got the trt-incident label removed, we found out when that happened and set it as the incident resolution date.
I tested this change by:
- Syncing incidents to a local DB
- Removing the incident label from [TRT-1202](https://issues.redhat.com//browse/TRT-1202)
- Resyncing, and confirm the resolution date was set to when I removed the label
- Added label back, resynced, and confirmed issue was marked unresolved again
> Ensure stale issues get updated for incidents

- sippy-ng/src/component_readiness/ComponentReadiness.js
[TRT-1230](https://issues.redhat.com//browse/TRT-1230)
This will focus the Component Readiness defaults (by excluding several items) so we can reduce the query search space and possibly make better use of the cache.
* Release to evaluate = 4.14 (from/to relative to now)
* Historical release = 4.13 (from/to set to 4 weeks before GA)
> Narrow scope of Component Readiness defaults

- pkg/api/jobrunintervals/job_run_intervals.go
- pkg/sippyserver/server.go
- sippy-ng/src/App.js
- sippy-ng/src/prow_job_runs/ProwJobRun.js
[TRT-1215](https://issues.redhat.com//browse/TRT-1215)
Today, when you click on the Intervals button on a prow job under the Debug section, only the jobID is passed.  From the jobID, we can get the GCS bucket url via the sippy database, but only after that prow job is added to the sippyDB (which happens hourly).
This change allows us to make use of a prow job name (if passed in as a parameter).  This obviates the need to wait for the sippyDB to be populated with the prow job; as such, we can get the intervals immediately.
https://github.com/openshift/release/pull/43064 will make use of this functionality.
Test:
> Allow passing in a jobName for sippy intervals

- pkg/db/models/pr_commenting.go
- pkg/github/commenter/ghcommenter.go
- pkg/sippyserver/pr_commenting_processor.go
Gorm appears to have a bug with detecting smallint/tinyint columns, it
thinks they always need their schema updated, whereas using an
int/bigint does not hit this.
Combined with a rollout of the deployment during our long running backup
job, this deadlocks the db somehow, but we need to remember this could
happen on any schema change if it ran into our backup in the middle of
the night.
[TRT-1228](https://issues.redhat.com//browse/TRT-1228)
> Avoid gorm bug with smallint postgres column

- pkg/api/component_report.go
[TRT-1083](https://issues.redhat.com//browse/TRT-1083)
Courtesy of David:
```
This sub-query:
SELECT  *,
ROW_NUMBER() OVER(PARTITION BY file_path, test_name, testsuite ORDER BY
CASE
WHEN flake_count > 0 THEN 0
WHEN success_val > 0 THEN 1
ELSE 2
END) AS row_num
FROM
openshift-gce-devel.ci_analysis_us.junit
WHERE TIMESTAMP(modified_time) >= "2023-09-01"
AND TIMESTAMP(modified_time) < "2023-09-27"
explodes to a full table scan due to the casting of your partitioned
field modified_time. Cast the argument instead and you'll drop from from
776GB per query to 85 GB per query.
```
> Cast argument instead of partitioned field

- sippy-ng/src/component_readiness/CompCapRow.js
- sippy-ng/src/component_readiness/CompReadyCapCell.js
- sippy-ng/src/component_readiness/CompReadyCapsCell.js
- sippy-ng/src/component_readiness/CompReadyCell.js
- sippy-ng/src/component_readiness/CompReadyRow.js
- sippy-ng/src/component_readiness/CompReadyTestCell.js
- sippy-ng/src/component_readiness/CompTestRow.js
[TRT-1063](https://issues.redhat.com//browse/TRT-1063)
This gives us what a proper "Back" button would give us (i.e., the ability to refer back to where we came from by going to the previous tab).
We are choosing to implement this way because getting the "Back" button to work properly has been problematic.
Once merged, the Component Readiness UI behavior will be such that for every link that is clicked, a new browser tab is opened.
> For Component Readiness, open new tab by default

- pkg/sippyserver/server.go
We're having problems with disk iops suddenly as of Sep 12 and not
totally sure why. To help calm it down we will reduce our matview
concurrency for refreshes to see if that helps.
> Reduce materialized views concurrency from 3 to 2

- sippy-ng/src/component_readiness/ComponentReadiness.css
[TRT-1250](https://issues.redhat.com//browse/TRT-1250)
This locks the left column and the top row to help the user more easily see what environment or component/capability/etc a square refers to.
> Lock the leftmost column and column headers in Component Readiness UI

- config/e2e-openshift.yaml
- e2e-scripts/sippy-e2e-sippy-e2e-setup-commands.sh
- main.go
- pkg/api/health.go
- pkg/prowloader/bigqueryjobs.go
- pkg/prowloader/github/github.go
- pkg/prowloader/prow.go
- pkg/prowloader/testconversion/testconversion.go
- test/e2e/util/e2erequest.go
[TRT-1190](https://issues.redhat.com//browse/TRT-1190)
We're spending a lot of time processing gcs buckets and importing jobs, such that when combined with the matview refreshes we're regularly approaching or exceeding the 60 minute window. This changes the gcs importer code to import up to 10 jobs in parallel.  Gorm is (mostly) thread safe, and I think I've protected all the places in our code that isn't.
> Parallelize job gcs bucket processing

- pkg/sippyserver/pr_commenting_processor.go
- pkg/sippyserver/pr_commenting_processor_test.go
Due to the flakiness of tests we want to see at least 2 consecutive failures for tests that we report risk analysis on vi PR commenting.
- If < 2 job runs skip commenting
- If 2 or more check to see that the same test failed in the prior run as well
- If incomplete tests or missing data only report if back to back runs show the issue
> trt-1167: match consecutive failures for risk analysis reporting

- pkg/sippyserver/pr_commenting_processor.go
- pkg/sippyserver/pr_commenting_processor_test.go
Observed after recent update:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1459e6e]
goroutine 109 [running]:
github.com/openshift/sippy/pkg/sippyserver.buildRiskSummary(0xc0012920c0?, 0x0)
/go/src/sippy/pkg/sippyserver/pr_commenting_processor.go:868 +0x1ae`
Created test case to reproduce and added nil check
> trt-1167: add check for valid priorRiskAnalysis

- pkg/testidentification/ocp_variants.go
- pkg/testidentification/ocp_variants_test.go
Currently missing cases like:
periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-upi
periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-upi-serial
> trt-1231: update vsphere-upi regex to handle missed matches

- pkg/sippyserver/server.go
When you goto a [presubmit job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/28327/pull-ci-openshift-origin-release-4.12-e2e-aws-ovn-single-node-upgrade/1712788098988904448) and try to click the Intervals link under Debug Tools, it shows as blank.
The GCS path for presubmits looks like this:
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/28327/pull-ci-openshift-origin-release-4.12-e2e-aws-ovn-single-node-upgrade/1712788098988904448/
```
The repo is not in that path and so the code to fetch the intervals from the bucket will never work.
This fixes that path so it should now work.
Two test cases:
* Intervals for Presubmit job: http://localhost:3000/sippy-ng/job_runs/1712198215459147776/pull-ci-openshift-origin-master-e2e-aws-ovn-s …
> Fix GCS path for intervals for presubmits

- pkg/sippyserver/server.go
Reverts #1248 ; tracked by TRT-9999
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
This PR accounts for only origin PRs and not other repos and breaks the Intevals link for non-origin Presubmit jobs
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
Click on Intervals link in Debug Tools for both origin and non-origin Presubmit jobs
```
CC: @DennisPeriquet
<div align="right">
PR created by <a …
> Revert #1248 "Fix GCS path for intervals for presubmits"

- pkg/sippyserver/server.go
Does essentially what https://github.com/openshift/sippy/pull/1248/files did -- but only for Presubmit jobs in origin.
Also accommodates for non-origin Presubmit job.
> Use different GCS bucket path for origin Presubmit jobs

- sippy-ng/src/prow_job_runs/ProwJobRun.js
- sippy-ng/src/pull_requests/PullRequestsTable.js
- sippy-ng/src/releases/PayloadStreamOverview.js
- sippy-ng/src/releases/PayloadStreamTestFailures.js
- sippy-ng/src/releases/PayloadStreamsTable.js
- sippy-ng/src/releases/PayloadTestFailures.js
- sippy-ng/src/releases/ReleasePayloadAcceptance.js
- sippy-ng/src/releases/ReleasePayloadPullRequests.js
- sippy-ng/src/releases/ReleasePayloadTable.js
- sippy-ng/src/tests/TestDurationChart.js
- sippy-ng/src/tests/TestTable.js
[TRT-1294](https://issues.redhat.com//browse/TRT-1294)
Only the change in `sippy-ng/src/tests/TestDurationChart.js` fixes the problem mentioned in the Jira.  But, the same problem exists in the other 5 files.
The `import { Error } from '@material-ui/icons'` line overlaps with the `Error` built-in which we use for `throw/catch` so we can propagate error strings to users during error conditions.  This overlap causes React to render the `bundle.js` in a way that we didn't actually intend and hence causes mysterious errors like `TypeError: cx is not a constructor` when the code handles an error condition.  Removal of that import allows React to render the bundle.js as we intended.
I was able to reproduce this by returning a 500 status in a local version of sippy.
TODO:
> Remove overlapping Error material-ui import

- pkg/db/suites.go
- scripts/updatesuites.go
I'll need to run updatesuites.go again, but it's only a small number of tests.  I removed the stuff from updatesuites.go that was invasive (removing indexes) so this should be able to just be run safely with Sippy online.
> Fix typo in Symptom Detection suite

- sippy-ng/src/App.js
- sippy-ng/src/component_readiness/CompCapRow.js
- sippy-ng/src/component_readiness/CompReadyCapCell.js
- sippy-ng/src/component_readiness/CompReadyCapsCell.js
- sippy-ng/src/component_readiness/CompReadyCell.js
- sippy-ng/src/component_readiness/CompReadyEnvCapabilities.js
- sippy-ng/src/component_readiness/CompReadyEnvCapability.js
- sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
- sippy-ng/src/component_readiness/CompReadyProgress.js
- sippy-ng/src/component_readiness/CompReadyRow.js
- sippy-ng/src/component_readiness/CompReadyTestCell.js
- sippy-ng/src/component_readiness/CompReadyTestReport.js
- sippy-ng/src/component_readiness/CompReadyUtils.js
- sippy-ng/src/component_readiness/CompTestRow.js
- sippy-ng/src/component_readiness/ComponentReadiness.js
[TRT-1278](https://issues.redhat.com//browse/TRT-1278)
Fixes the back button, and removes the requirement to press "Generate report" on the first page load.
There were 2 problems with the back button:
- When a component links to itself, React doesn't automatically unmount
and remount the component so old state stays around, this is why in
places there were extra set state calls to update the app state
resulting in split calls to state setting, meaning we ended up with
different history entries for each state call.  The `key` param in
App.js on ComponentReadiness fixes this and makes it update whenever the
URL changes, thus re-reading the state from the URL parameters. This
avoids the need for the extra state setting calls.
- In a few places, we reply on URLSearchParams, a browser built-in …
> Fix back button in component readiness

- sippy-ng/src/component_readiness/ComponentReadiness.js
> Fix the sample selector dates to always pick the last week

- sippy-ng/src/releases/ReleasePayloadJobRuns.js
- sippy-ng/src/repositories/RepositoriesTable.js
- sippy-ng/src/tests/TestOutputs.js
Added this to `eslintrc.js` and found 3 more occurrences of `Error` shadow:
```js
'no-shadow': [
'error',
{
builtinGlobals: true,
},
],
```
Adding that option for now is a bit too intrusive as seen in [PR1273](https://github.com/openshift/sippy/pull/1273) so we skip it for now.
> Remove uses of Error when overlapping with "new Error()"

- pkg/api/component_report.go
- sippy-ng/src/component_readiness/ComponentReadiness.js
Currently, when looking at a component readiness report, it can be difficult to find which square was red.  For example [on this page](https://sippy.dptools.openshift.org/sippy-ng/component_readiness/env_capability?arch=amd64&arch=amd64&baseEndTime=2023-10-30%2023%3A59%3A59&baseRelease=4.14&baseStartTime=2023-10-02%2000%3A00%3A00&capability=Other&component=kube-apiserver&confidence=95&environment=ovn%20amd64%20metal-ipi&environment=ovn%20amd64%20metal-ipi&excludeArches=arm64%2Cheterogeneous%2Cppc64le%2Cs390x&excludeClouds=openstack%2Calibaba%2Cibmcloud%2Clibvirt%2Covirt%2Cunknown&excludeVariants=hypershift%2Cosd%2Cmicroshift%2Ctechpreview%2Csingle-node%2Cassisted%2Ccompact&groupBy=cloud%2Carch%2Cnetwork&ignoreDisruption=true&ignoreMissing=false&minFail=3&network=ovn&network=ovn&pity=5&plat …
> Component readiness should prioritize showing regressions first

- main.go
- pkg/api/component_report.go
- pkg/api/component_report_test.go
- pkg/bigquery/client.go
- pkg/sippyserver/metrics/metrics.go
- pkg/sippyserver/server.go
[TRT-1321](https://issues.redhat.com//browse/TRT-1321)
- Moves the caching layer for component readiness into the data layer, so it works for the API and the metrics gathering
- Adds metrics for component readiness, reports last GA vs dev release
Example metrics:
```promql
sippy_component_readiness{arch="amd64",component="Cloud Compute / Other Provider",network="sdn",platform="azure"} -2
sippy_component_readiness{arch="amd64",component="Cloud Compute / Other Provider",network="sdn",platform="gcp"} -3
sippy_component_readiness{arch="amd64",component="Cloud Compute / Other Provider",network="sdn",platform="metal-ipi"} -1
sippy_component_readiness{arch="amd64",component="Cloud Compute / Other Provider",network="sdn",platform="vsphere"} 0
```
Alerts PR: …
> Enable metrics for component readiness

- pkg/sippyserver/metrics/metrics.go
If we don't have a cache, then we don't want component readiness metrics, because you'll end up hitting bigquery every 5 minutes ($$$).
> Don't generate component readiness metrics until we have a cache

- Dockerfile.buildroot
- hack/go-lint.sh
- pkg/sippyserver/pr_commenting_processor.go
- sippy-ng/package-lock.json
- sippy-ng/package.json
- We don't actually use axios anywhere, and there's now a CVE in it, which is preventing builds https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
- Once we get past that, golangci-lint is OOMKilled because ubi9 updated their golang version... update golangci-lint to 1.52.1, this should prevent the oom (golangci-lint and golang versions have to be compatible)
> Fix sippy builds (remove axios, fix OOMKilled for golangci-lint)

- sippy-ng/src/datagrid/GridToolbarFilterItem.js
Bug from the v5 upgrade. Job analysis page date filters aren't working, it needed to be wrapped with the LocalizationProvider like I did for component readiness.
> Fix date picker for filters

- pkg/api/disruption_report.go
- pkg/apis/api/types.go
- pkg/sippyserver/metrics/metrics.go
Query new views in BigQuery which contain the complex logic, whatever is
in those views, we publish a metric for. One of them will need to be
updated as part of the GA date tasks.
Metrics published for the P50/75/95 delta now compared to both 30 days
prior to previous GA, and two weeks prior to two weeks ago.
We'll alert on these to notify ourselves of regressions in either.
> TRT-1357: Publish disruption delta metrics

- pkg/api/component_report.go
- pkg/api/utils.go
Easy to introduce bug, this should help detect it. It triggered on the initial version of https://github.com/openshift/sippy/pull/1330/files with:
```
panic: you cannot use struct api.disruptionReportGenerator with no exported fields as a cache key
```
> Be more defensive about empty cache keys

- sippy-ng/src/component_readiness/ComponentReadiness.js
[TRT-1371](https://issues.redhat.com//browse/TRT-1371)
Because search-as-you-type fields are hard to make URL parameters, this gives a button to copy the current searches as a link.  This lets you filter the grid as you like, and then copy the value so you can share it, bookmark it, etc.
Link with fields set: http://localhost:3000/sippy-ng/component_readiness/main?searchComponent=Cluster+Version+Operator%7CCloud+Credential&searchColumn=gcp&redOnly=1
> Make searches linkable

- sippy-ng/src/App.js
It's generally accepted that JS console.log messages shouldn't be visible in production [1], this turns console.log to noops when we're running in prod mode so we don't have to remove debugging logs which might be useful later in development.
[1] https://www.google.com/search?q=disable+js+console.log+in+production
> Disable console.log in production

- pkg/apis/api/types.go
- pkg/sippyserver/metrics/metrics.go
This will allow us to join on the disruption metric and the relevance
metric to only alert on nurps we feel are relevant, as defined by the
view we're querying.
promql I tested with this looks like:
sippy_disruption_vs_prev_ga{delta="P50",release="4.15"} >= 1 and ignoring(delta) sippy_disruption_vs_prev_ga_relevance >= 2
It is returning the same as my sql queries so I believe the join is
working properly.
> Publish disruption relevance metrics

- sippy-ng/src/component_readiness/ComponentReadiness.js
Pair up defaultSampleRelease && defaultBaseRelease to make it easy to update
Remove logic to try to determine defaultBaseRelease as it doesn't consider GA dates
Future work can evaluate most recent GA date and set defaults based on it.
> trt-1382: set explicit defaultBaseRelease && defaultSampleRelease

- sippy-ng/src/component_readiness/CompReadyUtils.js
- sippy-ng/src/component_readiness/ComponentReadiness.js
- sippy-ng/src/component_readiness/RegressedTestsModal.js
When I added the copy/clear searches link buttons, it didn't look good and now doesn't fit well with the show regressed tests links. Refactor it to be an appbar.  I'm not entirely sure the light mode looks good, but it's still an improvement I think.
> Clean-up component readiness toolbar

- pkg/api/component_report.go
[TRT-1410](https://issues.redhat.com//browse/TRT-1410)
If a test is marked obsolete, don't show it in component readiness.
> Exclude obsolete tests from component readiness

- sippy-ng/src/releases/ReleasePayloadTable.js
Both UI lower components (GridToolbarFilterItem etc) and API handling (FilterOptions) are common code. To minimize impact, I am customizing time format in ReleasePayloadTable so that other components are not affected.
> TRT-1426: Adjust time filter from timestamp to ISO format for release tag query

- pkg/apis/api/interval.go
- sippy-ng/src/components/TimelineChart.js
- sippy-ng/src/prow_job_runs/ProwJobRun.js
[TRT-1216](https://issues.redhat.com//browse/TRT-1216)
In the openshift/origin repo, I did this:
```
$ cd e2e-chart
$ git diff -U5 f2c0dead2b0d92585b0d9bd2fa3b56685b531b6f master -- e2e-chart-template.html
```
I added the javascript diffs to `sippy-ng/src/prow_job_runs/ProwJobRun.js`.
I also added `Source`, `StructuredLocator`, and `StructuredMessage` structs and json equivalents from openshift/origin intervals implementation where they are used.
These 6 jobs were used for testing existing sections including the new ones for `cloud-metrics` and `apiserver-shutdown`:
http://localhost:3000/sippy-ng/job_runs/1743298455779938304/periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-sdn-upgrade/intervals
http://localhost:3000/sippy-ng/job_runs/1737738662319230976/periodic-ci-openshift-relea …
> TRT-1216: sync html and new EventInterval fields from origin

- pkg/api/component_report.go
The flattened junit CTE doesn't exclude skipped tests, so since the failure field isn't set we are considering it a success.
> TRT-1434: exclude skipped test cases

- sippy-ng/src/component_readiness/CompReadyMainInputs.js
In light mode, the background is too dark.
Old: 
New:
> Adjust release selector background color

- pkg/api/component_report.go
Reverts openshift/sippy#1432
This broke test details page
https://sippy.dptools.openshift.org/sippy-ng/component_readiness/test_details?arch=amd64&arch=amd64&baseEndTime=2023-10-31%2023%3A59%3A59&baseRelease=4.14&baseStartTime=2023-10-04%2000%3A00%3A00&capability=Other&component=Installer%20%2F%20openshift-installer&confidence=95&environment=ovn%20upgrade-micro%20amd64%20azure%20standard&excludeArches=arm64%2Cheterogeneous%2Cppc64le%2Cs390x&excludeClouds=openstack%2Cibmcloud%2Clibvirt%2Covirt%2Cunknown&excludeVariants=hypershift%2Cosd%2Cmicroshift%2Ctechpreview%2Csingle-node%2Cassisted%2Ccompact&groupBy=cloud%2Carch%2Cnetwork&ignoreDisruption=true&ignoreMissing=false&minFail=3&network=ovn&network=ovn&pity=5&platform=azure&platform=azure&sampleEndTime=2024-01-22%2023%3A59%3A59&sampleRelease …
> Revert "TRT-1351: Use capability to exclude disruption tests"

- sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
For some reason I set display: none on `xs` screens. Maybe came from the MUI example in the docs.
> TRT-1442: Fix CR toolbar buttons on mobile devices

- pkg/apis/api/interval.go
- sippy-ng/src/components/TimelineChart.js
- sippy-ng/src/prow_job_runs/ProwJobRun.js
This change takes the changes from [e2e-chart-template.html](https://github.com/openshift/origin/blob/511023f1e1edc796973ce37fbeab5b25078b9abd/e2echart/e2e-chart-template.html) for charting the etcd-leaders and puts them in sippy's intervals chart.
Samples:
* [An older job](http://localhost:3000/sippy-ng/job_runs/1747942857647329280/periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-sdn-upgrade/intervals)
* Same job but with [smaller number of interval sections](http://localhost:3000/sippy-ng/job_runs/1747942857647329280/periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-sdn-upgrade/intervals?categories=operator_unavailable&categories=operator_progressing&categories=operator_degraded&categories=pod_logs&categories=node_state&categories=e2e_test_failed&categories=disruption&ca …
> TRT-1443: Add etcd-leaders section from openshift/origin repo to sippy intervals chart

- sippy-ng/src/components/Sidebar.js
Changes the Disruption Dashboard link to the CI Observability Dashboards folder
> trt-1439: observability dashboards link

- pkg/api/component_report.go
This unreverts the change that uses capabilities rather than string matching to filter disruption.  There was a typo in one of the SQL queries in the original PR, this fixes it.
> TRT-1351: Unrevert ignore disruption change and fix typo

- pkg/componentreadiness/resolvedissues/resolved_4.15_issues.go
We fixed the glibc problem that hit: periodic-ci-openshift-operator-framework-olm-release-X.X-periodics-e2e-gcp-olm
> OLM problems were resolved

- .gitignore
- pkg/db/loader/issues.go
- sippy-ng/src/helpers.js
- sippy-ng/src/jobs/JobTable.js
- sippy-ng/src/tests/TestTable.js
We have migrated `ci-search` over to the CR Cluster as it's new location to run.  It can be accessed via the following URL:
https://search.dptools.openshift.org/
We are currently planning on replacing the resources behind `search.ci.openshift.org` with a redirector pointing over to `search.dptools.openshift.org`.  To minimize any disruptions to TRT, this PR updates the various references from: `search.ci.openshift.org` directly to: `search.dptools.openshift.org`.
> Updating the location of `ci-search`

- cmd/sippy/migrate.go
Have cobra do the error handling instead of os.Exit.   The other commands use RunE, not sure why I didn't here.
> Migrate should use RunE instead of Run

- Makefile
Address #1537, after this fix, 
```console
jiazha-mac:sippy jiazha$ make
Makefile:5: *** "Missing npm in PATH".  Stop.
```
> display the right dep info when running make

- pkg/api/releases.go
- pkg/apis/api/types.go
- pkg/db/query/release_queries.go
- pkg/sippyserver/metrics/installupgradesuccess.go
- pkg/sippyserver/metrics/metrics.go
This PR adds a mechanism to silence an alert for older releases. It uses a map to map a metric to a count. The count defines how many recent releases for which the alert should be generated for that metric. The metric for releases older than the count will be label as silenced. 
Alert definitions will be updated once this merges. We will remove specific releases in the alert definition. Instead, the current release definitions are translated into counts in this PR for any specific metrics. 
As new releases are introduced, a rollover will happen so that older releases will fall off the sliding window and have their alerts silenced automatically.
EDIT:
The above implementation is changed to add just "releaseStatus" label to all the metrics with label "release". The value of releaseStatus is …
> TRT-1437: Automate alert update when new releases are introduced

- sippy-ng/src/bugs/BugButton.js
- sippy-ng/src/bugs/BugTable.js
- sippy-ng/src/component_readiness/CompReadyTestReport.js
- sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
- sippy-ng/src/tests/TestAnalysis.js
- Link directly to jira on component readiness and test detail pages
- Add `component-regression` label automatically when filing from CR
- Show last modified in the bug table
> Improve bug handling in component readiness

- sippy-ng/src/bugs/BugTable.js
This page errors
https://sippy.dptools.openshift.org/sippy-ng/tests/4.16/analysis?test=%5Bbz-networking%5D%5Binvariant%5D%20alert%2FOVNKubernetesResourceRetryFailure%20should%20not%20be%20at%20or%20above%20info&filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22%5Bbz-networking%5D%5Binvariant%5D%20alert%2FOVNKubernetesResourceRetryFailure%20should%20not%20be%20at%20or%20above%20info%22%7D%5D%2C%22linkOperator%22%3A%22and%22%7D
> Allow affects version to be nil

- cmd/sippy/load.go
- pkg/dataloader/bugloader/bugloader.go
- pkg/dataloader/bugloader/bugloader_test.go
Reverts openshift/sippy#1540
Affects versions and last changed are coming up blank in sippy production even though the table has the values.  They were populated when I tested locally.   Maybe I broke something on a late change to the PR.  Go back to the old bug loader while I sort this out.
> Revert "TRT-1484: Migrate bugloader to use bigquery data sources"

- pkg/apis/prow/prow.go
- pkg/dataloader/prowloader/bigqueryjobs.go
- pkg/dataloader/prowloader/prow.go
- pkg/sippyserver/pr_commenting_processor.go
Reverts openshift/sippy#1581
Sippy not syncing:
```
time="2024-04-03T19:28:20.509Z" level=error msg="loader \"prow\" returned error: googleapi: Error 400: Unrecognized name: prowjob_start_ts; Did you mean prowjob_start? at [16:20], invalidQuery"
971
Error: errors were encountered while loading database, see logs for details
```
> Revert "TRT-1588: Avoid NULL for prowjob_start_ts"

- DEVELOPMENT.md
- cmd/sippy/component_readiness.go
- cmd/sippy/main.go
- pkg/sippyserver/capabilities.go
- pkg/sippyserver/metrics/metrics.go
- pkg/sippyserver/server.go
- sippy-ng/src/App.js
- sippy-ng/src/components/Sidebar.js
Allow launching only just component readiness. The other UI parts of Sippy don't load.
Example if you just want CR:
```
./sippy component-readiness
--google-service-account-credential-file ~/google-service-account-credential-file.json
```
Bonus: /api now returns some very basic API docs.
TODO's:
> TRT-1462: Allow launching sippy without postgres

- pkg/api/component_report.go
- pkg/api/component_report_test.go
QE jobs contain a frequency element in the name (-f7, -f28, etc), we want to be able to normalize these job names.
> Normalize job names containing frequency

- OWNERS
Been a long time since it's made sense for me to be an approver here.  Sippy has been in good hands for quite a while.
> Remove bparees from approvers

- pkg/api/component_report.go
Looks like I broke caching for the queries by not including enough information about the queries in the cache key.  Found when trying to modify excluded arches but would impact just about everything.
Keeping a reference to the ComponentReportGenerator that is the basis for the query should get the keys right again.
> trt-1590: Keep ComponentReportGenerator context for query cache keys

- pkg/api/component_report.go
- pkg/api/component_report_test.go
- pkg/apis/api/types.go
- sippy-ng/src/component_readiness/CompReadyUtils.js
- sippy-ng/src/component_readiness/extreme-triaged.svg
- sippy-ng/src/component_readiness/regressed-triaged.svg
Shows 'triaged' icons for regressions that are cleared via triaged incidents.
Screenshot showing the watch count triaged regression under Unknown
Small amount of cleanup for sampleQueryGenerator and baseQueryGenerator since we pulled in ComponentReportGenerator for cache key making the separate storage of SampleRelease and BaseRelease redundant.
> Trt 1594 regression icons

- pkg/api/component_report.go
Smaller alternative to https://github.com/openshift/sippy/pull/1604
This is a small change to allow filtering by capability, I have the UI parts in another branch but it's probably not ready before I go on PTO, and I know David may want this if Sippy's regular test API isn't sufficient somehow.
Just append `&capability=Other` to the API call to filter the results, e.g.
http://localhost:8080/api/component_readiness?baseEndTime=2024-02-28T23:59:59Z&baseRelease=4.15&baseStartTime=2024-02-01T00:00:00Z&confidence=95&excludeArches=arm64,heterogeneous,ppc64le,s390x&excludeClouds=openstack,ibmcloud,libvirt,ovirt,unknown&excludeVariants=hypershift,osd,microshift,techpreview,single-node,assisted,compact&groupBy=cloud,arch,network&ignoreDisruption=true&ignoreMissing=false&minFail=3&pity=5&sampleEndTi …
> TRT-1582: Support capability filtering in the API

- pkg/api/jobrunintervals/job_run_intervals.go
- pkg/apis/api/interval.go
- sippy-ng/src/components/TimelineChart.js
- sippy-ng/src/prow_job_runs/ProwJobRun.js
In https://github.com/openshift/origin/pull/28727 we finally move the structured locator and message over to their final field names, and remove the legacy flat strings. 
This changes sippy to use the new format, but also has backward compatability to parse the old files and translate them on the fly. The UI only needs to know one format.
> TRT-1611: Use new structured interval fields with backward compat from the API

- .golangci.yml
- Dockerfile.buildroot
- hack/go-lint.sh
Choice # 1 - bump up to 1.54.2 and remove depguard
Doesn't look like we have configuration for it so it would be blacklist with not blacklisting.
Configs have changes and we now have failures.  Will work on alternate config changes allowing all / specific failure list depending on the size.
Latest golangci-lint version appears to be 1.57.2.  There are a couple more issues flagged by gocritic that we could work through now if we want.
> NO-JIRA: update linter

- pkg/sippyserver/server.go
Attempts to fix error for [Issues](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.16/analysis?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-release-master-nightly-4.16-metal-ovn-single-node-recert-cluster-rename%22%7D%5D%7D) not loading on Job Analysis page
```
time="2024-05-02T11:18:12.51Z" level=error msg="error querying test bugs from db" error="record not found"
time="2024-05-02T11:18:12.51Z" level=info msg="responded to request" elapsed=25.86793ms method=GET uri="/api/tests/bugs?test=undefined"
```
> trt-1604: handled undefined tests bugs query

- .golangci.yml
- Dockerfile.buildroot
- hack/go-lint.sh
- pkg/api/component_report.go
- pkg/api/health.go
- pkg/api/install.go
- pkg/api/job_runs.go
- pkg/api/jobs.go
- pkg/api/tests.go
- pkg/dataloader/prowloader/bigqueryjobs.go
- pkg/dataloader/prowloader/github/github_test.go
- pkg/dataloader/prowloader/prow.go
- pkg/db/db.go
- pkg/db/query/job_queries.go
- pkg/sippyserver/parameters.go
- pkg/testidentification/ocp_variants.go
- pkg/variantregistry/ocp.go
Mostly gocritic ifelse -> switch changes as well as removing explicit check enablement for defaults.
```
level=warning msg="[linters_context] gocritic: no need to enable check \"argOrder\": it's already enabled"
level=warning msg="[linters_context] gocritic: no need to enable check \"badCond\": it's already enabled"
level=warning msg="[linters_context] gocritic: no need to enable check \"caseOrder\": it's already enabled"
level=warning msg="[linters_context] gocritic: no need to enable check \"codegenComment\": it's already enabled"
level=warning msg="[linters_context] gocritic: no need to enable check \"deprecatedComment\": it's already enabled"
level=warning msg="[linters_context] gocritic: no need to enable check \"dupArg\": it's already enabled"
level=warning msg="[linters_context] …
```
> NO-JIRA: update golangci-lint v1.57.2

- pkg/api/component_report.go
- pkg/apis/api/types.go
- pkg/sippyserver/server.go
New API "/api/jobs/variants".
Example output:
```
{
"variants": {
"Aggregation": [
"aggregated",
"none"
],
"Architecture": [
"amd64",
"arm64",
"heterogeneous",
"ppc64le",
"s390x"
],
"FeatureSet": [
"default",
"techpreview"
],
"FromRelease": [
"0.0",
"0.1",
"0.2",
"0.22",
"0.23",
"0.24",
"0.25",
"0.26",
"1.0",
"1.1",
"1.2",
"1.3",
"1.4",
"1.5",
"1.6",
"1.7",
"1.8",
"1.9",
"1.10",
"1.11",
"1.12",
"1.13",
"1.14",
"1.15",
"1.16",
"1.17",
"1.18",
"1.19",
"1.20",
"1.21",
"1.22",
"1.23",
"1.24",
"1.25",
"1.26",
"1.27",
"1.28",
"1.29",
"1.30",
"1.31",
"1.32",
"1.52",
"1.54",
"1.55",
"1.58",
"1.64",
"1.70",
"2.2",
"2.3",
"2.4",
"2.5",
"2.6",
"2.7",
"2.8",
"2.9",
"2.10",
"3.11",
"4.1",
"4.2",
"4.3",
"4.4",
"4.5",
"4.6",
"4.7",
"4.8",
"4.9",
"4.10",
"4.11",
"4.12",
"4.13",
"4.14",
"4.15",
"4.16", …
```
> TRT-1615: Create api to use the new variant registry

- hack/gen-resolved-issue.md
- hack/gen-resolved-issue.py
* Removes 'OutputType' from JSON output since JSON is the default and persisting it requires manual step to remove when writing to DB.
* Updates [gen-resolved-issue.md](https://github.com/neisw/sippy/blob/0231b877cdd42b4165390e838785dcdf256bb8ed/hack/gen-resolved-issue.md) to document the input argument options
* Adds --match-all-job-runs to drop job runs from the incident records that don't contain all of the  specified test ids
** Likely needs more work to not drop everything when a testid / variant doesn't have any common job runs which will currently drop all job runs.
Replaces https://github.com/openshift/sippy/pull/1666
> trt-1555: Support keeping only common job runs for all test ids

- sippy-ng/src/component_readiness/CompReadyEnvCapabilities.js
- sippy-ng/src/component_readiness/CompReadyEnvCapability.js
- sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
- sippy-ng/src/component_readiness/CompReadyPageTitle.js
- sippy-ng/src/component_readiness/CompReadyTestReport.js
- sippy-ng/src/component_readiness/ComponentReadiness.js
- sippy-ng/src/component_readiness/CopyPageURL.js
This will adds a link in the lower right page to page API URL. This will (hopefully) obviate the need to use the debugging tools to retrieve the link used for the triage workflow.
> TRT-1661: Add link to title pages to help triage

- hack/gen-resolved-issue.py
- pkg/api/component_report.go
- pkg/componentreadiness/resolvedissues/types.go
Clears triage regression status for Infrastructure issue types.
Lays groundwork to clear issues with resolved date.
Fixes bug in triage script when issue url is not provided.
->
> trt-1668: Clear triage status for Infrastructure

- pkg/api/component_report.go
- pkg/api/component_report_test.go
- pkg/apis/api/types.go
- pkg/componentreadiness/resolvedissues/types.go
- pkg/componentreadiness/tracker/tracker.go
- pkg/sippyserver/metrics/metrics.go
- sippy-ng/src/component_readiness/ComponentReadiness.css
- sippy-ng/src/component_readiness/RegressedTestsModal.js
- sippy-ng/src/index.css
- sippy-ng/src/pull_requests/PullRequestsTable.css
- sippy-ng/src/releases/PayloadTestFailures.css
Sippy's metrics loop which queries the default component readiness report already, now uses this data to maintain a new test_regressions table in bigquery tracking when a test first went regressed, and when it resolved. The opened date is now returned in a new sub-struct on the test summary for regressed/triaged tests, and displayed in the test modal.
Because params can change, the goal here is to specifically track when a test regressed *in the default report*. For simplicity now however, regardless of your parameters, we'll include that opened date in the response provided the test was still regressed in that report. In future, we may only include this value if you're using the "default" server side view.
The code attempts to re-use recent regressions, within the last two days, to limit …
> TRT-1667: Track component readiness test regression start/end dates

- pkg/api/component_report.go
Sample query uses modified time.  Triage job runs track start time.  Short term fix is to add a 6 hour buffer for triage job runs that are about to fall off but we still want to consider.
> trt-1668: Add triage start time buffer

- hack/gen-resolved-issue.md
- hack/gen-resolved-issue.py
- pkg/api/component_report.go
Adds support for --issue-resolution-date, when a resolution date is set and it is within the sample window the triage icon will be replaced with the NotSignificant icon.
The triage script has been updated to not automatically set a resolution date.  If not specified the incident will be left open and the triage icon will be shown.
> trt-1668: Add support for issue-resolution-date

- pkg/db/functions.go
We consider Verified, ON_QA, MODIFIED, and Closed to be terminal states from TRT's perspective.  Once a fix is merged we don't want to silence alerts anymore, or consider that bug in the open count.
> TRT-1649: Exclude bugs in resolved state from open count

- pkg/variantregistry/ocp.go
Compact jobs were among the few mismatching here, as in-cluster they report ha which was skewing our data. The remaining mismatches don't look particularly critical to address but we can still examine logs if someone wants to go hunting.
> Honor job name over cluster-data.json for Topology

- cmd/sippy/component_readiness.go
- cmd/sippy/serve.go
- pkg/componentreadiness/tracker/tracker.go
- pkg/sippyserver/metrics/metrics.go
This prevents conflicts where devs working on sippy are actually
modifying the regression tables, in the case of the recent variant
registry work, this is catastrophically wrong.
> Guard the regression table maint with an opt-in flag.

- pkg/sippyserver/server.go
Sippy in some cases can panic when the /api/releases API is called more than once before it's cached.  This is because the API response's GA dates is a global.  The API should make a copy of it before modifying it.
```
fatal error: concurrent map writes
goroutine 191 [running]:
github.com/openshift/sippy/pkg/sippyserver.(*Server).jsonReleasesReportFromDB(0x140001420e0, {0x102abbf38, 0x140006440e0}, 0x140004d78f8?)
/Users/stbenjam/go/src/github.com/openshift/sippy/pkg/sippyserver/server.go:939 +0x28c
net/http.HandlerFunc.ServeHTTP(0x140004d7938?, {0x102abbf38?, 0x140006440e0?}, 0x11f91d150?)
/opt/homebrew/Cellar/go/1.21.4/libexec/src/net/http/server.go:2136 +0x38
[...]
```
You can pretty reliably force the panic by doing something like this on a local Sippy instance *without* Redis: …
> Fix concurrent map write bug in Sippy

- pkg/api/component_report.go
- sippy-ng/package-lock.json
We repartitioned yesterday for cost savings reasons, and made the
modified_time column now required to query. As it happens we were
querying already without a partition filter.
This function looks like it's used to query the distinct values for
network / arch / upgrade / platform / other variants. Each query before
looks like around 33 GB, we're only selecting one column each time, but
with the size of the table it was still quite a bit.
I've changed to only those rows from the last 60 days, the queries are
now around 6GB each, but of course we only see values for jobs that have
run in the past two months. All of this is irrelevant in the new
variant registry code currently in a branch.
> Fix missing modified_time in query for distinct column values

- pkg/db/matviews.go
- pkg/db/models/prow.go
About a 70% reduction in matview cost according to `EXPLAIN`.  By filtering prow_job_run_tests before we join, we get a huge reduction. At the moment we're doing a join on 3-months of data, instead now it'll be 2 weeks.
> Restrict prow_job_run_tests to last 14 days too

- sippy-ng/src/prow_job_runs/ProwJobRun.js
Ignore disruption intervals without the display flag.
Small hack to work around problems moving towards a UI that only shows
intervals if the code generating them said they were meant for user
display, which is not presently in all releases we're using. As such,
overriding the display flag right now is very useful for 4.16, but this
includes some disruption intervals we should never be showing. I should
have separated them on Source, but again, hard to get that to all active
releases.
For now, have the UI never display those so the "override display flag"
works well on 4.16.
> ignore no display disruption intervals

- sippy-ng/src/components/MiniCard.js
- sippy-ng/src/helpers.js
- sippy-ng/src/tests/TestByVariantTable.css
- sippy-ng/src/tests/TestByVariantTable.js
Updated display to split up the variant name to make it easier to see for overview grid and test grid
/assign @stbenjam 
Ex:
> updated to handle new information in variant names

- hack/gen-resolved-issue.py
- hack/requirements.txt
- pkg/api/component_report.go
- pkg/apis/api/types.go
- pkg/componentreadiness/resolvedissues/types.go
- Convert existing triage key/value to new variants when read.  
- Use new variants for new triage records.
- Record job run CompletedTime when available
- Use CompletedTime over StartTime for triage job run window when available
> trt-1712: Update triage for new variants

- sippy-ng/src/App.js
- sippy-ng/src/releases/Install.js
- sippy-ng/src/releases/Upgrades.js
- sippy-ng/src/tests/TestByVariantTable.js
updated view tree so that main sets the max width of the container and the children fit inside, this should keep things from moving out of bounds when the side panel is opened 
added sticky header and columns with a bounded table width to make navigation a little easier
/assign @stbenjam 
Can you try this one locally first, I tried to test as much as I could with the web dev tools, but view tree changes like this have ways of surprising me.
Ex:
> upkeep: updated table grid view

- pkg/api/component_report.go
- pkg/api/component_report_test.go
- pkg/apis/api/types.go
- sippy-ng/src/component_readiness/CompReadyTestReport.js
- sippy-ng/src/component_readiness/RegressedTestsModal.js
- **Include pass rates in regressed tests API struct**
- **Show the change in pass rate in regressed tests modal**
- **Make regression certainty col sortable**
- **Return stats even for non-regressed tests in assessComponentStatus**
These changes are working towards tracking pass rates when we open/close regressions, but wanted to put up for review in isolation to make things easier.
> Include and display regressed test pass rates

- sippy-ng/src/component_readiness/RegressedTestsModal.js
Use valueGetter for variants formColumnName  call as noted in the [doc](https://mui.com/x/react-data-grid/filtering/customization/).
> trt-1740: use valueGetter for variants column

- pkg/api/component_report.go
In openshift-tests, we create two junits for the same test to indicate a flake, one success one failure. But depending on the order in which the two junits appear in the file, we get different entries to the junit BQ table. In one case the success count includes the flake while in the other it does not. This has caused math errors in some status calculation.
> TRT-1743: Remove flake from success count for test cases

- hack/gen-resolved-issue.py
Needed to set the newSampleEndTime to the end of the current day and use along with the diff to calculate the start.  Previously had an extra day in the range.
> NO-JIRA: fix relative sample start time

- sippy-ng/src/component_readiness/CompReadyMainInputs.js
- sippy-ng/src/component_readiness/CompReadyVars.js
This updates the side bar to allow filtering by owner and adds qe and as defaults so the QE instance correctly shows their jobs. This should have no effect on the engineering instance as there's no `qe` owned jobs in our tables.
> Update filtering to allow for owners

- sippy-ng/src/component_readiness/CompReadyVars.js
Partial revert.  Ken added a dummy qe job to get CR working again, but it'll be removed by this code eventually https://github.com/openshift/sippy/blob/master/pkg/variantregistry/loader.go#L103
> Remove qe from defaults

- pkg/variantregistry/ocp.go
Temporary fix until underlying issue is fixed in origin, and then we need to make this condition for releases <= whatever release we fix origin in.
> TRT-1777: Use jobname for NetworkStack as origin cluster-data cannot detect dualstack yet

- sippy-ng/src/component_readiness/CheckboxList.css
- sippy-ng/src/component_readiness/CompReadyMainInputs.js
- sippy-ng/src/component_readiness/CompReadyUtils.js
- sippy-ng/src/component_readiness/CompReadyVars.js
- sippy-ng/src/component_readiness/ComponentReadiness.js
- sippy-ng/src/component_readiness/GroupByCheckboxList.js
- sippy-ng/src/component_readiness/IncludeVariantCheckboxList.js
- sippy-ng/src/component_readiness/ReleaseSelector.js
Enable the UI for specifying variants for cross-comparison, both in the
UI parameters and API parameters. This introduces the "Compare" button  
in the variant selection sidebar, and plumbs the results through. This  
adds parameters for "variantCrossCompare" and "compareVariant" which    
specify (respectively) the variant groups that should query for 
different values in sample vs basis, and what those actual values should
be.
There was also a fair amount of refactoring and renaming along the way.
I tried to distinguish variantGroup ("Architecture") from individual    
variants ("Architecture:amd64"). Hopefully the result is clearer.
Since this could take a while, I added a second commit that removes the "Compare" button in the UI so that if we want, we can merge this PR without …
> TRT-1619: cross-variant comparison UI

- sippy-ng/package-lock.json
npm audit is now failing lint, example: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_sippy/1927/pull-ci-openshift-sippy-master-lint/1828115495451103232
This is the result of running npm audit fix
> npm audit fix

- pkg/api/componentreadiness/component_report.go
- pkg/api/componentreadiness/queryparamparser.go
- pkg/api/componentreadiness/queryparamparser_test.go
- pkg/api/componentreadiness/test_details.go
- pkg/api/utils.go
- pkg/apis/api/componentreport/types.go
- pkg/sippyserver/metrics/metrics.go
- sippy-ng/src/component_readiness/CompReadyTestReport.js
- sippy-ng/src/component_readiness/CompReadyUtils.js
- sippy-ng/src/component_readiness/CompReadyVars.js
- sippy-ng/src/component_readiness/GeneratedAt.js
- sippy-ng/src/component_readiness/GroupByCheckboxList.js
- sippy-ng/src/component_readiness/IncludeVariantCheckboxList.js
following on previous preparation, this brings the API and UI support together to provide variant cross-comparison.
* the `Compare` button is returned to the UI, and bugs with cross-compare fixed.
* the API converts CR parameters into comparable queries with different sets of variants for basis and sample.
* the test_details UI displays what is being compared in a helpful format.
> TRT-1619: variant cross-comparison api

- pkg/api/componentreadiness/test_details.go
base and sample queries run in goroutines, based on the same parameter variables that were updated in between; sometimes this would result in both queries being the same. by separating the variables this is prevented.
(this was for test_details only; regular CR pages already came from correctly separated queries)
> api bugfix: race condition in sample/base queries

- sippy-ng/src/prow_job_runs/ProwJobRun.js
This was because important intervals did not have the display flag
correctly set until 4.17. Now that we're primarily focused on 4.17+,
this can be unselected by default. If working with old releases and you
see too little data, just check the box.
> Stop selecting override display flag by default on intervals charts

- sippy-ng/src/component_readiness/CompReadyVars.js
I noticed that sometimes when checking variants in the sidebar, they got lost (not translated to params) when generating the report. I _think_ this fixes that.
> ui: hopefully fix weird CR state problems with variants

- pkg/api/componentreadiness/test_details.go
- pkg/variantregistry/ocp.go
- pkg/variantregistry/ocp_test.go
- Owner was not part of the TestDetails query and we were picking up non eng jobs.  
- Triage is based on TestDetails and perfscale job was added added to the triage job runs
- ComponentReadiness detected more triaged job runs than failures and skipped triage
- Fixed TD query to honor IncludeVariants not referenced elsewhere
- Found periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.17-periodics-e2e-aws-arm showing up as amd64, updated variant parsing
> trt-1788: Ensure IncludeVariants not otherwise referenced are part of test_details query

- sippy-ng/src/component_readiness/CompReadyUtils.js
- sippy-ng/src/component_readiness/ComponentReadiness.js
- sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
- sippy-ng/src/component_readiness/RegressedTestsModal.js
- sippy-ng/src/component_readiness/RegressedTestsPanel.js
- sippy-ng/src/component_readiness/TriagedIncidentGroups.js
- sippy-ng/src/component_readiness/TriagedIncidentsPanel.js
- sippy-ng/src/component_readiness/TriagedVariants.js
- Moved RegressedTests to its own panel
- Consolidated code creating regression data arrays
- Added new tab with all regressed tests
- Refactored Triaged Incidents Test Failures columns to better align with Regressed Tests
> trt-1792: Add all regressions view to RegressedTestsModal.js

- pkg/api/componentreadiness/component_report.go
- sippy-ng/src/component_readiness/TriagedIncidentGroups.js
- Skip returning incidents that don't have relevant runs
- Make the JIRA URL a link
> trt-1792: Add Jira Link, filter irrelevant incidents

- sippy-ng/package-lock.json
There's a CVE in path-to-regexp. Ran `npm audit fix`.  In the end, the fixes were backported to work with react-router v5 but it wasn't clear that was going to happen: we need to move to v6.
Also the CVE itself is a nothing burger, we might want to move to something else to let us skip CVE's that aren't applicable (npm audit out of the box doesn't do that).
> TRT-1807: CVE-2024-45296 update path-to-regexp

- hack/gen-resolved-issue.md
- hack/gen-resolved-issue.py
Adds the ability to generate allowed regressions JSON for override at GA
See [component-readiness-triage/pull/7](https://github.com/neisw/component-readiness-triage/pull/7) for template / output
> Support generating intentional regressions JSON output

- pkg/api/componentreadiness/test_details.go
This was introduced with the variant cross-compare; originally the CompareVariants would only include variants under cross-compare, so I used that to determine whether this bit of code needed to add the variant filter or not. Later I updated the code to fill out CompareVariants with all the variants, which caused this bit to skip adding basically everything. Thus Owner, which is not in the RequestedVariants, if not in the cross-comparison would never be filtered. By scoping the exclusion to the variant groups under cross-comparison, it returns to its original intent.
> TRT-1813: fix bug omitting some variants from test_details filter

- sippy-ng/src/tests/TestTable.js
When clicking the Flakes icon, it doesn't filter the job run list by the variants for that row on the tests table. We were just using the wrong filter model to pass in.
> TRT-1808: fix flakes link to include variants in job runs filter

- pkg/regressionallowances/intentional_regressions.go
- pkg/regressionallowances/regressions_4.17.json
Partially replaces #1991.  Thanks @neisw.
- pkg/regressionallowances/intentional_regressions.go - embed the new json file and import into 4.17
- pkg/regressionallowances/regressions_4.17.json - add two tests for OVN Vsphere UPI
> OCPBUGS-39580 Add console test regression for 4.17

- Makefile
- cmd/sippy/component_readiness.go
- cmd/sippy/serve.go
- hack/go-lint.sh
- pkg/api/componentreadiness/component_report.go
- pkg/api/componentreadiness/component_report_test.go
- pkg/api/componentreadiness/test_details.go
- pkg/api/disruption_report.go
- pkg/api/releases.go
- pkg/api/utils.go
- pkg/componentreadiness/tracker/tracker.go
- pkg/sippyserver/metrics/metrics.go
- pkg/sippyserver/server.go
goroutines need to be terminated when an HTTP request ends, currently without a context they keep running.   We also need to pass these into `bigquery.Query()` so the DB query terminates too.
If you wanted to test this PR:
1. Start up component readiness and click on an uncached square
2. Immediately close the browser tab -- notice the queries are terminated (you'll see context cancelled in the logs)
If you try this without this PR, the queries will continue executing. 
New goroutines should follow this pattern:
```go
go func() {
wg.Add(1)
defer wg.Done()
select {
case <-ctx.Done():
logrus.Infof("Context canceled while fetching base job run test status")
return
default:
// work to do
}
```
> TRT-1836: wire up contexts for http requests

- config/qe-views.yaml
They don't have any metal jobs in their tables.  I had thought the error was coming from the hardcoded list in the frontend code, but metal was accidentally listed in their views when I copied and pasted it from engineering's.
> TRT-1849: Remove metal from QE platforms

- pkg/api/pull_requests.go
- pkg/db/query/payload_queries.go
- pkg/sippyserver/server.go
No UI but we can use the api to get diffs after the release-controller has rolled off older payloads
```
http://127.0.0.1:8080/api/payloads/diff?fromPayload=4.18.0-0.nightly-2024-10-15-171849&toPayload=4.18.0-0.nightly-2024-10-16-001902
```
```
[
{
"id": 0,
"created_at": "0001-01-01T00:00:00Z",
"updated_at": "0001-01-01T00:00:00Z",
"deleted_at": null,
"url": "https://github.com/openshift/api/pull/2060",
"pull_request_id": "2060",
"name": "cluster-config-api",
"description": "Ensure custom feature gate mainfest path is passed into generator",
"bug_url": ""
},
{
"id": 0,
"created_at": "0001-01-01T00:00:00Z",
"updated_at": "0001-01-01T00:00:00Z",
"deleted_at": null,
"url": "https://github.com/openshift/api/pull/2062",
"pull_request_id": "2062",
"name": "cluster-config-api",
"description": …
```
> NO-JIRA: payload diff

- pkg/api/test_analysis.go
- pkg/db/db.go
- pkg/db/matviews.go
Replace by a live normal view that uses the test analysis by job matview, and then joins in the variants and sums the results. This is very fast when filtering for a test. As a matview in testing it was still a bit slow, at least 5 minutes, I'm not sure how long, but given we can live query it that seems the best approach.
The data looks correct with my spot checks:
```
postgres=# select * from prow_test_analysis_by_variant_14d_matview where test_id=34 and date = '2024-10-23' and variant='Network:ovn';
test_id |            test_name            | watchlist |    date    |   variant   | release | runs | passes | flakes | failures 
---------+---------------------------------+-----------+------------+-------------+---------+------+--------+--------+----------
34 | install should succeed: …
```
> Eliminate the 50+ minute test analysis by variant matview

- sippy-ng/src/bugs/BugButton.js
- sippy-ng/src/component_readiness/CompReadyTestReport.js
e.g. [visit locally](http://localhost:3000/sippy-ng/component_readiness/test_details?Architecture=amd64&Architecture=amd64&FeatureSet=default&FeatureSet=default&Installer=ipi&Installer=ipi&Network=ovn&Network=ovn&NetworkAccess=default&Platform=metal&Platform=metal&Scheduler=default&SecurityMode=default&Suite=unknown&Suite=unknown&Topology=ha&Topology=ha&Upgrade=micro&Upgrade=micro&baseEndTime=2024-10-01%2023%3A59%3A59&baseRelease=4.17&baseStartTime=2024-09-01%2000%3A00%3A00&capability=ClusterUpgrade&columnGroupBy=Architecture%2CNetwork%2CPlatform%2CTopology&component=Cluster%20Version%20Operator&confidence=95&dbGroupBy=Platform%2CArchitecture%2CNetwork%2CTopology%2CFeatureSet%2CUpgrade%2CSuite%2CInstaller&environment=amd64%20default%20ipi%20ovn%20metal%20unknown%20ha%20micro&ignoreDisrupti …
> TRT-1859: file jira with helpful summary

- cmd/sippy/component_readiness.go
- cmd/sippy/serve.go
- cmd/sippy/trackregressions.go
- pkg/api/componentreadiness/component_report.go
- pkg/api/componentreadiness/component_report_test.go
- pkg/api/componentreadiness/queryparamparser.go
- pkg/api/componentreadiness/test_details.go
- pkg/api/utils.go
- pkg/apis/api/componentreport/types.go
- pkg/apis/cache/cache.go
- pkg/bigquery/client.go
- pkg/cache/bigquerycache/bigquery.go
- pkg/cache/bigquerycache/bigquery_test.go
- pkg/cache/compressed/cache.go
- pkg/cache/compressed/cache_test.go
- pkg/cache/redis/redis.go
- pkg/flags/cache.go
- pkg/sippyserver/server.go
- pkg/util/utils.go
- sippy-ng/src/component_readiness/AdvancedOptions.js
- sippy-ng/src/component_readiness/CompCapTestRow.js
- sippy-ng/src/component_readiness/CompReadyMainInputs.js
- sippy-ng/src/component_readiness/CompReadyTestCell.js
- sippy-ng/src/component_readiness/CompReadyTestPanel.js
- sippy-ng/src/component_readiness/CompReadyTestReport.js
- sippy-ng/src/component_readiness/CompReadyUtils.js
- sippy-ng/src/component_readiness/CompReadyVars.js
- sippy-ng/src/component_readiness/ComponentReadiness.js
- sippy-ng/src/component_readiness/RegressedTestsPanel.js
- Queries previous releases without variant, capability or testid filtering
- Caches results so navigating down through capabilities doesn't cause the query to run again
- Compares stats from previous releases based on testIdentification and selects the one with the highest pass rate
- Includes Advanced Option for `Historical release analysis` default is exclude currently
- Fallback test details shows both the queried base release status and fallback when applicable
- Override Release Assessment
- Fallback Release Assessment
- Fallback Release basis with dates
- Override Release basis with dates (new tab)
When included the regressed since column will be empty since regression tracking is currently not aware of these
Test Details Report will show tabs for the requested basis as well as the …
> TRT-1811: fallback queries

- config/views.yaml
- pkg/api/componentreadiness/component_report.go
- pkg/api/componentreadiness/test_details.go
Getting this to work fully in some kind of generic fashion across the UI
and query params will be extremely difficult. We're not even sure the
idea will work, so for now this PR adds a hacky temporary solution.
A scheduled query is doing a full table scan every day and copying
rarely run junit results to a much smaller table in bigquery,
junit_rarely_run_jobs. This allows us to scan it without the immense
cost.
For this temporary view, I added a hack where if we see you're querying
for JobTier rare, we will flip to using this other table.
Side effect, if someone uses the UI and adds in this JobTier, suddenly
their results will be fully busted.
> TRT-1772: Hacky solution to test rarely run jobs results

- config/views.yaml
- sippy-ng/src/component_readiness/CompReadyUtils.js
- sippy-ng/src/component_readiness/ComponentReadiness.js
Currently 4.19-rarely-run-jobs returns no json in the response ~~causing errors in the UI~~
CR Shows 92 regressions with historical release analysis (fallback) enabled vs 63 without
> TRT-1864: enable 4.19 views

- OWNERS
- pkg/api/componentreadiness/component_report.go
- pkg/api/componentreadiness/queryparamparser.go
- pkg/api/componentreadiness/test_details.go
- pkg/api/job_analysis.go
- pkg/api/job_runs.go
- pkg/api/jobs.go
- pkg/api/tests.go
- pkg/api/utils.go
- pkg/filter/filterable.go
- pkg/sippyserver/install_details.go
- pkg/sippyserver/parameters.go
- pkg/sippyserver/server.go
- pkg/util/param/param.go
this also helps a bit with [TRT-1890](https://issues.redhat.com//browse/TRT-1890) (normalization) since values all go into named parameters instead of directly in the query.
> TRT-1781: sanitize sippy-server parameter inputs

- config/views.yaml
Starting in 4.19 we'd like to enforce TP reliability by having it in the main dashboard.
> component readiness: enforce techpreview in 4.19+

- pkg/apis/api/types.go
- pkg/db/query/feature_gates.go
- pkg/sippyserver/server.go
- sippy-ng/src/App.js
- sippy-ng/src/components/Sidebar.js
- sippy-ng/src/constants.js
- sippy-ng/src/helpers.js
- sippy-ng/src/releases/PayloadStreamsTable.js
- sippy-ng/src/releases/ReleaseOverview.js
- sippy-ng/src/tests/FeatureGates.js
- sippy-ng/src/tests/TestAnalysis.js
- sippy-ng/src/tests/TestTable.js
- sippy-ng/src/tests/Tests.js
Sippy has historically showed the "working" percentage (success +
flake), but we're ready to deprecate this concept and show pass rate
only (strict success).  This is the first part: only in core sippy.  CR will come later.
We already do this for the o/api feature gate analyzer, which uses strict success. This
results in confusion when people try to do archeology in Sippy and see the rates
reported (working) don't match o/api's requirements (success).
While Sippy users can change the view from Working -> Passing, it's not
very discoverable.
This PR:
- Adds a "Feature Gates" page per release, that links to the tests-by-variant
- Deprecates "Working" reporting from sippy -- only show success pass rates
- Caches test result pages for speedier loading
> Improve test reporting for feature gates

- pkg/variantregistry/ocp.go
- pkg/variantregistry/ocp_test.go
- origin reports these clusters as "AWS" - make sure we accept the ROSA override
- Perfscale and SD use "HCP" in hypershift job names
> Fix ROSA Variants

- Dockerfile.buildroot
The one installed by dnf install is go1.22.7. We don't need to manually install this in the dockerfile.
> Use default go version from dnf install

- config/views.yaml
> Add ROSA to 4.19-main dashboard

- sippy-ng/src/tests/TestPassRateCharts.js
- sippy-ng/src/tests/TestStackedChart.js
This is working around an edge case with our new method of daily
reporting on test analysis via bigquery, rather than matview refreshes.
A few tests exist in sippy but are not imported into bigquery, and as
such no longer have any test analysis available. This was causing the
page to crash.
Show a clear indicator that no analysis is available and keep the page
loading properly for the rest of it.
Example test that doesn't load today until this pr merges: https://sippy.dptools.openshift.org/sippy-ng/tests/4.17/analysis?test=Build%20image%20image-based-install-operator%20from%20the%20repository&filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22Build%20image%20image-based-install-operator%20from%20the%20repository%22%7D%2C%7B …
> Allow page loads when test analysis is empty

- pkg/api/utils.go
We believe specifying a redis url when no redis is listening is linked
to cost issues for developers using the views file, which is very easy
to do. Redis outages would be rare, so we're now going to exit if we
detect a redis url specified, but get a connection refused.
> Log fatal and exit on redis outage

- sippy-ng/src/tests/TestTable.js
Any test below 95% pass rate will be marked as red, test colors are now an up-or-down vote (green or red - not gradiented).
> Force test table colors to be green or red

- sippy-ng/src/App.js
Any URL with a release can use "latest" to get Sippy's default release, it will redirect.
e.g.
http://localhost:3000/sippy-ng/feature_gates/latest
It also supports mentioning a feature gate in the URL which will redirect to the right place:
http://localhost:3000/sippy-ng/feature_gates/latest/NetworkSegmentation
> TRT-1923, TRT-1925: Feature gate and release URL helpers

- pkg/api/disruption_report.go
- pkg/apis/api/types.go
- pkg/sippyserver/metrics/metrics.go
Created V2 views to transition to the additional feature_set variant
Verified locally the feature_set label is populated
```
sippy_disruption_vs_prev_ga{architecture="amd64",backend="aws-network-liveness-new-connections",compare_release="4.17",delta="P75",feature_set="techpreview",master_nodes_updated="N",network="ovn",platform="gcp",release="4.19",releaseStatus="Development",topology="ha",upgrade_type="none"} 0
sippy_disruption_vs_prev_ga{architecture="amd64",backend="aws-network-liveness-new-connections",compare_release="4.17",delta="P75",feature_set="default",master_nodes_updated="Y",network="ovn",platform="gcp",release="4.19",releaseStatus="Development",topology="ha",upgrade_type="minor"} 0
```
> trt-1768: add feature_set labels

- pkg/sippyserver/server.go
Turns out my [macro-driven refactor](https://github.com/openshift/sippy/pull/2112/files) removed some `return` statements. Oops.
Respond correctly for jobs that request RA but sippy does not import. They still won't get RA but at least it will be clear why not.
The 3 commits are distinct small changes in this file.
> TRT-1924: fix refactor and handle missing jobs

- pkg/dataloader/prowloader/prow.go
We check if they're ignored before creating test results, but not when
we check if the test record itself needs to be created, leading to many
thousands of tests in the db we do not want.
> Stop creating ignored tests in db.

- sippy-ng/src/tests/FeatureGates.js
Colorization was originally based on "is there enough tests" (e.g. at least 5), but it is being mistaken as "this feature gate is passing tests and is good."
This removes the colors.
> Remove colors from feature gate table

- pkg/api/job_runs.go
- pkg/db/query/test_queries.go
In working on reducing matview CPU, I recently moved us to a partitioned
table test_analysis_by_job_by_dates, updated once a day, and we do not
prune old dates as we intended to allow configurable ranges to generate
the test pass rate graphs.
I analyzed running queries on postgres and found many risk analysis
queries, tracing back to this use of the new table without a filter on
dates. This means jobs are constantly running and requesting risk
analysis, and scanning this table that's growing larger and larger
without a date filter. Fixing this may well fix our problem with the
matviews as this could be what's taking all the cpu.
> Attempt a fix for postgres CPU

- pkg/sippyserver/server.go
According to AWS RDS performance monitoring, this query is the main culprit for our spiked CPU usage - temporarily disabling the endpoint.
> Temporarily disable job run risk analysis

- hack/gen-resolved-issue.py
- sippy-ng/src/component_readiness/CompReadyTestPanel.js
TestDetails is usually accessed via a regression.  But when changing the dates it can come back as not regressed without sample stats.  Add protection for that.  Also add protection in triage script for prow 502 errors.
> TRT-1993: Handle TestDetails No Regression / Missing Sample Stats

- pkg/sippyserver/server.go
We've added an index targeting the problem query, and lightened the load in other ways; see what happens with RA back on now.
> Revert "Temporarily disable job run risk analysis"

- Dockerfile
- pkg/api/componentreadiness/component_report.go
- pkg/api/componentreadiness/component_report_test.go
- pkg/api/componentreadiness/middleware/interface.go
- pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances.go
- pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances_test.go
- pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
- pkg/api/componentreadiness/middleware/releasefallback/releasefallback_test.go
- pkg/api/componentreadiness/query/querygenerators.go
- pkg/api/componentreadiness/query/releasedates.go
- pkg/api/componentreadiness/test_details.go
- pkg/api/componentreadiness/utils/utils.go
- pkg/apis/api/componentreport/types.go
- pkg/componentreadiness/jiraautomator/jiraautomator_test.go
- **Reapply "[TRT-1982](https://issues.redhat.com//browse/TRT-1982): Introduce middleware starting with ReleaseFallback impl"**
- **Fix cache key bug with base/sample test details queries**
Found the bug, the private reqOptions on the base/sample query generators meant cache keys were serializing as: time="2025-02-26T14:05:46.953-04:00" level=info msg="cache hit" key="BaseJobRunTestStatus~{\"BaseRelease\":\"4.18\",\"BaseStart\":\"2025-01-27T00:00:00Z\",\"BaseEnd\":\"2025-02-26T16:00:00Z\"}" type=componentreport.JobRunTestReportStatus
Causing all kinds of weird and horrifying wires to be crossed when you loaded the test details pages for subsequent tests. Fix is to make the field public and thus serialized as it was intended, but I missed.
> Introduce middleware for release fallback and intentional regressions (attempt 2)

- pkg/api/job_runs.go
- pkg/api/job_runs_test.go
- pkg/api/jobrunintervals/job_run_intervals.go
- pkg/api/tests.go
- pkg/apis/api/types.go
- pkg/apis/sippyprocessing/v1/types.go
- pkg/db/models/pr_commenting.go
- pkg/db/query/job_queries.go
- pkg/db/query/test_queries.go
- pkg/github/commenter/ghcommenter.go
- pkg/sippyserver/pr_commenting_processor.go
- pkg/sippyserver/pr_commenting_processor_test.go
- pkg/sippyserver/pr_new_tests_worker.go
- pkg/sippyserver/pr_new_tests_worker_test.go
- pkg/sippyserver/server.go
We have an issue where new tests often don't reliably produce success results, or have other issues like dynamic components in the test name (e.g. a namespace).
Expand the risk analysis PR commenter to report on all never-before-seen tests in presubmits, with a link/reminder of our test standards.
[Example comment](https://github.com/openshift/origin/pull/29512#issuecomment-2678344068)
> TRT-1825: pr commenting refactor, add new-test analysis

- .golangci.yml
Some new rules are failing, like converting 3+ if statements to switch.
> Only enable checks for gocritic we already enabled

- hack/go-lint.sh
New version seems too slow for our CI system
> Increase timeout for golangci-lint

- pkg/api/jobrunintervals/job_run_intervals.go
- pkg/dataloader/prowloader/gcs/gcs_jobrun.go
- pkg/dataloader/prowloader/prow.go
- pkg/variantregistry/ocp.go
In the GCS code, we're ignoring non-iterator errors, and hitting this in our cron jobs for QE. Looks like maybe the variant registry job doesn't have access to the QE GCS bucket.  This was failing silently before.
> Ensure we handle any google error

- DEVELOPMENT.md
- cmd/sippy-daemon/main.go
- cmd/sippy/automatejira.go
- cmd/sippy/component_readiness.go
- cmd/sippy/serve.go
- cmd/sippy/trackregressions.go
- cmd/sippy/variants_generate.go
- pkg/flags/google.go
The commands that utilize the GCS creds are:
`automatejira`, `component_readiness`, `load`, `serve`, `trackregressions`, `variants_generate`, and `sippy-daemon`. Of these, only `load` doesn't require it in all cases, so I have left validation off for it.
> Add validation for gcs credentials and clarify the development readme

- cmd/sippy/component_readiness.go
- pkg/api/componentreadiness/component_report.go
- pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
Missed passing the db connection through to the metrics loop here. If the
auth sippy which runs the component-readiness entrypoint command
happened to be the one which found the cache expired, it would populate
it without regressed since values. This would happen roughly half the
time.
> Fix missing regressed since values

- pkg/api/componentreadiness/query/querygenerators.go
Query was failing due to ambiguous `org` reference
> NO-JIRA: qualify pr options with job table name

- pkg/api/componentreadiness/query/querygenerators.go
- pkg/variantregistry/ocp.go
Also an update for https://github.com/openshift/sippy/pull/2402
> Exclude konflux jobs from component readiness

- sippy-ng/src/releases/PayloadCalendar.js
The alert will display if the current view of the payload calendar didn't return any results for `accepted` or `rejected` payloads; to warn the user that there might be something wrong. It will also display (with a different message) when there is actually an error returned from any of the event sources.
> TRT-1540: add alert when no accepted or rejected results are found for the payload calendar

- config/qe-views.yaml
- use absolute datetime for base release
- time duration of base release is 30 days. queried earliest modified_time of auto release job from BigQuery
- only keep qe for variant owner, remove service-delivery
- base release version is same as sampel release
> OCPERT-33 add/refine qe view for releases 4.14+

- pkg/api/componentreadiness/test_details.go
- pkg/apis/api/componentreport/types.go
- sippy-ng/src/component_readiness/CompReadyTestDetailRow.js
- sippy-ng/src/component_readiness/CompReadyTestPanel.js
- sippy-ng/src/component_readiness/CompReadyTestReport.js
- sippy-ng/src/component_readiness/CompReadyUtils.js
- sippy-ng/src/component_readiness/RegressedTestsModal.js
- sippy-ng/src/component_readiness/TriagedTestJobRuns.js
- Adds the Triaged Tests view used in the Regressed Tests Modal Dialog to Test Details when there is 1 or more associated Triage records
- Marks Triaged JobRuns with `T` instead of `F`
> trt-2058: Show Triaged Issues in TestDetails

- sippy-ng/src/App.js
- sippy-ng/src/component_readiness/CompCapRow.js
- sippy-ng/src/component_readiness/CompCapTestRow.js
- sippy-ng/src/component_readiness/CompReadyCapsCell.js
- sippy-ng/src/component_readiness/CompReadyEnvCapabilities.js
- sippy-ng/src/component_readiness/CompReadyEnvCapability.js
- sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
- sippy-ng/src/component_readiness/CompReadyRow.js
- sippy-ng/src/component_readiness/CompReadyTestCell.js
- sippy-ng/src/component_readiness/CompReadyTestReport.js
- sippy-ng/src/component_readiness/CompSeverityIcon.js
- sippy-ng/src/component_readiness/ComponentReadiness.js
- sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
- sippy-ng/src/component_readiness/RegressedTestsModal.js
- sippy-ng/src/component_readiness/RegressedTestsPanel.js
- sippy-ng/src/component_readiness/Sidebar.js
- sippy-ng/src/components/AccessibilityModeProvider.js
- sippy-ng/src/components/AccessibilityToggle.js
There are only 2 places that actually need the value of `accessibilityModeOn`: `CompReadyTestReport` and `CompSeverityIcon`. The rest of the usages were just prop drilling. We can use `useContext` to avoid that and make this much cleaner.
> NO-JIRA: refactor accessibility mode to use context

- pkg/variantregistry/ocp.go
- pkg/variantregistry/ocp_test.go
These were not intended to be blocking signal yet and should not be causing red cells.
> Exclude osde2e jobs in component readiness

- pkg/api/jobartifacts/apitypes.go
- pkg/api/jobartifacts/manager.go
- pkg/api/jobartifacts/query.go
- pkg/api/jobartifacts/query_test.go
- pkg/sippyserver/pr_commenting_processor_test.go
- pkg/sippyserver/pr_new_tests_worker_test.go
- pkg/sippyserver/server.go
- pkg/util/param/param.go
- pkg/util/testing.go
- pkg/util/utils.go
Search a set of job runs for artifacts matching a glob and (optionally) content matching a string. API params are:
- `prowJobRuns`: a comma-separated list of prow job run IDs to query
- `pathGlob`: a glob pattern to match against the GCS path (ref. https://cloud.google.com/storage/docs/json_api/v1/objects/list#list-object-glob)
- `textContains` (optional): a string to search for in the contents of the artifacts, returning the containing line
Returns a JSON `jobartifacts.QueryResponse` object listing the job runs, the artifacts that matched the glob, and (optionally) lines within those artifacts that matched. Errors that occurred are also listed per job run. To prevent (accidental) DOS, the number of artifacts and matches returned are limited.
Example query: …
> API to enable querying job artifacts

- sippy-ng/src/component_readiness/CompReadyMainInputs.js
We want to be able to compare nat-instance to default network access modes.
> Add network access to sidebar

- DEVELOPMENT.md
We will always need the `load-openshift-ci-bigquery` flag when running in `ocp` mode due to https://github.com/openshift/sippy/blob/531d36b8dd127678279b12706fccf126dda1b430/pkg/flags/mode.go#L43-L48
> NO-JIRA: specify required flag when running in `ocp` mode

- pkg/api/componentreadiness/component_report_test.go
- pkg/api/componentreadiness/query/querygenerators.go
- pkg/api/componentreadiness/test_details.go
- pkg/apis/api/componentreport/types.go
test_details report data now includes the original sample/base job names (if relevant) and a new attr for job run ID. So it now looks like:
```
{
...
"job_stats": [
{
"job_name": "periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-X.X-periodics-e2e-aws-techpreview",
"sample_job_name": "periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.19-periodics-e2e-aws-techpreview",
"base_job_name": "",
"sample_stats": {...},
"base_stats": {...},
"sample_job_run_stats": [
{
"job_url": "https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.19-periodics-e2e-aws-techpreview/1906587761641525248",
"job_run_id": "1906587761641525248",
"test_stats": {
"success_rate": 1, …
```
> enrich test details results

- sippy-ng/src/component_readiness/RegressedTestsPanel.js
The function name was changed in https://github.com/openshift/sippy/commit/93cc9d230e45b2237b98bd32296c6d4eaf927e84#diff-10893e44787a52095576ae3ffa73c55ba0c42a28ba33682ebb4e7978ed4514af, and this usage was missed
> NO-JIRA: use new function name to restore functionality

- pkg/api/componentreadiness/component_report_test.go
- pkg/api/componentreadiness/test_details.go
- pkg/apis/api/componentreport/types.go
- sippy-ng/src/component_readiness/CompReadyTestDetailRow.js
- sippy-ng/src/component_readiness/CompReadyTestPanel.js
- sippy-ng/src/component_readiness/ComponentReadiness.js
Rather than a "normalized" job name taking up an oversized column on the left, the real job names are interleaved with their results. Also if a sample or basis job is not present, name and zeroed stats are omitted. I think this is clearer, and it compacts better than the previous layout (where the long job name would become many lines).
The normalized name no longer has a use in the UI so omit it.
> change layout of `test_details` results

- pkg/variantregistry/ocp.go
These are double counting results and need better consideration for inclusion.
They also are rarely run. If they were to degrade, they would be
swallowed in larger buckets as things stand now.
> cert-rotation-shutdown jobs get JobTier=hidden and a Procedure

- pkg/api/releases.go
- pkg/api/releases_test.go
- pkg/apis/api/types.go
- pkg/apis/sippy/v1/types.go
- pkg/sippyserver/server.go
Pass along DevelStartDate so callers can determine if development has started on the release yet.  Allowing us to add releases prior to actual branch cut / dev start dates
> TRT-2080: Include dev start date with Release

- pkg/api/jobartifacts/apitypes.go
- pkg/api/jobartifacts/content_line_matcher.go
- pkg/api/jobartifacts/content_line_matcher_test.go
- pkg/api/jobartifacts/manager.go
- pkg/api/jobartifacts/query.go
- pkg/api/jobartifacts/query_test.go
- pkg/sippyserver/server.go
- pkg/util/param/param.go
two commits:
* patterns/readability around select statements    
I found the select logic around channel actions jarring and repetitive; I think it's clearer if those patterns are named and implemented outside the main logic.
* expand content matching
introduces a more generic ContentMatcher type to handle any type of match we might like for an artifact file's content.
existing implementations can read files a line at a time and match strings like before, or match a regex. these can also return context lines around the match. the api is updated with parameters for constructing these.
future implementations can enable processing json, yaml, or xml.    
e.g. [regex match http://localhost:8080/api/jobs/artifacts?prowJobRuns=1905396175427604480,1905379393581092864,1905368974137233408,190540970 …
> jobartifacts: readability, expand content matching

- pkg/variantregistry/ocp.go
Per discussion today we hope to eliminate suite, so we use Procedure now
for a job doing it's own thing.
Move to candidate as the job has a known problem that needs fixing and
should not be in CR as a new job.
> Classify console-operator jobs as candidate and give a procedure

- pkg/api/componentreadiness/component_report.go
Context is in the comments.
Note the current regressions without the fix:
And with:
There are 15 cases in the current sample (excluding aws) that are hitting this right now.
> NO-JIRA: Adjust partial triage counts

- pkg/sippyserver/server.go
- sippy-ng/src/component_readiness/CompReadyUtils.js
- sippy-ng/src/component_readiness/CompReadyVars.js
- sippy-ng/src/component_readiness/CompSeverityIcon.js
- sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
- sippy-ng/src/component_readiness/RegressedTestsModal.js
- sippy-ng/src/component_readiness/RegressedTestsPanel.js
- sippy-ng/src/component_readiness/TriagedRegressionTestList.js
- sippy-ng/src/component_readiness/TriagedRegressions.js
- sippy-ng/src/component_readiness/TriagedTestsPanel.js
The option to add a new triage entry will only be available in auth sippy.
This also sets the corresponding tests to the applicable triaged status and icon. It adds a new panel to the regressed tests modal to display these entries and associated tests.
The new panel will eventually replace the current "Triaged Tests" panel, but for now it is in addition to it. With that in mind, I have mostly copied that panel into new components and made the necessary updates rather than adapting it to work with both use cases.
There will be a follow up to add a `Description` field to the backend, DB, and UI for triage entries.
Add a new entry:
View entries:
> TRT-2045: add the ability to create a triage entry in the UI, and update modal accordingly

- pkg/api/componentreadiness/query/querygenerators.go
- pkg/api/componentreadiness/test_details.go
- pkg/apis/api/componentreport/types.go
include job start time in the details so that it can be provided to the user for context. so results now look like
```
...
"sample_job_run_stats": [
{
"job_url": "https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.19-periodics-e2e-aws-techpreview/1909849662261563392",
"job_run_id": "1909849662261563392",
"start_time": "2025-04-09T06:03:37",
"test_stats": {
"success_rate": 1,
"success_count": 1,
"failure_count": 0,
"flake_count": 0
}
}, ...
```
> test_details: include start time in job run data

- pkg/api/componentreadiness/triage.go
- pkg/db/query/triage_queries.go
- pkg/sippyserver/server.go
- sippy-ng/src/component_readiness/CompReadyTestReport.js
If `triage` entries are present for the displayed `test_id` and `sampleRelease` they will show on the test-details page instead of the `TriagedIncidentsPanel`. Eventually, the latter will be removed entirely.
> TRT-2045: display triages on test-details page

- pkg/api/componentreadiness/component_report.go
- pkg/api/componentreadiness/component_report_test.go
- pkg/api/componentreadiness/middleware/interface.go
- pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances.go
- pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances_test.go
- pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker.go
- pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
- pkg/api/componentreadiness/middleware/releasefallback/releasefallback_test.go
- pkg/api/componentreadiness/regressiontracker.go
- pkg/api/componentreadiness/test_details.go
- pkg/api/componentreadiness/utils/utils.go
- pkg/apis/api/componentreport/types.go
- sippy-ng/src/component_readiness/RegressedTestsPanel.js
- **Reapply "Improve middleware and port regression tracker over"**
- **Fix panic with no base stats**
- **Suboptimal fix for missing basis in fallback test details reports**
The latter commit is not the arch I was hoping for but it's too complex to tackle right now.
Merging this carries the unexpected fixing of fallback beyond 4.17, there are only a couple regressions that match 4.15 and 4.16, and they look like they're regressed either way so they should not be new.
> Regression Tracking + Improved Fallback Middleware

- pkg/api/health.go
- pkg/api/releases.go
- pkg/api/releases_test.go
RHCOS is no longer tied to the OCP release.
> Remove RHCOS version mismatch warnings

- sippy-ng/src/component_readiness/CompReadyTestReport.js
Accidentally displayed them when there were no results. The check should be `> 0`, rather than `>= 0`
> TRT-2045: don't show triaged tests list if there are none

- sippy-ng/src/App.js
- sippy-ng/src/prow_job_runs/IntervalsChart.js
The existing time filtering worked poorly, it was impossible to get to precise times, often buggy, and would still include mass empty rows between intervals actually in the frame.
Add actual interval time filtering, prepopulated with the first/last intervals times. You can then adjust precisely if desired and see only intervals in that timeframe. A reset button is included, and these are working as query params so you can send someone a link to just what you see.
Also took the time to sort the Categories/Sources buttons, and wrap them so we no longer have to scroll to the right all the time.
> Time filtering for intervals charts

- sippy-ng/src/component_readiness/RegressedTestsModal.js
`Triaged Tests` will display as long as there is at least one entry, otherwise it will be `Triaged Incidents`. Eventually, `Triaged Incidents` will be removed entirely.
> TRT-2045: only display one of "Triaged Incidents" or "Triaged Tests" tabs

- pkg/api/componentreadiness/component_report.go
- pkg/api/componentreadiness/component_report_test.go
- pkg/api/componentreadiness/middleware/interface.go
- pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances.go
- pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances_test.go
- pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker.go
- pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
- pkg/api/componentreadiness/middleware/releasefallback/releasefallback_test.go
- pkg/api/componentreadiness/regressiontracker.go
- pkg/api/componentreadiness/test_details.go
- pkg/api/componentreadiness/utils/utils.go
- pkg/apis/api/componentreport/types.go
- sippy-ng/src/component_readiness/RegressedTestsPanel.js
- **Reapply "Regression Tracking + Improved Fallback Middleware"**
- **Fix new tests not being annotated with regression data**
> Regression Tracking + Fallback Middleware Improvements Attempt #3

- sippy-ng/src/component_readiness/RegressedTestsPanel.js
The API return value changed in https://github.com/openshift/sippy/commit/64b4c66791c10dbc025de8264a08c5ca9653c3a0
> NO-JIRA: fix the test checkbox by updating the location of the regression_id in the JSON

- pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker.go
- pkg/api/componentreadiness/test_details.go
- pkg/sippyserver/server.go
Follows up on https://github.com/openshift/sippy/pull/2559 to make the middleware work on the test details report
> TRT-2089: fully wire up regression tracking middleware on test_details

- pkg/variantregistry/ocp.go
New [jobs](https://github.com/openshift/release/pull/64143/files) for 4.19 with known failures, don't want show as regressions so marking candidate
> NO-JIRA: set 4.19 jobs as candidate

- pkg/sippyserver/server.go
- sippy-ng/src/component_readiness/CompReadyTestReport.js
- sippy-ng/src/component_readiness/RegressedTestsPanel.js
- sippy-ng/src/component_readiness/TriageFields.js
- sippy-ng/src/component_readiness/UpsertTriageModal.js
This refactors as much of the form logic from the `RegressedTestsModal` as I could into a new `TriageFields` component that is used in the original location, and in a new `UpsertTriageModal` from the `CompReadyTestReport`. It allows for the association of the test to either an existing, or new, triage entry. At that point, the page is reloaded, and the status icon is updated to reflect the triage. The new modal is named `Upsert` because I plan on reusing it to edit a triage in other ways from the, yet-to-be-created, triage page.
> TRT-2089: allow the ability to triage a test from the test_details report

- pkg/api/componentreadiness/regressiontracker.go
- pkg/db/models/triage.go
- sippy-ng/src/component_readiness/TriagedRegressionTestList.js
- test/e2e/componentreadiness/regressiontracker/regressiontracker_test.go
For the duration a regression is open, track the max number of failures we saw in the sample window. This will be helpful for determining what minFail we should use, and provide insights related to regressions that go away on their own.
Doesn't work great with triage right now for the same reason we see 100% passing on a triaged test details page, we decrement traiged runs today and don't return any info on them. This will be better in the new traige where job runs only get decremented when the regression is considered closed.
Also removed temp bigquery migration code for the postgres rollout that
I forgot to come back for.
Also tracks the last failure time for the regression. 
And finally displays that in the triaged portion of the regressed tests modal. This will allow us to better see …
> TRT-2056: Track more regression data and show last failure in triaged table

- cmd/sippy-daemon/main.go
- cmd/sippy/component_readiness.go
- cmd/sippy/serve.go
- pkg/api/jobrunintervals/job_run_intervals.go
- pkg/apis/api/interval.go
- pkg/flags/google.go
- pkg/sippyserver/server.go
- sippy-ng/src/prow_job_runs/IntervalsChart.js
the intervals page insisted on finding a job run in the DB even though it has what it needs in most cases from the parameters. rather than break for jobs that don't have entries in the DB (like when invoked with `/payload-job`), the DB lookup is now optional (but authoritative if present).
i think this covers all of the cases we will actually see. we could futher fall back to looking up the job in BQ `jobs` table, but it looks unnecessary.
also there's now a link to the job run.
> TRT-2105: intervals for payload-job runs

- e2e-scripts/sippy-e2e-sippy-e2e-test-commands.sh
- pkg/api/componentreadiness/regressiontracker.go
I saw failures intermittently on the port 8080 which makes me think two pods on the same CI node both running sippy e2e at once may conflict? Trying random ports.
Also opening up psql access again with a random port, so we can enable some of the tests that use direct psql.
> TRT-2120: Enable sippy e2e db tests and prevent port collisions

- sippy-ng/src/App.js
- sippy-ng/src/component_readiness/CompReadyTestReport.js
- sippy-ng/src/component_readiness/CompReadyUtils.js
- sippy-ng/src/component_readiness/RegressedTestsPanel.js
- sippy-ng/src/component_readiness/Triage.js
- sippy-ng/src/component_readiness/TriageFields.js
- sippy-ng/src/component_readiness/TriagedRegressionTestList.js
- sippy-ng/src/component_readiness/TriagedRegressions.js
- sippy-ng/src/component_readiness/UpsertTriageModal.js
This is a quick MVP to allow for the resolution date to be set in the UI. There will be more to come here in a followup PR.
The Triage details page looks like:
It utilizes a modal for edits:
> TRT-2050: create a page for `triage` details and allow some simple edits

- pkg/api/componentreadiness/query/querygenerators.go
This looks to have come in with the non-enabled treat flakes as failures
feature, but we mistakenly assumed to do that all the time in the query
for calculating last failure time. As a result, we show tests that have
flaked since their triage resolution as pants on fire when we didn't
actually count a test failure.
Last failure will now be correct for the main use case, but not for
flakes as failures, we'll need to revisit if that feature ever takes off
in a default view.
I've also switched to using prowjob start time for the last failure, not
modified time which I believe is ingestion time. This was confusing as
the test details page shows job runs and their start times.
> TRT-2122: Fix last failure time picking up flakes

- pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker.go
- pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker_test.go
The new middleware did not account for regressions actually clearing the
sample. (oops) If the sample is no longer regressed, we should not be
adjusting status based on whether or not it's triaged and resolved, it's
just gone.
This was causing things to never leave the report.
> Fix triaged and resolved regressions staying open forever

- config/views.yaml
I noticed in 4.19, we're not monitoring for regressions in hypershift in CR.  This adds it to the main view for 4.20+
> Hypershift should be blocking in CR for 4.20+

- pkg/dataloader/bugloader/bugloader.go
- pkg/db/models/prow.go
On `test_details` pages we look up bugs that have been linked according to the test name. However sometimes test names change and are mapped to a shared "unique" id. In this case, we would like the bug to be linked not only from the `test_details` for the test name it mentions, but also from the test_details of any test mapped with that.
This update enhances the bugloader to look up mapped tests as bugs are scanned and link those in bug_tests as well as the mentioned test.
> TRT-2044: bugloader: associate mapped tests with bugs

- pkg/variantregistry/ocp.go
Follow up to https://github.com/openshift/release/pull/64752 and https://github.com/openshift/origin/pull/29776
Just a draft for now, but since the original tests were added to serial directly and have reached the necessary pass rates before, I went ahead and added it to the views as well for 4.20.
> MCO-1652: Add MCO suite tracking

- pkg/dataloader/bugloader/bugloader.go
- pkg/db/models/prow.go
Not certain this is related but it's suspicious:
```
time="2025-05-21T13:30:57.329Z" level=warning msg="1 errors were encountered while loading database:"
time="2025-05-21T13:30:57.329Z" level=error msg="loader \"bugs\" returned error: error deleting stale bugs: ERROR: update or delete on table \"bugs\" violates foreign key constraint \"fk_triages_bug\" on table \"triages\" (SQLSTATE 23503)"
Error: errors were encountered while loading database, see logs for details
```
Reverts openshift/sippy#2619
> Revert "TRT-2044: bugloader: associate mapped tests with bugs"

- pkg/dataloader/bugloader/bugloader.go
- pkg/db/models/prow.go
(reinstate #2619)
On test_details pages we look up bugs that have been linked according to the test name. However sometimes test names change and are mapped to a shared "unique" id. In this case, we would like the bug to be linked not only from the test_details for the test name it mentions, but also from the test_details of any test mapped with that.
This update enhances the bugloader to look up mapped tests as bugs are scanned and link those in bug_tests as well as the mentioned test.
> unrevert TRT-2044: bugloader: associate mapped tests with bugs

- pkg/dataloader/bugloader/bugloader.go
- pkg/db/query/job_queries.go
- pkg/db/query/test_queries.go
triage records reference bugs and we don't want to remove those. there's no real reason to remove stale bugs, just filter them out of our queries.
> don't delete bugs anymore

- sippy-ng/src/component_readiness/CompReadyUtils.js
- sippy-ng/src/component_readiness/RegressedTestsModal.js
- sippy-ng/src/component_readiness/RegressedTestsPanel.js
- sippy-ng/src/component_readiness/TriagedRegressionTestList.js
- sippy-ng/src/component_readiness/TriagedRegressions.js
- sippy-ng/src/component_readiness/TriagedTestsPanel.js
This adapts functionality from the `RegressedTestsPanel` to utilize in the `TriagedRegressionTestList` on the modal as well. The adapted functionality now resides in `CompReadyUtils`.
This is not shown on the triage details page as we don't have the necessary info available there to determine the URL. This could be enhanced in the future if desired, but I don't think it is necessary.
> TRT-2094: add a link to the test_details report for each triage record

- sippy-ng/src/App.js
https://github.com/openshift/sippy/pull/2649 broke the page as it now uses the `expandEnvironment` function
> TRT-2094: fix triage details page by wrapping in the CompReadyVarsProvider

- pkg/dataloader/bugloader/bugloader.go
- pkg/dataloader/testownershiploader/testownershiploader.go
make sippy loads more friendly for my brain.
> bugloader refactor

- pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker.go
- pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker_test.go
They will reappear if failures are observed after the resolution date.
Should be visible in the new All Triages page, though not with
regressions attached as those would be gone.
This also means the regression tracker will close the regression at that
time, but it will also reuse the old regression record if it reopens within 5 days.
> Hide triaged resolved ci-infra regressions

- sippy-ng/src/App.js
- sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
- sippy-ng/src/component_readiness/RegressedTestsModal.js
- sippy-ng/src/component_readiness/RegressedTestsPanel.js
- sippy-ng/src/component_readiness/TriagedRegressionTestList.js
- sippy-ng/src/component_readiness/TriagedRegressions.js
Params are cleared when switching tabs within the modal (as they may no longer be relevant), and also when closing the modal.
This also uses the query params for other usages of the panels, but that is nice functionality. The only downside there is the way they are named, but I think keeping `modal` in the name is worth it for clarity within the source code itself.
> TRT-1787: use query params for selections within the regressed test modal 

- sippy-ng/src/component_readiness/Triage.js
- sippy-ng/src/component_readiness/TriagedRegressions.js
- sippy-ng/src/helpers.js
- Triage details page title to show description
- Table hides created and updated columns by default; only show jira updated
column
- Show timestamps as relative 
- Show resolution as a glanceable status icon
- Format all timestamps to second precision for consistency
> TRT-2147: Improvements to triage pages

- sippy-ng/src/component_readiness/AddRegressionPanel.js
- sippy-ng/src/component_readiness/CompReadyTestReport.js
- sippy-ng/src/component_readiness/RegressedTestsPanel.js
- sippy-ng/src/component_readiness/UpsertTriageModal.js
This modifies the logic so that the `UpsertTriageModal` is used when triaging regressions within the `RegressedTestsModal`. This has the effect of including the ability to add to an existing triage record. In order to support this, the upsert logic needed to be changed so that it could add multiple regressions to a triage at a time, which was previously not necessary.
We could actually follow up on this to edit the triage directly from the modal now fairly simply...
> TRT-2146: Add to existing Triage from RegressedTestsModal

- pkg/sippyserver/server.go
I want to verify that we have access to this info without making changes to our oauth proxy pod
> TRT-1474: log the user making a mutating triage request in preparation for auditing

- sippy-ng/src/component_readiness/CompReadyVars.js
* [original broken link from the example jira](https://sippy-auth.dptools.openshift.org/sippy-ng/component_readiness/test_details?Aggregation=none&Architecture=amd64&Architecture=amd64&FeatureSet=default&FeatureSet=default&Installer=hypershift&Installer=hypershift&LayeredProduct=none&Network=ovn&Network=ovn&NetworkAccess=default&Platform=azure&Platform=azure&Procedure=none&Scheduler=default&SecurityMode=default&Suite=parallel&Suite=parallel&Topology=external&Topology=external&Upgrade=none&Upgrade=none&baseEndTime=2025-05-26%2023%3A59%3A59&baseRelease=4.19&baseStartTime=2025-04-26%2000%3A00%3A00&capability=OCPFeatureGate%3AGatewayAPIController&columnGroupBy=Architecture%2CNetwork%2CPlatform%2CTopology&component=Networking%20%2F%20router&confidence=95&dbGroupBy=Platform%2CArchitecture%2CNetw …
> TRT-2154: handle old test_details links

- pkg/api/componentreadiness/component_report.go
- pkg/api/componentreadiness/component_report_test.go
- pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances.go
- pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances_test.go
- pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
- pkg/api/componentreadiness/middleware/releasefallback/releasefallback_test.go
- pkg/api/componentreadiness/test_details.go
- pkg/api/componentreadiness/utils/utils.go
- pkg/apis/api/componentreport/types.go
I set out to refactor `test_details.internalGenerateTestDetailsReport` for readability and along the way discovered a few bugs to fix. The bug fixes are isolated to their own commits; otherwise no functionality should be changing. Those (relatively simple) commits:
* two `respect FlakeAsFailure` commits
* `bugfix: also assessTestStats on sample-only tests`
* `baseRegression tweaking now handled in middleware` - at least I think? If anyone has a testcase handy it would be good to check.
I'd especially appreciate a review of my "fixes" to make sure they really are fixes. That should be much less work than a total review -- the actual refactoring is less suspicious; I got some good test failures along the way to make sure there was some coverage, and the results seem OK locally.
> refactor of `test_details` analysis

- pkg/api/componentreadiness/component_report.go
- pkg/api/componentreadiness/middleware/list.go
- pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances.go
- pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
- pkg/api/componentreadiness/test_details.go
- pkg/apis/api/componentreport/types.go
- pkg/regressionallowances/types.go
Following on previous refactor with some simplifications and finally a refactor to `generateComponentTestReport` in CR.
Also abstracted out middleware calls and CR.getStatusFromBigQuery goroutine management.
No changes to functionality, except that middleware calls consistently bail out at the first error, where before there were places they would keep running (Devan confirmed that wasn't for any reason).
May be easiest to review individual commits; each has fairly limited scope.
> more CR refactoring

- config/qe-views.yaml
Update base release in 4.19-qe-main from 4.18 to 4.19 and add two new views:
- 4.19-qe-auto-release for automated release testing
- 4.20-qe-main for 4.20 release testing
> Update QE views for 4.19 and add 4.20 view

- sippy-ng/src/component_readiness/AddRegressionPanel.js
- sippy-ng/src/component_readiness/ExistingTriageSelector.js
- sippy-ng/src/component_readiness/TriageFields.js
This will allow the user to instead select (one of) the other record(s), or continue to create a new one if desired.
Here is what it looks like as soon as the `Jira URL` field matches any existing triage entries:
Confirmation when the user still attempts to create a new entry. It doesn't stop them, but makes them aware:
Augment assisted with refactoring out the `ExistingTriageSelector` component.
> TRT-2138: add soft-validation when user attempts to create a triage with a duplicate Jira

- pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker.go
- pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker_test.go
This allows for the triage list to display on the report when the regression has been triaged since the last cache refresh
> TRT-2166: add the triages to the analysis regression in post-analysis 

- pkg/dataloader/bugloader/bugloader.go
This fixes a panic in `bugloader`. I searched through the code looking for other places that may update the triage without setting the current-user, and can't find anything else. I considered changing the logic so that it wouldn't panic if this were to happen somewhere else, but I am worried that we wouldn't notice the issue and end up with an empty user in the audit logs instead.
> NO-JIRA: set current-user on context when updating triage record via bugloader

- go.mod
- pkg/api/job_runs.go
- pkg/api/jobs.go
- pkg/cache/bigquerycache/bigquery.go
- pkg/componentreadiness/resolvedissues/types.go
- pkg/dataloader/bugloader/bugloader.go
- pkg/github/commenter/ghcommenter.go
- pkg/sippyserver/server.go
- pkg/synthetictests/ocp_synthetic_tests.go
- pkg/util/rate_limiter.go
- pkg/util/utils.go
nolint was added for a few integer conversion warnings. I think our use case should be safe. Or we will have to go through code path to make sure we are all consistent with using signed or unsigned integers.
> TRT-2192: Bump go version in go.mod to 1.24

- pkg/api/componentreadiness/component_report.go
- pkg/api/componentreadiness/query/querygenerators.go
- pkg/api/componentreadiness/queryparamparser.go
- pkg/apis/api/componentreport/reqopts/types.go
- pkg/util/param/param.go
- sippy-ng/src/component_readiness/CompReadyMainInputs.js
- sippy-ng/src/component_readiness/CompReadyUtils.js
- sippy-ng/src/component_readiness/CompReadyVars.js
- sippy-ng/src/component_readiness/ReleaseSelector.js
This functionality broke the cache-primer by making it calculate the sample stats utilizing job runs from multiple releases.
This reverts commit 0911cbb98d889b3829959f759ebf1fc343554cf2.
> TRT-2191: Revert "Allow multiple payload to be used for sample"

- pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
Very few of the exported fields within the `fallbackTestQueryGenerator` and `fallbackTestQueryReleasesGenerator` are actually used in their respective queries. These 2 new cache keys only utilize those fields.
I didn't use AI at all to write the code, but I did use Cursor (Claude-4-sonnet) to check my work:
> Looking at the `fallbackTestQueryGenerator` struct and its cache key, I need to examine which exported fields are used in the query logic but not included in the cache key.
> 
> Let me search for how `query.BuildComponentReportQuery` uses the `ReqOptions` parameter to understand what fields are actually needed:
> Ran tool
> 
> Let me examine the `BuildComponentReportQuery` function more closely to see what fields are actually used in fallback queries:
> Read file: …
> TRT-2179: Add an explicit cache key for release fallback to limit unnecessary cache misses

- pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
This is a follow up to https://github.com/openshift/sippy/pull/2777. After #2777 merged it was noticed that the cache was still being updated every 4 hours (when the cache-primer runs). This is due to the cache-primer setting `ForceRefresh` to true. While that is valid for other usages, we don't want fallback information to be refreshed that frequently.
> TRT-2179: do not allow cache refresh to be forced for the `releasefallback` caching

- sippy-ng/src/component_readiness/TestDetailsReport.js
- sippy-ng/src/helpers.js
Previous fix broke other pre-existing callers of this function, so only the links from comp readiness are working.
The use of Link prevents us having to construct our own full href and is
more consistent with existing code.
> Fix test analysis links again

- DEVELOPMENT.md
- cmd/sippy/load.go
- e2e-scripts/sippy-e2e-sippy-e2e-setup-commands.sh
- scripts/e2e.sh
The `load-openshift-ci-bigquery` flag has long been the default option for prow loading. Now, the loader errors when that flag is not passed. Remove it.
> NO-JIRA: remove `load-openshift-ci-bigquery` flag

- pkg/api/componentreadiness/query/querygenerators.go
BigQuery allows for [any_value](https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#any_value) to be used with a `HAVING MAX` clause that we can use to get the most recent job run's test_name, instead of just a non-deterministic one.
The validity of this is very hard to verify in practice as the current behavior works correctly a significant portion of the time, and there are not that many tests that have been renamed recently to check on. I have spot checked a few, and haven't noticed anywhere where this has pulled back the old name.
@dgoodwin pointed out a potential failure case that we will have to keep an eye on:
> if we were comparing last week of 4.20 vs last week of 4.19, instead of month pre-ga, and 4.19 had the most recent job run, would we get the …
> TRT-2136: find the most recently started test name for display in the report

- config/views.yaml
Sync up variant_options for x86-vs-arm with main 4.20 settings
> trt-2195: update x86-vs-arm view

- sippy-ng/src/datagrid/utils.js
This small PR fixes class generation in invert mode where a local `scaleColors` variable overshadowed, breaking correct styling. This affected both the Payload Test Failures and Payload Stream Test Failures components.
> Fix class generation logic in invert mode

- sippy-ng/src/prow_job_runs/IntervalsChart.js
This adds new CertificateRotation section with controller events updating secrets/configmaps and issuing CSRs.
Also created for origin: https://github.com/openshift/origin/pull/29279
> API-1802: intervals: show certificate rotation events

- pkg/dataloader/bugloader/bugloader.go
Tracking the actual transition (along with the time) would be needlessly complex. We can get a very close approximation by just resolving _any_ triages that are not resolved which have their associated bug in one of the proper statuses at the current time. the `bugloader` runs hourly, so this will be very close to the transition time.
The status values look funny, but I checked the DB, and those are the real values. Some are upper case, some use underscores, and some have spaces...
> TRT-2112: auto-resolve triages when we detect that the associated bug's status has moved to "Modified" or beyond

- sippy-ng/src/component_readiness/CompReadyCapCell.js
- sippy-ng/src/component_readiness/CompReadyCapsCell.js
- sippy-ng/src/component_readiness/CompReadyCell.js
- sippy-ng/src/component_readiness/CompReadyTestCell.js
- sippy-ng/src/component_readiness/CompReadyVars.js
- sippy-ng/src/component_readiness/CompTestRow.js
- sippy-ng/src/component_readiness/ComponentReadiness.js
This fixes testId undefined during env_capability → env_test navigation, and makes URL params consistent.
The ComponentReadiness component was using local React state to store URL parameters (testId, testName, testBasisRelease, etc), but useState only initializes once. When navigating between routes, URL parameters changed but local state didn't update, causing testId to be undefined on certain transitions.
Assisted-by: Cursor AI
> TRT-2218: Centralize URL params in vars context

- pkg/variantregistry/ocp.go
This PR enables sippy for usernamespace suite.
https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.20-e2e-gcp-ovn-usernamespace
> OCPNODE-3520: Add usernamespace procedure

- config/views.yaml
- pkg/api/componentreadiness/component_report.go
- pkg/api/componentreadiness/queryparamparser_test.go
in 4.20 we've added `LayeredProduct:virt` to the views, without distinguishing that as a variant. This causes the `virt` and non-`virt` data to be mixed and actually shows up as new regressions.
Once this code is in, we can update the existing regressions to include the new variant with:
`update test_regressions set variants = (variants || '{LayeredProduct:none}') where release='4.20';`
> TRT-2235: include LayeredProduct in DBGroupBy

- cmd/sippy/annotatejobruns.go
- cmd/sippy/automatejira.go
- cmd/sippy/load.go
- config/openshift-customizations.yaml
- config/openshift.yaml
- pkg/api/health.go
- pkg/api/install.go
- pkg/api/releases.go
- pkg/api/releases_test.go
- pkg/api/utils.go
- pkg/apis/api/types.go
- pkg/apis/sippy/v1/types.go
- pkg/bigquery/client.go
- pkg/dataloader/crcacheloader/crcacheloader.go
- pkg/dataloader/featuregateloader/featuregateloader.go
- pkg/dataloader/prowloader/prow.go
- pkg/db/query/test_queries.go
- pkg/flags/bigquery.go
- pkg/sippyserver/metrics/metrics.go
- pkg/sippyserver/server.go
- pkg/util/param/param.go
- pkg/variantregistry/ocp.go
- sippy-ng/src/App.js
- sippy-ng/src/component_readiness/ReleaseSelector.js
- sippy-ng/src/component_readiness/TestDetailsReport.js
- sippy-ng/src/components/Sidebar.js
- sippy-ng/src/releases/InstallTopLevelIndicators.js
- sippy-ng/src/releases/TopLevelIndicators.js
Enable arbitrary releases that don't look like "x.y". Define capabilities in the BQ Releases table, and stop treating Presubmits as special (mostly). This enables adding releases like aro-integration with a subset of capabilities.
/hold
This requires updating the Release table schema and contents and updating BackendDisruptionPercentilesDeltaCurrentVsPrevGAV2, then clearing old cache content and re-priming.
> TRT-2198: enable sippy to accept hcm releases

- pkg/api/componentreadiness/query/querygenerators.go
Branch is populated by ci-to-bigquery cf and uses a different regex than variants for extracting release / branch.  This lets things slip in that won't work for CR.  We can either use the variant release value in our query which we do can validate in our testing or update our release parsing like in https://github.com/openshift/sippy/pull/2859
> trt-2229: use variant release for cr

- pkg/variantregistry/ocp.go
Per https://redhat-internal.slack.com/archives/C01CQA76KMX/p1755062667189139, `periodic-ci-openshift-insights-operator-release-4.20-periodics-vsphere-insights-runtime-extractor-tests` is causing the OLM component readiness regressed because of instability.
> Flag vsphere-insights-runtime jobs as hidden

- config/views.yaml
- pkg/variantregistry/ocp.go
- **Demote several unstable hypershift jobs to candidate status to clean up 4.20 board**
- **Add a hypershift view that includes their candidate jobs for stabilization in 4.21.**
> Demote subset of unstable hypershift jobs to candidate status for 4.20

- pkg/api/autocomplete.go
- pkg/sippyserver/server.go
Broken with https://github.com/openshift/sippy/pull/2870
Cursor doesn't think anything else is broken:
> The server is properly using the Gorilla Mux router for path parameter extraction rather than manual path trimming. The only manual path trimming is for:
Frontend file serving - necessary for React router support
Static asset serving - handled by Go's standard library
All API endpoints that need path parameters (like the triage endpoints and autocomplete) are correctly using mux.Vars() to extract URL parameters, which is the proper approach with the Gorilla Mux router.
Conclusion: The sippy server endpoints are properly implemented and not using problematic manual path trimming for extracting API parameters. The existing path trimming is only used for legitimate file serving purposes.
> NO-JIRA: use the gorilla matcher for autocomplete endpoint

- cmd/sippy/load.go
- pkg/api/componentreadiness/component_report.go
- pkg/api/componentreadiness/component_report_test.go
- pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances.go
- pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances_test.go
- pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
- pkg/api/componentreadiness/middleware/releasefallback/releasefallback_test.go
- pkg/api/componentreadiness/query/querygenerators.go
- pkg/api/componentreadiness/query/releasedates.go
- pkg/api/componentreadiness/test_details.go
- pkg/api/componentreadiness/utils/utils.go
- pkg/apis/api/componentreport/crtest/types.go
- pkg/dataloader/crcacheloader/crcacheloader.go
- pkg/dataloader/featuregateloader/featuregateloader.go
- pkg/dataloader/releaseloader/releasesync.go
- pkg/sippyserver/server.go
- sippy-ng/src/component_readiness/ReleaseSelector.js
- sippy-ng/src/components/Sidebar.js
It's likely easiest to review a commit at a time.
first commit is in response to [this comment](https://github.com/openshift/sippy/pull/2857/files?diff=unified&w=1#r2263027287). (I chose against the [other nit](https://github.com/openshift/sippy/pull/2857/files?diff=unified&w=1#r2262985126).)
the second commit uses the Releases table by default for loaders that need releases specified. this way we can remove all the `fetchdata` release params (although if supplied they are used) and not need to update the cronjob every time we add a release.
following commits expand on that a little bit to make the Releases table authoritative everywhere in the backend.
> TRT-2198: followup to releases change

- config/views.yaml
- pkg/variantregistry/ocp.go
This naming convention helps filter by the one specifically matching job that should be collected under the correlated component (`CNV-lp-interop`).
All other related virt data (collected from multiple jobs) can be remain under the `virt` filter.
> Add -lp-interop-virt LP filtering

- pkg/api/componentreadiness/triage.go
- pkg/api/componentreadiness/triage_test.go
- pkg/sippyserver/server.go
- sippy-ng/src/component_readiness/Triage.js
- sippy-ng/src/component_readiness/TriageAuditLogsModal.js
- test/e2e/componentreadiness/triage/triageapi_test.go
Adds a new button to the triage details page to display audit logs in a user-friendly way in a new modal dialog. This information is only requested when a user clicks on the button. It displays a colorful diff of each change to the respective triage along with the time and user associated with the change.
The implementation here couples the logic to the current state of the `triage` data model. If we end up making breaking changes to that data model in the future, we will have to address them in the diffing logic. I think that has a pretty low likelihood of being an issue though.
Assisted by Cursor
> TRT-2189: display triage audit logs on the Triage details page when requested

- cmd/sippy/load.go
- pkg/api/componentreadiness/component_report.go
- pkg/api/componentreadiness/component_report_test.go
- pkg/api/componentreadiness/test_details.go
This is an unrevert with a fix for the panic due to a nil pointer on `testStats.BaseStats` when there is no basis. This is only being used to grab the release for logging, so in this case we will just log `no basis`.
> TRT-2289: Bandage fix for test_details reports not showing as regressed when they do on the main report

- pkg/db/query/triage_queries.go
Bug details were always empty in test details triage table, but present if you went to the triage tab indicating we have the data, it's just not being returned from the API.
> TRT-2310: Display triaged jira details in test details triage table

- pkg/api/componentreadiness/regressiontracker.go
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11559ee]
goroutine 1 [running]:
github.com/openshift/sippy/pkg/api/componentreadiness.(*RegressionTracker).SyncRegressionsForReport(_, {_, _}, {{0xc0008ddc50, 0x9}, {{{0xc0008ddcd0, 0x4}, 0x0, 0x0, {0x0, ...}, ...}, ...}, ...}, ...)
/go/src/sippy/pkg/api/componentreadiness/regressiontracker.go:305 +0x46e
```
> TRT-2210: fix panic in regression tracker when BaseStats is nil

- pkg/dataloader/bugloader/bugloader.go
- pkg/db/models/prow.go
- sippy-ng/src/component_readiness/Triage.js
- sippy-ng/src/component_readiness/TriagedRegressions.js
I have already update the `openshift-ci-data-analysis.jira_data.tickets_dedup` view to include the new field.
> TRT-2249: obtain release_blocker status on bugs and display it on linked triage in the UI

- cmd/sippy/seed_data.go
- sippy-ng/src/tests/TestTable.js
This does not enforce that feature gate test results are coming from component readiness included job tiers, but it does help display to the user whether they are or not in the default view presented when clicking through to the fg tests table.
JobTier is now first in the list, previously it was typically hidden as it wasn't in the first 8. It will be green if an included jobtier, red otherwise.
Hide Network (always ovn now)
Hide Owner (still visible in tooltip)
Tooltip will also get a warning if the result is from an excluded jobtier to help explain.
In future, a dropdown view for included/excluded CR would be nice both on this table, and the jobs table.
Assisted-by: Cursor AI
> TRT-2263: Indicate when feature gate test results are coming from included/excluded jobtiers

- config/views.yaml
After discussion with leadership we are pulling hypershift until they can fix some issues and stabilize their CI signal. We will try again in 4.21 once signal is clean.
> Drop hypershift from main views for 4.20 and 4.21

- pkg/api/componentreadiness/test_details.go
- pkg/dataloader/crcacheloader/crcacheloader.go
The debug message for this issue where regressed tests aren't regressed could use some helpful info, like for what release and variants.
> TRT-2150: better debug info for cache primer issue
