.gitignore
main.go
pkg/html/html.go

also beginnings of a parameterizable "detailed analysis" view page.

add expandable list of failing tests for each platform

---

README.md

Fix markdown formatting for list of available params

readme: fix list formatting in "Detailed usage" section

---

main.go
pkg/html/html.go
pkg/util/utils.go
resources/route.yaml

also filter bug matching to only count bugs that match the release we are reporting on, and which are not already verified for at    least a week.

use v2 search api and retrieve more bug metadata

---

main.go
pkg/util/utils.go

also fix a bug in handling whether a test failure has a known bug or not
also add another variant of operator.Import to the ignore list

add `serial` platform

---

pkg/util/utils.go

This adds fips as platform for reporting.

add fips as a platform

---

pkg/html/html.go

Instead of the "search bug", you get an "open bug" link.

provide 'open a bug' on top platform failures

---

main.go
pkg/html/html.go
pkg/util/components.go
pkg/util/utils.go

This aims to show how many jobs a bz component is blocking.  It needs work on presentation and an "expand" button.  But basically every component is blocking someone pretty badly.

show how much components are blocking

---

OWNERS

many refactoring PRs and good general knowledge of how sippy works now.

add dead2k as an approver

---

pkg/html/jobaggregationresult.go
pkg/testgridanalysis/testidentification/platforms.go

fixes https://github.com/openshift/sippy/issues/86

add 'promote' variant and fix up some regex matches

---

pkg/html/html.go
pkg/html/jobaggregationresult.go
pkg/html/jobresult.go
pkg/html/testresult.go
pkg/testgridanalysis/testreportconversion/by_platform.go
pkg/testgridanalysis/testreportconversion/testresult.go

add indenting for expanding sections

---

pkg/testgridanalysis/testreportconversion/by_platform.go
pkg/testgridanalysis/testreportconversion/testresult.go

address minor fixup after some refactors

---

main.go
pkg/html/jobaggregationresult.go
pkg/html/jobresult.go

The jobTestCount is used to display the expanding section.  MaxInt isn't a good default, use 10.

default test display count to something more reasonable

---

main.go
pkg/api/api.go
pkg/apis/sippyprocessing/v1/types.go
pkg/html/failing_tests.go
pkg/html/fastest_moving_jobs.go
pkg/html/html.go
pkg/testgridanalysis/testgridanalysisapi/types.go
pkg/testgridanalysis/testreportconversion/by_tests.go
pkg/testgridanalysis/testreportconversion/test_report.go
pkg/util/utils.go

Adds slicing for jobs that suddenly start failing based on the last two days of results.  This is currently horrifying....

Job Pass Rates By Most Reduced Pass Rate

---

pkg/html/jobaggregationresult.go
pkg/testgridanalysis/testidentification/platforms.go

These jobs have different characteristics.

split vsphere into upi and ipi variants

---

pkg/api/api.go
pkg/apis/sippyprocessing/v1/types.go
pkg/html/decorations.go
pkg/html/failing_tests.go
pkg/html/html.go
pkg/html/top_level_indicators.go
pkg/testgridanalysis/testreportconversion/test_report.go
pkg/util/utils.go

add top level indicator for infra, install, upgrade

---

pkg/testgridanalysis/testidentification/test_identification.go

another job with a different setup container.

add handling for custom installation

---

pkg/apis/sippyprocessing/v1/types.go
pkg/html/decorations.go
pkg/html/failing_bzcomponents.go
pkg/html/failing_tests.go
pkg/html/fastest_moving_jobs.go
pkg/html/html.go
pkg/html/jobaggregationresult.go
pkg/html/jobresult.go
pkg/html/testresult.go
pkg/testgridanalysis/testreportconversion/by_tests.go
pkg/testgridanalysis/testreportconversion/test_report.go
pkg/testgridanalysis/testreportconversion/testresult.go

Add a section of curated tests.  We need this at the moment to track certain test which aren't failing frequently, but which are indicative of underlying problems.

add a curated test section

---

pkg/html/decorations.go
pkg/html/failing_bzcomponents.go
pkg/html/failing_tests.go
pkg/html/fastest_moving_jobs.go
pkg/html/html.go
pkg/html/jobaggregationresult.go
pkg/html/jobresult.go
pkg/html/testresult.go

This let's us see what appears to be noise and what appears to be consistent when we look at individual tests.

add number of flakes to test output

---

pkg/html/decorations.go
pkg/html/failing_bzcomponents.go
pkg/html/failing_tests.go
pkg/html/fastest_moving_jobs.go
pkg/html/html.go
pkg/html/jobaggregationresult.go
pkg/html/jobresult.go
pkg/html/testresult.go

This brings nearly all the html display into a common format.

use the job aggregation display functionality to render the BZ component view

---

pkg/testgridanalysis/testidentification/platforms.go

found a few more infrequents that have never passed.

add never passing jobs for 4.6

---

pkg/html/generichtml/decorations.go
pkg/html/generichtml/jobaggregationresult.go
pkg/html/generichtml/jobresult.go
pkg/html/installhtml/util.go
pkg/html/releasehtml/top_level_indicators.go

colorize jobs/variants with zero runs as gray

---

pkg/testgridanalysis/testidentification/test_identification.go

Adds handling for the new container name.

azure setup changed to multi-step

---

pkg/testgridanalysis/testgridconversion/synthentic_tests.go

moves jobsWithBadSetupContainer list to use a regex pattern for each job
to help with matching on multiple releases. May be useful in other
cases later.
- excludes all jobs matching
promote-release-openshift-machine-os-content-e2e-aws-4.[2-7].*
These jobs were showing warnings in all other releases except for
4.6

Update SetupContainer list; fix setup warnings

---

pkg/testgridanalysis/testidentification/component.go

Hi @deads2k, per your suggestion, I opened this PR, could you please help take a look?

add sig name for logging testing

---

pkg/testgridanalysis/testgridconversion/synthentic_tests.go

https://bugzilla.redhat.com/show_bug.cgi?id=1899121

Ignore 4.1 promote job too

---

pkg/api/api.go
pkg/apis/sippy/v1/types.go
pkg/apis/sippyprocessing/v1/types.go
pkg/buganalysis/cache.go
pkg/html/generichtml/bugs.go
pkg/html/generichtml/jobaggregationresult.go
pkg/html/installhtml/finalhealth_by_operators.go
pkg/html/installhtml/install_by_operators.go
pkg/html/installhtml/test_detail.go
pkg/html/installhtml/test_detail_html.go
pkg/html/installhtml/upgrade_by_operators.go
pkg/html/installhtml/util.go
pkg/html/releasehtml/html.go
pkg/html/releasehtml/top_level_indicators.go
pkg/testgridanalysis/testgridanalysisapi/types.go
pkg/testgridanalysis/testidentification/component.go
pkg/testgridanalysis/testidentification/variants.go
pkg/testgridanalysis/testreportconversion/by_variant.go
pkg/testgridanalysis/testreportconversion/test_report.go
pkg/util/utils.go

No code change, just renaming platform to variant.

rename platform to variant

---

main.go
pkg/sippyserver/analyzer.go
pkg/sippyserver/server.go
pkg/testgridanalysis/testidentification/no_variants.go
pkg/testgridanalysis/testidentification/ocp_variants.go
pkg/testgridanalysis/testidentification/variants.go
pkg/testgridanalysis/testreportconversion/by_variant.go
pkg/testgridanalysis/testreportconversion/test_report.go
pkg/testgridanalysis/testreportconversion/testresult.go

This will allow us to specify different variants for kube.  It just makes an instance variable that is passed around.

allow alternative variants per server

---

main.go
pkg/sippyserver/analyzer.go
pkg/sippyserver/server.go
pkg/testgridanalysis/testgridconversion/no_synthentic_tests.go
pkg/testgridanalysis/testgridconversion/ocp_synthentic_tests.go
pkg/testgridanalysis/testgridconversion/to_raw_data.go

Also updates the openshift detection to inspect the dashboard names.

allow synthetic test calculation to be configured

---

README.md
main.go
pkg/testgridanalysis/testidentification/kube_variants.go

Only a single is allowed for now by validation, but the arg is multiple.  Updated help for the new usage.

add the ability to specify a --variant

---

pkg/testgridanalysis/testidentification/test_identification.go

fixing this job:
https://testgrid.k8s.io/redhat-openshift-ocp-release-4.7-informing#periodic-ci-openshift-release-master-ocp-4.7-e2e-metal-assisted

add setup test name for metal-assisted

---

pkg/buganalysis/cache.go

properly filter out older closed/release_pending bugs from test-causality

---

pkg/html/releasehtml/failing_tests.go

the tests in this table will all have bugs associated with them

Use Bugs heading instead of File a bug

---

pkg/testgridanalysis/testidentification/test_identification.go

Reverts openshift/sippy#178
these strings were already present

Revert "add e2e-aws-upgrade-ipi-install-install-stableinitial as a setup container equivalent for upgrade jobs"

---

scripts/fetchdata-kube.sh

This matches the openshift one and allow building an image the contains the scripts required to gather data easily and consistently.

add kube data collection script

---

sippy-ng/package-lock.json

Fixing https://npmjs.com/advisories/1783

Update npm dependencies to pull in security fixes

---

pkg/testgridanalysis/testidentification/ocp_variants.go

signed-off-by: Deep Mistry
/cc @bparees 
/cc @ausil

Adding ARM64 to the sippy variant

---

Dockerfile
scripts/fetchdata-kube.sh

adds https://github.com/openshift/sippy/blob/master/scripts/fetchdata-kube.sh back to the image

add fetchdata-kube.sh back to docker image

---

OWNERS

He's had 64 commits and is the top #4 contributor.

Add dgoodwin as an OWNER

---

sippy-ng/package-lock.json

Ran:
npm audit fix
https://github.com/advisories/GHSA-74fj-2j2h-c42q

Update npm packages for a cve

---

pkg/testgridanalysis/testgridanalysisapi/types.go
pkg/testgridanalysis/testgridconversion/ocp_synthetic_tests.go
pkg/testgridanalysis/testgridconversion/to_raw_data.go
pkg/testgridanalysis/testidentification/test_identification.go
pkg/testgridanalysis/testreportconversion/jobresult.go
pkg/testgridanalysis/testreportconversion/testresult.go

Add some missing install tests. Also change all names from setup to install.

Install test fixes

---

pkg/testgridanalysis/testreportconversion/test_report.go

the `.Overall` tests are simply summaries of the data we're looking at, so they don't provide unique value to us for viewing.  It fills the "most failing test", with entries we cannot investigate.

trim unnecessary tests

---

pkg/testgridanalysis/testidentification/ocp_variants.go

Add a new 'assisted' variant

---

pkg/testgridanalysis/testgridconversion/to_raw_data.go
pkg/testgridanalysis/testgridconversion/to_raw_data_test.go

This is to address [TRT-174](https://issues.redhat.com/browse/TRT-174) where test names with random characters create an ever growing list of test names.  Checking for known pattern and replacing the random bits with 'random'.

Add cleanTestName and remove random operator names

---

pkg/buganalysis/bugcache.go

Looks like something is up here, 20 minutes worth of it.

Log bugzilla query timings.

---

pkg/api/job_analysis.go
pkg/db/db.go

This query to lookup the count of each failing test for a job by day was
taking about 17 seconds with a month of data.
Switching to a materialized view it appears down to 180ms or better. The
view takes about 18 seconds to refresh currently and contains 175k rows.

Speedup job analysis page with a materialized view.

---

pkg/db/db.go

Query was incorrectly using 13 (flake) instead of 12 (failure), but was
also not working for generically listing all runs for a job.
This change credit of @stbenjam fixes the problem, tested on globaly job
list -> all job runs, job analysis -> job runs button, and test analysis
-> failing jobs panel as well as job runs button.

Fix job runs API and UI.

---

sippy-ng/src/tests/TestAnalysis.js

Due to the limitations of the in-memory structs, the test analysis page
approximated pass rates.
This changes that page to now directly reference passes.  It also stops
considers flakes a pass.'
Compare the below to production: https://sippy.dptools.openshift.org/sippy-ng/tests/4.11/analysis?test=[sig-arch][Late]%20clients%20should%20not%20use%20APIs%20that%20are%20removed%20in%20upcoming%20releases%20[Suite:openshift/conformance/parallel]
As flakes == pass there, we hardly show anything at all.
This PR:

test analysis: correctly show percentages

---

pkg/testgridanalysis/testidentification/ocp_variants.go

- Alphabetize existing list
- Upgrade micro
- Upgrade minor
- Alibaba

Add some new variants

---

sippy-ng/src/bugzilla/BugzillaSearch.js
sippy-ng/src/bugzilla/BugzillaUtils.js
sippy-ng/src/helpers.js
sippy-ng/src/jobs/JobAnalysis.js
sippy-ng/src/jobs/JobRunsTable.js
sippy-ng/src/jobs/JobStackedChart.js
sippy-ng/src/jobs/JobTable.js
sippy-ng/src/jobs/JobsDetail.js
sippy-ng/src/releases/ReleaseOverview.js
sippy-ng/src/releases/ReleasePayloadAcceptance.js
sippy-ng/src/releases/ReleasePayloadDetails.js
sippy-ng/src/releases/ReleasePayloadJobRuns.js
sippy-ng/src/releases/ReleasePayloadPullRequests.js
sippy-ng/src/releases/ReleasePayloadTable.js
sippy-ng/src/tests/TestAnalysis.js
sippy-ng/src/tests/TestTable.js
sippy-ng/src/tests/TestsDetail.js

Replace use of the library encodeURIComponent with a wrapper that
additionally encodes square brackets.  Square brackets are NOT unsafe
per RFC1738, but Google and others mishandle them.

URI Encode square brackets

---

pkg/html/installhtml/install_by_operators.go
pkg/testgridanalysis/testgridanalysisapi/types.go
pkg/testgridanalysis/testidentification/test_identification.go

trying to add
```
: install should succeed: other | 0s
: install should succeed: configuration | 0s
: install should succeed: infrastructure | 0s
: install should succeed: cluster bootstrap | 0s
: install should succeed: cluster creation | 0s
: install should succeed: overall
```

add install stage tests to the install details page

---

pkg/testgridanalysis/testidentification/ocp_variants.go

Add additional missing variants

---

sippy-ng/src/datagrid/GridToolbarFilterMenu.js
sippy-ng/src/tests/TestTable.js

Ensure filter fields are ordered alphabetically

---

pkg/api/autocomplete.go
pkg/sippyserver/server.go
sippy-ng/src/datagrid/GridToolbarAutocomplete.js
sippy-ng/src/datagrid/GridToolbarFilterItem.js
sippy-ng/src/jobs/JobRunsTable.js
sippy-ng/src/jobs/JobTable.js
sippy-ng/src/tests/TestTable.js

Add autocomplete on tests, jobs, and variants. Part of making the test pages more useful.

Enable autocomplete for filters

---

main.go
pkg/sippyserver/server.go

Refresh metrics when the server is starting up in dbonly mode

trt-217: refresh metrics at startup

---

pkg/sippyserver/server.go

Fix OpenShift sippy running in plain kube mode

---

sippy-ng/src/jobs/JobAnalysis.js

- Fix job analysis preselecting all time most failing tests.

Fix job analysis preselecting all time most failing tests instead of last two weeks.

---

pkg/prowloader/prow.go
pkg/testgridanalysis/testgridconversion/to_raw_data.go
pkg/testidentification/test_identification.go
pkg/testidentification/test_identification_test.go

[TRT-269](https://issues.redhat.com//browse/TRT-269)
- Move ignored test regex to helper func
- Add "" as an ignored test name
- Use in prow importing code, too

Extract ignored test function and apply to prow imports too

---

pkg/prowloader/prow.go

The existing logic of adding test statuses together is bugged. Make one
pass and any number of failures always make a flake.
I think this is behind [TRT-270](https://issues.redhat.com//browse/TRT-270)

Correctly handle flakes in prow import

---

scripts/fetchdata.sh

[TRT-228](https://issues.redhat.com//browse/TRT-228)

Fetch data for 4.12

---

pkg/db/models/releases.go
pkg/releasesync/releasesync.go
pkg/releasesync/releasesync_test.go
sippy-ng/src/releases/ReleasePayloadTable.js

[TRT-349](https://issues.redhat.com//browse/TRT-349): Refresh existing Payload entries when Phase status changes and calculate if the status was forced

trt-349: track forced phases

---

pkg/prowloader/prow.go

[TRT-324](https://issues.redhat.com//browse/TRT-324)
This changes the logic of the prow-based sippy to match how testgrid handles suites (e.g., only look at pre-populated suites already in DB).  This should fix all the missing synthetic test handling stuff as tests will match one-to-one -- but only after clearing the DB.
I believe this is the last step to get equivalency between prow and testgrid-based sippy.

Match suites behavior of testgrid Sippy

---

pkg/api/releases.go
pkg/apis/api/types.go
pkg/db/models/releases.go
pkg/db/query/payload_queries.go
sippy-ng/src/components/NumberCard.js
sippy-ng/src/components/SummaryCard.js
sippy-ng/src/components/__snapshots__/SummaryCard.test.js.snap
sippy-ng/src/helpers.js
sippy-ng/src/releases/PayloadStreamOverview.js

[TRT-264](https://issues.redhat.com//browse/TRT-264)
Adding the min/mean/max stats that Brenton had mentioned in the JIRA ticket.  Open to opinions about how this is laid out, and whether we should show the min/max values too.

Show additional release payload statistics

---

sippy-ng/src/releases/ReleasePayloadTable.js

also addresses [TRT-298](https://issues.redhat.com//browse/TRT-298)

Fix variables to snake case for UI links

---

DEVELOPMENT.md
sippy-ng/README.md

[TRT-403](https://issues.redhat.com//browse/TRT-403)

Add some docs about working with prow/gcs/release controller data

---

scripts/fetchdata-prow.sh

Make sure older releases are collecting all the right data as well.

Collect all releases in Prow-based sippy

---

pkg/api/build_clusters.go
pkg/api/job_runs.go
pkg/apis/api/types.go
pkg/db/models/build_clusters.go
pkg/db/query/build_clusters.go
pkg/prowloader/prow.go
pkg/sippyserver/parameters.go
pkg/sippyserver/server.go
sippy-ng/src/App.js
sippy-ng/src/build_clusters/BuildClusterDetails.js
sippy-ng/src/build_clusters/BuildClusterHealthChart.js
sippy-ng/src/build_clusters/BuildClusterOverview.js
sippy-ng/src/build_clusters/BuildClusterTable.css
sippy-ng/src/build_clusters/BuildClusterTable.js
sippy-ng/src/components/Sidebar.js
sippy-ng/src/constants.js
sippy-ng/src/jobs/JobRunsTable.js
sippy-ng/src/releases/ReleaseOverview.js

[TRT-237](https://issues.redhat.com//browse/TRT-237)
First pass at a build health page.  Since cluster health isn't really constrained by release, this adds a new side bar item outside of Releases.
Unfortunately the data is noisy, but sharp drops (like build02 today) are visible.

Cluster health

---

pkg/api/tests.go
pkg/apis/api/types.go
pkg/db/matviews.go
sippy-ng/package-lock.json
sippy-ng/src/tests/TestTable.js

- Revert "Revert "Differentiate on test suite in NURPs test tables.""
- Add left join for suites to fix bug.

test suite nurp

---

sippy-ng/src/build_clusters/BuildClusterTable.js
sippy-ng/src/jobs/JobRunsTable.js
sippy-ng/src/jobs/JobTable.js
sippy-ng/src/releases/PayloadStreamTestFailures.js
sippy-ng/src/releases/PayloadStreamsTable.js
sippy-ng/src/releases/ReleasePayloadJobRuns.js
sippy-ng/src/releases/ReleasePayloadPullRequests.js
sippy-ng/src/releases/ReleasePayloadTable.js
sippy-ng/src/tests/TestTable.js

[TRT-284](https://issues.redhat.com//browse/TRT-284)
Currently selecting rows per page does nothing, this fixes it.

Fix rows per page selector

---

pkg/sippyserver/metrics/metrics.go

After this deploy, I will change the alert to include the newly added label.

Add silenced label to differentiate between zero runs and zero pass rate

---

pkg/sippyserver/metrics/metrics.go

Sippy stopped refreshing data recently because of TRT-533, it took 19
hours to spot it, so I think we need an alert to tell us when it's been
more than a couple of hours.  Job run data should get updated hourly.

Add metric for last data refresh

---

pkg/db/query/test_queries.go

This should fix https://issues.redhat.com/browse/TRT-508

Include suite check in bad nurp stats calculation

---

sippy-ng/src/releases/ReleaseOverview.js

i'm not sure if this was a deliberate construction of a new word (combining significant and sufficient), in which case feel free to close this and you have my admiration for the innovation, or not.

Fix significiently->significantly

---

sippy-ng/src/jobs/JobAnalysis.js

[TRT-82](https://issues.redhat.com//browse/TRT-82)
In the select/view tests modal, this adds a link to the test analysis page for that test.

Make test name clickable from job anaylsis page

---

pkg/prowloader/prow.go

[TRT-593](https://issues.redhat.com//browse/TRT-593)
We're sometimes marking a test incorrectly as a flake. This is because of the suite handling in Sippy.  We got 1 test pass in one suite, and a failure in separate suite, and sippy was combining them. This is a regression, we previously fixed it but it got reintroduced in juggling suite names.
Now that we always know the suite since we have access to the raw junit, maybe we stop with only sometimes prepending it? But for now this fixes the cache to always include the suite so we don't accidentally combine results from different suites..

Use consistent cache key for tests that includes suite name

---

DEVELOPMENT.md

This [PR](https://github.com/openshift/continuous-release-jobs/pull/1233) changes to use the custom format for backups.

Mention how to load DB using custom format

---

pkg/releasesync/releasesync.go

Currently this 4.13 payload
(https://amd64.ocp.releases.ci.openshift.org/api/v1/releasestream/4.13.0-0.ci/release/4.13.0-0.ci-2022-11-02-023326) is not reporting a URL for one of the jobs, resulting in follow-on effects such as trying to insert a row where the job run id is 0.

Handle case where release controller does not report a URL

---

pkg/sippyserver/server.go

Bad logic here, we didn't fork properly and instead tried to find a prow
job in the body of the request right after, when you gave us the id to
use.

Fix risk analysis by prow job ID.

---

pkg/api/job_runs.go
pkg/apis/api/types.go

[TRT-644](https://issues.redhat.com/browse/TRT-644)

Add release name to risk analysis api result

---

pkg/filter/filterable.go

Wasn't working as we inject an AND for the release first, then we try to
add ORs but of course the AND already picks up all tests, so ORs had no
effect.
This makes it possible to OR on test names. However it still doesn't
work if you use any filtering on fields beyond the rawFilter, as we
split into raw and post filtering which comes after.
[TRT-694](https://issues.redhat.com//browse/TRT-694)

Fix or filtering

---

Makefile
pkg/sippyserver/server.go
pkg/sippyserver/server_test.go

Validate incoming ProwJobRun and return elevated risk if invalid

TRT-697: validate incoming ProwJobRun

---

pkg/sippyserver/dbloader.go

This is now more than postgresql can handle. Hard to say how long this
has been broken, but now more visible in the broken out cronjobs.
[TRT-712](https://issues.redhat.com//browse/TRT-712)

Fix kube fetchdata due to over 60k tests

---

main.go
pkg/prowloader/prow.go
pkg/releasesync/releasesync.go
pkg/sippyserver/dbloader.go

This is to hopefully allow more resilient syncing without abandoning
large portions because of a single area in any specific section of the
code.
All errors are re-logged at the end of the process, and if any were
present an overall error is returned causing the job to fail. This will
hopefully fire alerts, and the logs at the end of the pod should
summarize what went wrong.
[TRT-598](https://issues.redhat.com//browse/TRT-598)

Refactor db load error handling to tolerate problems and keep going

---

pkg/api/tests.go
pkg/db/query/test_queries.go

[TRT-653](https://issues.redhat.com/browse/TRT-653)

Fix overall test query error

---

pkg/prowloader/testoutputmetadata.go
pkg/prowloader/testoutputmetadata_test.go

[TRT-721](https://issues.redhat.com//browse/TRT-721)

Extract test metadata for watch requests

---

pkg/apis/config/v1/types.go
pkg/prowloader/prow.go

[TRT-714](https://issues.redhat.com/browse/TRT-714)

Add test grid url for jobs

---

config/openshift-customizations.yaml

The team asked for this jobs to end up in Sippy so risk analysis works.

Add operator-framework to sippy

---

pkg/prowloader/prow.go

[TRT-714](https://issues.redhat.com/browse/TRT-714)

Update test grid URL for existing prow jobs

---

pkg/prowloader/testoutputmetadata.go
pkg/prowloader/testoutputmetadata_test.go

[TRT-687](https://issues.redhat.com/browse/TRT-687)

Add result tag to test metadata for pathological event test

---

pkg/prowloader/prow.go

Want to see if we can get a better idea where we are stopping when calling findOrAddPullRequests

TRT-778: add info logging to investigate missing prow_pull_request entries

---

DEVELOPMENT.md
main.go
pkg/api/job_runs.go
pkg/db/db.go
pkg/db/models/pr_commenting.go
pkg/db/models/prow.go
pkg/github/commenter/ghcommenter.go
pkg/github/commenter/ghcommenter_test.go
pkg/prowloader/gcs/gcs_jobrun.go
pkg/prowloader/github/github.go
pkg/prowloader/github/github_test.go
pkg/prowloader/prow.go
pkg/sippyserver/daemon_server.go
pkg/sippyserver/pr_commenting_processor.go
pkg/sippyserver/server.go
pkg/util/rate_limiter.go
resources/README.md
resources/openshift/daemon-deploymentconfig.yaml

Add support for commenting on PRs with RiskAnalysis results from presubmit ci failures

TRT-718: Risk analysis pr commenting

---

OWNERS

FYI
@DennisPeriquet
@deepsm007
@neisw
@xueqzhan

Add TRT approvers to OWNERS

---

scripts/fetchdata-testgrid.sh
scripts/fetchdata.sh

https://issues.redhat.com/browse/TRT-881
/cc @dgoodwin

TRT-881: Get sippy ready for 4.14

---

sippy-ng/src/components/Sidebar.js

Remove "Payload Streams" from the "Presubmits" section.

Remove Payload Streams from Pull Presubmits

---

pkg/api/pull_requests.go
pkg/apis/api/types.go
pkg/db/query/pull_request_queries.go
pkg/filter/filterable.go
sippy-ng/src/App.js
sippy-ng/src/components/Sidebar.js
sippy-ng/src/pull_requests/PullRequests.js
sippy-ng/src/pull_requests/PullRequestsTable.css
sippy-ng/src/pull_requests/PullRequestsTable.js

[TRT-816](https://issues.redhat.com//browse/TRT-816)
This add a "Pull Requests" page under Presubmits for viewing recently merged PR's, their job history, and the first release payload they appeared in.
Todo:

Add a pull requests view similar to ocp-what-merged

---

sippy-ng/README.md

This will help vscode users address formatting quickly.

Mention Prettier code formatter for vscode users

---

pkg/db/loader/issues.go

[TRT-970](https://issues.redhat.com//browse/TRT-970)
[TRT-990](https://issues.redhat.com//browse/TRT-990)
I recently killed a fetchdata job that was running for a while trying to get a result from search.ci for over 2 hours, I think this change can only help.
a past log shows about 12 minutes of calling search.ci with batches of 50 searches [here](https://github.com/openshift/sippy/blob/21beafdd679aef3d730e4b455e1f4b77dbb0dc33/pkg/sippyserver/dbloader.go#L458):
```
time="2023-04-25T07:26:11.962Z" level=info msg="querying search.ci for test/job associations"
time="2023-04-25T07:38:19.708Z" level=info msg="syncing issue test/job associations to db"
```
The sippy load on e2e CI test sometimes takes longer than 300s; it never finishes the part where we query search.ci; so we give it a few …

Call the search.ci api with smaller batch size ; give e2e more load time

---

pkg/db/query/pull_request_queries.go

[TRT-983](https://issues.redhat.com//browse/TRT-983)
We were getting inconsistent results in the "first payload" column, this should fix it.  We do this by creating a subquery that knows the first payload for each PR for each stream/architecture, we then join on that to find the value.

Fix first payload release query

---

sippy-ng/src/helpers.js
sippy-ng/src/tests/TestAnalysis.js
sippy-ng/src/tests/TestTable.js

[TRT-1018](https://issues.redhat.com/browse/TRT-1018)

Allow test analysis page to show tests that belong to aggregated jobs

---

sippy-ng/src/component_readiness/CompReadyUtils.js
sippy-ng/src/component_readiness/ComponentReadiness.js

[TRT-1062](https://issues.redhat.com//browse/TRT-1062)
* Add some TextField UI elements for the regexes
* Re-factor code that forms columns (so it can be re-used to make it clear what the comparison is against)
* applying the filters to component and column names (and column results). 
NOTE:  The changes look bigger due to the indentations.

Add search in rows and columns for page 1

---

sippy-ng/src/component_readiness/CompReadyTestReport.js
sippy-ng/src/component_readiness/CompReadyUtils.js
sippy-ng/src/component_readiness/CompSeverityIcon.js

The "Probability of ..." text has also been revamped based on the assessment.

Add Assessment to ComponentReadiness TestReport

---

pkg/api/component_report.go
pkg/api/component_report_test.go
pkg/apis/api/types.go

[TRT-1069](https://issues.redhat.com/browse/TRT-1069)

use test id from mapping table

---

sippy-ng/src/component_readiness/CompReadyUtils.js
sippy-ng/src/component_readiness/ComponentReadiness.js

[TRT-1062](https://issues.redhat.com//browse/TRT-1062)
This applies the "Red Only" checkbox so we also filter out columns that have no red.

Include column filtering when selecting Red Only

---

pkg/api/job_runs.go
pkg/api/job_runs_test.go
pkg/db/query/job_queries.go
pkg/db/query/test_queries.go
pkg/testidentification/ocp_variants.go

Review changes switching from variant matches to jobname matches

TRT-892: Match jobnames, not variants

---

pkg/api/component_report.go

Schema query does not contain data range and therefore increased cost.

Add time range to schema query to cut db cost

---

sippy-ng/src/component_readiness/CompReadyTestReport.js

[TRT-1098](https://issues.redhat.com//browse/TRT-1098)
Add the dates in the test report for easy reference.  Attempt to print out a human interpretable summary related to the GA dates we know about.

Add to/from dates to test report page plus human readable message

---

sippy-ng/src/App.js
sippy-ng/src/component_readiness/ComponentReadiness.js
sippy-ng/src/component_readiness/ReleaseSelector.js

I think this works correctly now.

Refactor release selector

---

sippy-ng/src/component_readiness/CompReadyTestReport.js

Now that releases can come from a Context, let's use it.

Use available context for versions in TestReport

---

main.go
pkg/api/jira.go
pkg/api/releases.go
pkg/apis/api/types.go
pkg/apis/jira/v1/types.go
pkg/db/db.go
pkg/db/models/models.go
pkg/jiraloader/jiraloader.go
pkg/sippyserver/server.go
sippy-ng/package-lock.json
sippy-ng/package.json
sippy-ng/src/releases/PayloadCalendar.js
sippy-ng/src/releases/PayloadCalendarLegend.js

[TRT-1067](https://issues.redhat.com//browse/TRT-1067)

Sync and show jira incidents on the sippy calendar

---

pkg/api/component_report.go

[TRT-1139](https://issues.redhat.com//browse/TRT-1139)
Flake tests appear to be able to have success_val as 0 or 1, so we need a more explicit ordering in my partitioning scheme.
- Prefer flakes first
- Then successes
- Then failures
And get the first occurence within the partition for each test case in a junit.

More explicit ordering in deduplication of junit table

---

pkg/testidentification/ocp_variants.go

TRT-1025: Add etcd-scaling as a variant

---

pkg/sippyserver/pr_commenting_processor.go

Addresses issues in [TRT-1167](https://issues.redhat.com/browse/TRT-1167?focusedId=22736351&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22736351) regarding missing global test failure reasons and invalid html link characters
Example after update:
Job Failure Risk Analysis for sha: e2cad6663c9186b487ec56daf33c671e69e09475
| Job Name | Failure Risk |
|:---|:---|
|[pull-ci-openshift-origin-master-e2e-openstack-ovn](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/28120/pull-ci-openshift-origin-master-e2e-openstack-ovn/1686778922848489472)|**High**<br>28 tests failed in this run: High|
|[pull-ci-openshift-origin-master-e2e-gcp-ovn](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/28120/pull-ci-openshift-origin-master-e2e-gcp-o …

TRT-1125: Support over all risk reasons and escape html in links

---

pkg/api/job_runs.go

Includes the 'Overall' test results for analysis.  Biases to the lower risk for variant based results and selection between jobname and variant result types.
Shows 'Overall' as the variant type when selected.
Example:
Job Failure Risk Analysis for sha: 84022353e287fbba854eb877eb41fc05f63d58c1
| Job Name | Failure Risk |
|:---|:---|
|[pull-ci-openshift-origin-master-e2e-metal-ipi-ovn-ipv6](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/28091/pull-ci-openshift-origin-master-e2e-metal-ipi-ovn-ipv6/1684253763965030400)|**High**<br>*[sig-arch][Late] operators should not create watch channels very often [apigroup:apiserver.openshift.io] [Suite:openshift/conformance/parallel]*<br>This test has passed 99.26% of 2150 runs on release 4.14 [Overall] in the last week.| …

TRT-1167: bias to lower risk, include overall variants as well

---

sippy-ng/package-lock.json

Fixes:
Regular Expression Denial of Service (ReDOS) while Parsing CSS
https://github.com/advisories/GHSA-hpx4-r86g-5jrg

Update css-tools to fix security vulnerability

---

pkg/api/component_report.go

[TRT-1171](https://issues.redhat.com/browse/TRT-1171)

Remove okd jobs from component readiness report

---

scripts/fetchdata-testgrid.sh
scripts/fetchdata.sh
sippy-ng/src/component_readiness/ComponentReadiness.js

Adding 4.15 release to sippy and start collecting data from testgrid
/cc @stbenjam

TRT-1122: Get sippy ready for 4.15

---

pkg/sippyserver/server.go

Updating cache to 8 hrs for component readiness

---

main.go

Let's collect some data on how long it takes us to load our prow jobs. This will help us see the impact of https://github.com/openshift/sippy/pull/1191.

Add metric for prow job loading time

---

pkg/api/component_report.go

[TRT-1262](https://issues.redhat.com//browse/TRT-1262)

Ignore recovery jobs in component readiness

---

pkg/dataloader/incidentloader/incidentloader.go

[TRT-1285](https://issues.redhat.com//browse/TRT-1285)
https://github.com/openshift/continuous-release-jobs/pull/1347 adds the secret

Use token for jira api requests

---

pkg/dataloader/loaderwithmetrics/loaderwithmetrics.go

Push up metrics for how many errors we encountered during each loaders run, this should let us detect failures earlier by setting up some alerts on these metrics.

Add metric for db loading errors

---

pkg/dataloader/loaderwithmetrics/loaderwithmetrics.go

Forgot this in my other PR https://github.com/openshift/sippy/pull/1237

 Add errorMetric to prometheus gateway pusher

---

pkg/sippyserver/pr_commenting_processor.go

I see cases where we write a comment and then shortly after update the comment.  In the PR only the last comment is preserved, however, the first comment in this case should not have contained the entry for `[sig-apps] Daemon set [Serial] should surge pods onto nodes when spec was updated and update strategy is RollingUpdate [Suite:openshift/conformance/serial] [Suite:k8s]
This test has passed 100.00% of 37 runs on jobs ['periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-ovn-serial'] in the last 14 days.` as it did not appear in the prior run.  We see it is dropped out in the second comment.
This PR adds some defensive checks to try to ensure the Job we are commenting on is in fact the latest and that we don't have a duplicate entry for the latest job and give a false positive on …

trt-1167: add checks to validate job is correct for commenting

---

pkg/dataloader/releaseloader/release_dates.go
sippy-ng/src/component_readiness/ComponentReadiness.js

[TRT-1123](https://issues.redhat.com//browse/TRT-1123)

Add 4.14 GA date and update CR defaults

---

main.go
pkg/dataloader/loaderwithmetrics/loaderwithmetrics.go
pkg/dataloader/testownershiploader/testownershiploader.go

- Uses caches for suites and jira components to improve speed
- Report a total data load time to prometheus as well as individual loader times

Small improvements to data loading

---

sippy-ng/package-lock.json
sippy-ng/package.json
sippy-ng/src/App.css
sippy-ng/src/App.js
sippy-ng/src/component_readiness/CompCapRow.js
sippy-ng/src/component_readiness/CompCapTestRow.js
sippy-ng/src/component_readiness/CompReadyCapCell.js
sippy-ng/src/component_readiness/CompReadyCapsCell.js
sippy-ng/src/component_readiness/CompReadyCell.js
sippy-ng/src/component_readiness/CompReadyEnvCapabilities.js
sippy-ng/src/component_readiness/CompReadyEnvCapability.js
sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
sippy-ng/src/component_readiness/CompReadyMainInputs.js
sippy-ng/src/component_readiness/CompReadyRow.js
sippy-ng/src/component_readiness/CompReadyTestCell.js
sippy-ng/src/component_readiness/CompReadyTestDetailRow.js
sippy-ng/src/component_readiness/CompReadyTestReport.js
sippy-ng/src/component_readiness/CompTestRow.js
sippy-ng/src/component_readiness/ComponentReadiness.css
sippy-ng/src/component_readiness/ComponentReadiness.js
sippy-ng/src/components/MiniCard.js
sippy-ng/src/components/NumberCard.js
sippy-ng/src/components/SimpleBreadcrumbs.js
sippy-ng/src/components/SummaryCard.js
sippy-ng/src/index.css
sippy-ng/src/index.js
sippy-ng/src/jobs/JobDetailTable.css
sippy-ng/src/releases/ReleasePayloadAcceptance.js
sippy-ng/src/tests/TestByVariantTable.js

Fun little addition that's more possible after fixing up some of our CSS mess in https://github.com/openshift/sippy/pull/1309.  I think things are all usable, but the theme colors might need some tweaking.
cc: @neisw Since you asked about dark mode :)

Add a dark mode

---

pkg/api/component_report.go
pkg/apis/api/types.go
sippy-ng/src/bugs/BugButton.js
sippy-ng/src/component_readiness/CompReadyTestReport.js

[TRT-1238](https://issues.redhat.com//browse/TRT-1238)

Add file a new bug link to component readiness

---

sippy-ng/src/App.js
sippy-ng/src/tests/TestByVariantTable.js

Cookies for dark mode and test cell expansion end up only being session cookies, set the expiration date for 12/31/3000 so it lasts.

Make cookies enduring

---

sippy-ng/package-lock.json

https://github.com/advisories/GHSA-prr3-c3m5-p7q2
I ran `npm audit fix`

Fix CVE in css-tools

---

pkg/api/component_report.go
sippy-ng/src/component_readiness/CompReadyUtils.js
sippy-ng/src/component_readiness/ComponentReadiness.js

[TRT-1151](https://issues.redhat.com//browse/TRT-1151)

Drop alibaba from component readiness

---

Makefile

Clean up make targets; add image build target

---

main.go

The initial metrics refresh takes a while, which can make quick development frustrating while you wait for the initial refresh.  This makes it so if `--listen-metrics=""`, we don't start the metrics server or refresh any metrics at all.

Make metrics server optional

---

.golangci.yml
main.go
pkg/api/component_report.go
pkg/api/component_report_test.go
pkg/api/jobrunintervals/job_run_intervals.go
pkg/dataloader/prowloader/gcs/gcs_jobrun.go
pkg/dataloader/prowloader/prow.go
pkg/sippyserver/metrics/metrics.go
pkg/sippyserver/server.go

Should help with the productization effot in allowing other projects to
import from other buckets.

Add CLI arg for GCS bucket to pull artifacts from

---

pkg/api/component_report.go

[TRT-1413](https://issues.redhat.com/browse/TRT-1413)

trt-1413: filter disruptive jobs

---

sippy-ng/src/datagrid/GridToolbarFilterItem.js

Revert "Fix time filter to use ISO format that is required by API"

---

sippy-ng/src/component_readiness/ComponentReadiness.js
sippy-ng/src/component_readiness/ComponentReadinessHelp.js
sippy-ng/src/component_readiness/ComponentReadinessToolBar.js

TRT-1435: Add a FAQ for component readiness

---

pkg/api/component_report.go
pkg/regressionallowances/OWNERS
pkg/regressionallowances/intentional_4.15_regressions.go
pkg/regressionallowances/types.go

The core part of the change that allows regressions to be introduced into the product.
/assign @stbenjam

Add mechanism to indicate that a regression is allowed in sippy

---

sippy-ng/src/App.js

- Improved OS dark mode detection, useMediaQuery is flaky
- Dark mode isn't experimental anymore

Dark mode improvements

---

pkg/api/component_report.go

/hold 
Pending ci-test-mapping PR https://github.com/openshift-eng/ci-test-mapping/pull/102

TRT-1351: Use capability to exclude disruption tests

---

sippy-ng/src/component_readiness/CompReadyTestReport.js

Test ID is needed for things like intentional regression and reporting fixed issues. It also helps find the specific test in ci-test-mapping to understand how the test was mapped.

Show test ID on test details report

---

pkg/regressionallowances/intentional_4.15_regressions.go
pkg/regressionallowances/types.go

Consistent suggestion for allowances
/assign @jupierce @stbenjam

require jira bug for a regression allowance

---

pkg/componentreadiness/resolvedissues/resolved_4.15_issues.go

Azure had issues on 1/21, we're filtering the same jobs from the install test failures.
/assign @deads2k

OCPBUGS-27495: Add exception for 4.15 operator network condition test

---

pkg/api/component_report.go
pkg/api/disruption_report.go
pkg/api/utils.go
pkg/apis/api/types.go
pkg/apis/cache/cache.go
pkg/sippyserver/metrics/metrics.go
pkg/sippyserver/server.go
sippy-ng/src/component_readiness/CompReadyEnvCapabilities.js
sippy-ng/src/component_readiness/CompReadyEnvCapability.js
sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
sippy-ng/src/component_readiness/CompReadyTestReport.js
sippy-ng/src/component_readiness/ComponentReadiness.js
sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
sippy-ng/src/component_readiness/GeneratedAt.js

This adds the time the report was generated, and ability to force a reload of the data in the cache.

TRT-1225: Allow user to force refresh the cache, add time/date to the API and pages

---

sippy-ng/src/tests/TestAnalysis.js
sippy-ng/src/tests/TestTable.js

Adds a jira component table view, and also shows the test component on the analysis page.

Show test component in Jira

---

pkg/dataloader/releaseloader/release_dates.go

Note: this will flip CR default to 4.16 vs. 4.15

Add GA date for 4.15

---

pkg/sippyserver/pr_commenting_processor.go

This has been crash looping the daemon over the weekend.

Add a check for nil attrs on a PR

---

sippy-ng/src/component_readiness/extreme-triaged.svg
sippy-ng/src/component_readiness/green-bypassed.svg
sippy-ng/src/component_readiness/regressed-triaged.svg

Vectorized versions of Justin's proposal for triaged and bypassed component readiness icons.

Triage icons (Justin's Version)

---

pkg/sippyserver/metrics/metrics.go

- Total number of regressed tests by component, this can count the same test multiple times if it's regressed across multiple NURP's
- Unique number of regressed tests by component

TRT-1585: Add two new component readiness metrics

---

hack/gen-resolved-issue.py
pkg/api/component_report.go
pkg/api/disruption_report.go
pkg/api/utils.go
pkg/apis/api/types.go
pkg/componentreadiness/resolvedissues/types.go
pkg/sippyserver/pr_commenting_processor.go

Need to finalize the location of the triaged_incidents table and update.
- updates gen-resolved-issue.py to write records to bigquery table
- updates component_report to read resolved / triaged records from bigquery
- separates sample and base queries and caches results independently

TRT-1555: Scripted Incident Attribution

---

hack/gen-resolved-issue.py
pkg/api/component_report.go
pkg/api/disruption_report.go
pkg/api/utils.go
pkg/apis/api/types.go
pkg/componentreadiness/resolvedissues/types.go
pkg/sippyserver/pr_commenting_processor.go

Reverts openshift/sippy#1560
We broke something. [Prior to this change](http://localhost:3000/sippy-ng/component_readiness/test_details?arch=amd64&baseEndTime=2024-04-03%2023%3A59%3A59&baseRelease=4.15&baseStartTime=2024-03-27%2000%3A00%3A00&capability=operator-conditions&component=Networking%20%2F%20router&confidence=95&environment=sdn%20upgrade-minor%20amd64%20metal-ipi%20standard&excludeArches=arm64%2Cheterogeneous%2Cppc64le%2Cs390x&excludeClouds=openstack%2Cibmcloud%2Clibvirt%2Covirt%2Cunknown&excludeVariants=hypershift%2Cosd%2Cmicroshift%2Ctechpreview%2Csingle-node%2Cassisted%2Ccompact&groupBy=cloud%2Carch%2Cnetwork&ignoreDisruption=true&ignoreMissing=false&minFail=3&network=sdn&pity=5&platform=metal-ipi&sampleEndTime=2024-04-03%2023%3A59%3A59&sampleRelease=4.16&sampleStartTime=2024-0 …

Revert "TRT-1555: Scripted Incident Attribution"

---

pkg/api/jobrunintervals/job_run_intervals.go
pkg/apis/api/interval.go
pkg/dataloader/prowloader/gcs/gcs_jobrun.go
pkg/sippyserver/server.go
sippy-ng/src/components/TimelineChart.js
sippy-ng/src/prow_job_runs/ProwJobRun.js

The move to structured intervals is underway, the fields in json remain tempStructuredLocator and tempStructuredMessage. Sippy now uses these fields instead of the legacy locator/message which will soon be removed, and the structured version will be moved to those names. When that happens, I will update this code in the sippy API to detect both and massage the data so old jobs can still be loaded fine.
In addition:
- we now load a specific intervals file, defaulting to the first spyglass intervals file we find.
- a dropdown allows loading other files.
More changes coming.

TRT-1404: Port Sippy Intervals UI to Use Structured Data and Various Improvements

---

DEVELOPMENT.md
cmd/sippy/component_readiness.go
cmd/sippy/main.go
pkg/sippyserver/capabilities.go
pkg/sippyserver/metrics/metrics.go
pkg/sippyserver/server.go
sippy-ng/src/App.js
sippy-ng/src/components/Sidebar.js

🤦🏻 I moved the `<Route>` declaration for `/`to the top for readability and I forgot it's ordering dependent.  `/` needs to match last, otherwise all URL's match.

TRT-1462: Unrevert allow launching sippy without postgres

---

sippy-ng/src/component_readiness/CompReadyTestReport.js

TRT-1631: Add a help link from the test details page

---

sippy-ng/src/bugs/BugTable.js
sippy-ng/src/jobs/JobAnalysis.js

trt-1604: handle missing job bugs

---

hack/gen-resolved-issue.md
hack/gen-resolved-issue.py

Added support for wildcard test ids, minimal test output and added examples in [gen-resolved-issue.md](https://github.com/neisw/sippy/blob/41f2dea8ef6d89fe4548db9b9c9c4ccc0f422fdc/hack/gen-resolved-issue.md)

trt-555: Update to support wildcarding test ids and fix variant record bug

---

.golangci.yml
Dockerfile.buildroot
hack/go-lint.sh
pkg/api/component_report.go
pkg/api/health.go
pkg/api/install.go
pkg/api/job_runs.go
pkg/api/jobs.go
pkg/api/tests.go
pkg/dataloader/prowloader/bigqueryjobs.go
pkg/dataloader/prowloader/github/github_test.go
pkg/dataloader/prowloader/prow.go
pkg/db/db.go
pkg/db/query/job_queries.go
pkg/sippyserver/parameters.go
pkg/testidentification/ocp_variants.go
pkg/variantregistry/ocp.go

Revert "NO-JIRA: update golangci-lint v1.57.2"

---

sippy-ng/src/prow_job_runs/ProwJobRun.js

Currently just OVS unreasonably long poll interval, indicating likely
CPU starvation.

Display system journal log intervals

---

pkg/variantregistry/loader.go
pkg/variantregistry/ocp.go

Believe this was due to cluster-data from most recent run (not
necessarily successful). If we hit a really bad run, and there was no
cluster-data, variants could churn from one update to the next.
Fix by adjusting query to join in the LAST SUCCESS prow url instead,
hopefully this will give us stable variants for things coming from
cluster-data.
Filter to only jobs that have run in last 6 months, this cuts number of
jobs from 24k to 14k, and query size from 2.6Gb to 750mb.
Batch job deletions so we can get through them in a reasonable
timeframe. (already run during devel though)

TRT-1655: Fix job variants churning for no reason

---

hack/gen-resolved-issue.md

I felt there were a lot of options so I grouped after getting a better understanding after a demo of the workflow.  I modified the simple example usage but kept the other examples intact.
I realize that the cli interface may go away after a UI is developed so feel free to deem this as unnecessary.

Enhance gen-resolved-issue README by grouping options

---

hack/gen-resolved-issue.py

Had my time comparison order reversed

trt-1668: Fix issue-resolution-date time compare

---

sippy-ng/package-lock.json

https://github.com/advisories/GHSA-grv7-fg5c-xmjg

Update braces for CVE-2024-4068

---

pkg/db/matviews.go
pkg/db/models/prow.go

- Use GIN index type for variants https://www.postgresql.org/docs/current/gin-intro.html
- Move away from CASE to FILTER
- ~Composite index for test ID+name, and run timestamp+ID~

Improvements to matview refresh

---

sippy-ng/src/component_readiness/CompReadyTestReport.js

fixes breakage in https://github.com/openshift/sippy/pull/1766 which merged prematurely

TRT-1550: followup fix

---

hack/gen-resolved-issue.md
hack/gen-resolved-issue.py

Adds support to target a specific build cluster for job run / test failures

trt-1712: Target build cluster

---

pkg/api/component_report.go

The dynamic job name column was not guarded for pull-request component
readiness sample requests only, causing /payload jobs to leak into
normal component readiness reports.
Modified to only use the dynamic column specifically for *sample*
queries, when a pull request is specified.

Fix /payload jobs leaking into variant based component readiness

---

pkg/api/job_runs.go
pkg/api/job_runs_test.go
pkg/apis/api/types.go
pkg/db/query/test_queries.go
pkg/sippyserver/pr_commenting_processor.go
pkg/sippyserver/server.go
pkg/sippyserver/server_test.go

For [TRT-1702](https://issues.redhat.com/browse/TRT-1702) I'd like to be able to record some more info about the analysis, so this supplies those raw values.
Also felt a need to refactor a bit along the way... that's mostly in the first two commits with the main intent in the final commit.

TRT-1702: enrich RiskAnalysis results

---

sippy-ng/package-lock.json
sippy-ng/package.json
sippy-ng/src/component_readiness/CompReadyUtils.js
sippy-ng/src/component_readiness/ComponentReadiness.css
sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
sippy-ng/src/component_readiness/RegressedTestsModal.js
sippy-ng/src/component_readiness/TriagedIncidentGroups.js
sippy-ng/src/component_readiness/TriagedIncidentsPanel.js
sippy-ng/src/component_readiness/TriagedTestDetailRow.js
sippy-ng/src/component_readiness/TriagedTestDetails.js
sippy-ng/src/component_readiness/TriagedTestJobRuns.js
sippy-ng/src/component_readiness/TriagedVariants.js

Adds a new `Triaged Incidents` tab to the RegressedTests modal dialog
Sample [localhost 4.16  6/7 - 6/14](http://localhost:3000/sippy-ng/component_readiness/main?baseEndTime=2024-06-27%2023%3A59%3A59&baseRelease=4.16&baseStartTime=2024-05-31%2000%3A00%3A00&columnGroupBy=Platform&columnGroupBy=Architecture&columnGroupBy=Network&confidence=95&ignoreDisruption=1&ignoreMissing=0&includeVariant=Architecture%3Aamd64&includeVariant=FeatureSet%3Adefault&includeVariant=Installer%3Aipi&includeVariant=Installer%3Aupi&includeVariant=Owner%3Aeng&includeVariant=Platform%3Aaws&includeVariant=Platform%3Aazure&includeVariant=Platform%3Agcp&includeVariant=Platform%3Ametal&includeVariant=Platform%3Avsphere&includeVariant=Topology%3Aha&minFail=3&pity=5&regressedModal=1&sampleEndTime=2024-08-14%2023%3A59%3A59& …

trt-1666: Add view to show existing triaged incidents

---

pkg/sippyserver/metrics/metrics.go

Bigquery sometimes complains about updating items in streaming buffer, until that is solved, this should solve the problem of missing view metrics

Continue to next view after one encounters errors

---

pkg/regressionallowances/intentional_regressions.go
pkg/regressionallowances/regressions_4.17.json

Resolves conflicts between [sippy#2006](https://github.com/openshift/sippy/pull/2006) and [sippy#2013](https://github.com/openshift/sippy/pull/2013)

Regressions 4.17 merge resolve

---

config/views.yaml

Revert "Compare 4.18 to 4.17 ga now"

---

sippy-ng/package-lock.json
sippy-ng/package.json

https://github.com/bendotcodes/cookies/issues/693 releases a new version of universal-cookie with the fix for https://github.com/advisories/GHSA-pxg6-pf52-xh8x.

TRT-1847: Update package deps to fix GHSA-pxg6-pf52-xh8x

---

pkg/api/utils.go
pkg/componentreadiness/resolvedissues/types.go

Marshaller got removed somewhere along the line

TRT-1832: json marshaller

---

config/views.yaml

- Exclude SDN
- Add microshift

Update component readiness default views

---

pkg/api/componentreadiness/component_report.go
pkg/api/componentreadiness/component_report_test.go

We think this will be more fair and realistic for component readiness
stop ship decisions.

Respect minFail in pass rate comparisons

---

sippy-ng/src/App.js
sippy-ng/src/helpers.js

Models CR and allows us to add the new release before branch cut

TRT-1774: First nonga release selection

---

pkg/sippyserver/server.go

I saw this same pattern repeated and it looked very cluttered. A few vim macros simplified it to the essentials.
Also fixed up a few error messages, which were easier to notice without the clutter.

server.go: simplify a lot of repetitive RespondWithJSON usage

---

hack/gen-resolved-issue.py

Only print job runs that match filters, I got confused by this in a
lengthy execution when I saw it printing jobs that it shouldn't be
matching.
Include some rough progress indicators, x of y cells, and a of b
regressions within that cell.

Touchups for the triage script

---

pkg/variantregistry/ocp.go
pkg/variantregistry/ocp_test.go

Counterpart to https://github.com/openshift/release/pull/57998

trt-1795: add chaos job support

---

config/qe-views.yaml

Update the base release for 4.18-qe-main to 4.17

Change base for 4.18-qe-main view to 4.17

---

cmd/sippy/load.go
pkg/api/test_analysis.go
pkg/dataloader/bugloader/bugloader.go
pkg/dataloader/prowloader/bigqueryjobs.go
pkg/dataloader/prowloader/prow.go
pkg/dataloader/prowloader/prow_test.go
pkg/db/db.go
pkg/db/models/prow.go
pkg/db/partitionedtables.go
pkg/db/query/job_queries.go
pkg/db/query/test_queries.go
pkg/db/views.go

- **Revert "Merge pull request #2180 from xueqzhan/revert-2074-append-test-analysis-by-job"**
- **Subtract 14 days, not add...**

by job analysis 2

---

pkg/api/componentreadiness/component_report.go
pkg/api/componentreadiness/querygenerators.go
pkg/api/componentreadiness/test_details.go

- **Revert "Merge pull request #2174 from sosiouxme/20241213-revert-2162"**
- **Fix mistakenly inverted start/end dates**
original pr was: https://github.com/openshift/sippy/pull/2162
small commit layered onto the original to fix the issue.

Refactor query generators (take 2)

---

pkg/api/job_runs.go
pkg/bigquery/client.go
pkg/cache/bigquerycache/bigquery.go
pkg/db/query/test_queries.go

minor refactoring, everything should work as before, but the code is (IMHO) clearer and cleaner.

TRT-1781: sql hygiene

---

pkg/api/job_runs.go

looks like `currentVersion` from the job sometimes fails to parse. not every branch of logic uses it, but those that do, panic. this prevents the panic and logs what happened, so we can go figure out where the bad version is coming from (I don't have a reproducer currently).

TRT-1924: address jsonJobRunRiskAnalysis panics

---

config/qe-views.yaml
config/views.yaml

also fix `rosa` no longer being a valid installer.

TRT-1941: update cross-compare views

---

pkg/api/componentreadiness/component_report.go

Looks to have been mistakenly disabled

TRT-1981: Restore confidence adjustment for recent regressions

---

pkg/api/job_runs.go
pkg/github/commenter/ghcommenter.go
pkg/sippyserver/pr_commenting_processor.go

mostly just to make things more readable for my own sanity

bit of refactoring for RA PR commenting

---

pkg/apis/api/types.go
pkg/db/query/feature_gates.go
pkg/sippyserver/server.go
sippy-ng/src/tests/FeatureGates.js

- Add "first seen in" columns to know when a feature gate was born
- This makes sort and filtering server-side so filtering on things like the enabled column actually work
- Default view is now only tech/dev preview for recent releases
- Adds bookmarks
- Also adds the download link

TRT-1994: Adjustments to feature gates page

---

pkg/variantregistry/ocp.go
pkg/variantregistry/ocp_test.go

Refactors variant registry to remove the regexp and make it a little easier to manage.  
There are some changes to variants but should all be correct, I fixed a few bugs.
- in some jobs that mention versions like "1.8" that's considered the "From" version so it's identified as sdn and runc -- but that's not correct
- metal-ipi-ovn-ipv6 jobs as NetworkAccess:disconnected.
- jobs with undetectable ContainerRuntime had blank "" values.  Those are removed
Summary of changes:
```
ocp_test.go:1151: Removed ContainerRuntime (was "")
- periodic-ci-CSPI-QE-MSI-openshift-ci-trigger-poc-test-fail-setup
- periodic-ci-CSPI-QE-MSI-openshift-ci-trigger-poc-test-fail-test
- periodic-ci-CSPI-QE-interop-aws-reporter-main-weekly_trigger-interop-aws-reporter-bot
- …
```

TRT-1983: Refactor variant registry to be simpler

---

pkg/sippyserver/pr_commenting_processor.go

just on principle, best not to allow comments to grow unbounded in size

TRT-1825: limit comment size for new tests

---

sippy-ng/src/AccessibilityModeProvider.js
sippy-ng/src/App.js
sippy-ng/src/component_readiness/AccessibilityToggle.js
sippy-ng/src/component_readiness/CompCapRow.js
sippy-ng/src/component_readiness/CompCapTestRow.js
sippy-ng/src/component_readiness/CompReadyCapsCell.js
sippy-ng/src/component_readiness/CompReadyCell.js
sippy-ng/src/component_readiness/CompReadyEnvCapabilities.js
sippy-ng/src/component_readiness/CompReadyEnvCapability.js
sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
sippy-ng/src/component_readiness/CompReadyRow.js
sippy-ng/src/component_readiness/CompReadyTestCell.js
sippy-ng/src/component_readiness/CompReadyTestReport.js
sippy-ng/src/component_readiness/CompReadyUtils.js
sippy-ng/src/component_readiness/CompReadyVars.js
sippy-ng/src/component_readiness/CompSeverityIcon.js
sippy-ng/src/component_readiness/ComponentReadiness.js
sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
sippy-ng/src/component_readiness/RegressedTestsModal.js
sippy-ng/src/component_readiness/RegressedTestsPanel.js
sippy-ng/src/component_readiness/Sidebar.js
sippy-ng/src/component_readiness/blue.svg
sippy-ng/src/component_readiness/extreme-orange-triaged.svg
sippy-ng/src/component_readiness/extreme-orange.svg
sippy-ng/src/component_readiness/half-blue.svg
sippy-ng/src/component_readiness/none-blue.svg
sippy-ng/src/component_readiness/orange-triaged.svg
sippy-ng/src/component_readiness/orange.svg

This mode, configurable next to 'night mode', changes the green icons to blue and red to orange. If there are further accessibility adjustments needed in the future, the toggle can control those as well.

TRT-1966: add accessibility-mode to component readiness

---

pkg/variantregistry/ocp.go

Always use the most recent prowjob_url and gcs_bucket for all rows, and use ANY_VALUE to get the gcs bucket. Fixes:
```
time="2025-03-07T08:05:16.994Z" level=fatal msg="could not execute root command" error="error querying primary list of all jobs: googleapi: Error 400: SELECT list expression references r.gcs_bucket which is neither grouped nor aggregated at [24:3], invalidQuery"
```

Fix group by problem in variant registry

---

config/views.yaml
pkg/api/componentreadiness/component_report.go
pkg/api/componentreadiness/query/querygenerators.go

Gets rid of ignored jobs, uses the job tier.

TRT-1983: Use JobTiers for selecting jobs in component readiness

---

hack/gen-resolved-issue.py
pkg/api/componentreadiness/component_report.go
pkg/api/componentreadiness/test_details.go
pkg/apis/api/componentreport/types.go

* Updates to take test details api urls for triage
* Fixes missing triage call in component_report
* Fixes completion_time reference for BQ schema

TRT-2039: triage via test details urls

---

pkg/variantregistry/ocp.go

In order to remove the config, we need to correctly classify presubmits with the right job tier and release variants. This would let us replace the regexp part of the sippy configuration[1].
[1] https://github.com/openshift/sippy/blob/0563dd59fab4b2877ddcced48b63d09deab23929/config/openshift-customizations.yaml#L16-L19

TRT-1983: Set release and job tier for presubmits

---

pkg/variantregistry/ocp.go

Processing all the jobs with their cluster data serially takes 2.5 hours in CI.  That doesn’t really matter much for something that runs once a day, but I’ve had to use it a few times locally, and I wished it was faster. This parallelizes generating variants, bringing it to around 20 minutes.

Parallelize job variant registry

---

pkg/variantregistry/ocp.go

This PR adds usernamespace suite according to the advise by @dgoodwin  https://github.com/openshift/release/pull/63161#discussion_r2018789445

OCPNODE-2315: Add usernamespace suite

---

pkg/db/models/triage.go
sippy-ng/src/component_readiness/CompReadyUtils.js
sippy-ng/src/component_readiness/RegressedTestsPanel.js
sippy-ng/src/component_readiness/TriagedRegressions.js

This also formats the link to Jira better so that it takes up less space

TRT-2045: add a description field to `triage`

---

sippy-ng/src/component_readiness/ComponentReadinessToolBar.js

We shouldn't try the `GET` endpoint without one. This is breaking QE component readiness.

TRT-2045: triages are only available if there is a postgres connection

---

sippy-ng/src/prow_job_runs/IntervalsChart.js

Buttons for including a category/source of intervals now show how many
that source is or would show if the button were enabled.

Display count of intervals by source

---

pkg/api/jobartifacts/apitypes.go
pkg/api/jobartifacts/manager.go
pkg/api/jobartifacts/query.go
pkg/api/jobartifacts/query_test.go
sippy-ng/src/component_readiness/CompReadyTestDetailRow.js
sippy-ng/src/component_readiness/CompReadyTestPanel.js
sippy-ng/src/component_readiness/CompReadyTestReport.js
sippy-ng/src/component_readiness/CompReadyUtils.js
sippy-ng/src/component_readiness/ComponentReadiness.css
sippy-ng/src/component_readiness/ComponentReadiness.js
sippy-ng/src/component_readiness/JobArtifactQuery.js
sippy-ng/src/helpers.js

Beginnings of a UI for searching up job artifact content from the test_details page.
The UX needs a lot of work but it's good enough to play with, and does some really useful stuff already.

TRT-2073: test_details job artifact search

---

pkg/variantregistry/ocp.go

Counterpart to https://github.com/openshift/release/pull/63667

trt-2076: add ipsec procedure variant value

---

pkg/dataloader/bugloader/bugloader.go
pkg/db/models/prow.go
sippy-ng/src/component_readiness/TriagedRegressions.js

This will helps us know if a bug is resolved, and if we have the correct bug triaged per release.

TRT-2111: Display triaged bug state and version

---

pkg/api/jobartifacts/apitypes.go
pkg/api/jobartifacts/content_line_matcher.go
pkg/api/jobartifacts/content_line_matcher_test.go
pkg/api/jobartifacts/manager.go
pkg/api/jobartifacts/query.go
pkg/api/jobartifacts/query_test.go
pkg/cache/compressed/cache_test.go
pkg/sippyserver/server.go
pkg/util/testing.go
sippy-ng/src/component_readiness/JobArtifactQuery.js

* error / timeout API reporting improved
* add caching for job artifact searches
UI improvements planned to take advantage of these...

TRT-2101: improvements to jobartifacts backend

---

pkg/dataloader/bugloader/bugloader.go

I previously implemented syncing triaged bugs that weren't already
picked up by virtue of mentioning a test name, into postgres. However we
were not going back to the triage records and establishing the link so
their details show in the triage api responses.

TRT-2110: Link triaged bugs after they're synced to our db

---

sippy-ng/src/component_readiness/CompReadyEnvCapabilities.js
sippy-ng/src/component_readiness/CompReadyEnvCapability.js
sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
sippy-ng/src/component_readiness/CompReadyUtils.js
sippy-ng/src/component_readiness/CompReadyVars.js
sippy-ng/src/component_readiness/ComponentReadiness.js
sippy-ng/src/component_readiness/JobArtifactQuery.js
sippy-ng/src/component_readiness/Triage.js
sippy-ng/src/component_readiness/TriageFields.js
sippy-ng/src/component_readiness/UpsertTriageModal.js
sippy-ng/src/components/SecureLink.js
sippy-ng/src/prow_job_runs/IntervalsChart.js

Two improvements:
* improve some slightly ugly UI code that bothered me
* proper workaround for dynamic links that snyk won't complain about

minor beautification

---

pkg/api/componentreadiness/triage.go
pkg/sippyserver/server.go
sippy-ng/src/component_readiness/AddRegressionPanel.js
sippy-ng/src/component_readiness/Triage.js
sippy-ng/src/component_readiness/TriagedRegressions.js
sippy-ng/src/component_readiness/UpdateTriagePanel.js
sippy-ng/src/component_readiness/UpsertTriageModal.js

This also adds the `Last Change` field to the modal and triage details page. There is some refactoring of functionalities into separate components included here, as the `UpsertTriageModal` began to get too complex.

TRT-2050: allow the ability to delete triage records and remove regressions from them

---

sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
sippy-ng/src/component_readiness/RegressedTestsModal.js
sippy-ng/src/component_readiness/RegressedTestsPanel.js
sippy-ng/src/component_readiness/TriagedRegressionTestList.js
sippy-ng/src/component_readiness/TriagedRegressions.js

Revert "TRT-1787: fix needless browser history updates"

---

sippy-ng/src/helpers.js

Fix test analysis links

---

sippy-ng/src/bugs/BugTable.js

Follows up on https://github.com/openshift/sippy/pull/2794
Assisted by Cursor (Claude 4 sonnet)

TRT-2182: add a link to triage details within simple triage button tooltip

---

sippy-ng/package-lock.json
sippy-ng/package.json
sippy-ng/src/App.js
sippy-ng/src/build_clusters/BuildClusterOverview.js
sippy-ng/src/component_readiness/CompReadyMainInputs.js
sippy-ng/src/component_readiness/CompReadyVars.js
sippy-ng/src/component_readiness/ComponentReadiness.js
sippy-ng/src/component_readiness/NotYetImplemented.js
sippy-ng/src/components/Histogram.js
sippy-ng/src/index.js
sippy-ng/src/jobs/JobStackedChart.js
sippy-ng/src/jobs/JobTable.css
sippy-ng/src/jobs/Jobs.js
sippy-ng/src/prow_job_runs/IntervalsChart.js
sippy-ng/src/releases/Install.js
sippy-ng/src/releases/PayloadCalendar.js
sippy-ng/src/releases/PayloadMiniCalendar.js
sippy-ng/src/releases/PayloadStream.js
sippy-ng/src/releases/ReleasePayloadDetails.js
sippy-ng/src/releases/Upgrades.js
sippy-ng/src/repositories/RepositoriesTable.js
sippy-ng/src/tests/FeatureGates.js
sippy-ng/src/tests/TestTable.css
sippy-ng/src/tests/Tests.js

This is a mostly automated migration to React Router v6 which I struggled to do by myself due to how fundamentally v6 changed.  Cursor helped solve the issues I couldn't easily figure out.
Assisted-by: Cursor AI

TRT-1814: Upgrade to react-router v6

---

sippy-ng/package-lock.json
sippy-ng/package.json
sippy-ng/src/App.js
sippy-ng/src/build_clusters/BuildClusterOverview.js
sippy-ng/src/component_readiness/CompReadyMainInputs.js
sippy-ng/src/component_readiness/CompReadyVars.js
sippy-ng/src/component_readiness/ComponentReadiness.js
sippy-ng/src/component_readiness/NotYetImplemented.js
sippy-ng/src/components/Histogram.js
sippy-ng/src/index.js
sippy-ng/src/jobs/JobStackedChart.js
sippy-ng/src/jobs/JobTable.css
sippy-ng/src/jobs/Jobs.js
sippy-ng/src/prow_job_runs/IntervalsChart.js
sippy-ng/src/releases/Install.js
sippy-ng/src/releases/PayloadCalendar.js
sippy-ng/src/releases/PayloadMiniCalendar.js
sippy-ng/src/releases/PayloadStream.js
sippy-ng/src/releases/ReleasePayloadDetails.js
sippy-ng/src/releases/Upgrades.js
sippy-ng/src/repositories/RepositoriesTable.js
sippy-ng/src/tests/FeatureGates.js
sippy-ng/src/tests/TestTable.css
sippy-ng/src/tests/Tests.js

Reverts openshift/sippy#2742
"Generate Report" is broken in CR.  I don't see a quick path so reverting this for now

Revert "TRT-1814: Upgrade to react-router v6"

---

pkg/api/componentreadiness/query/querygenerators.go

dbg sql statement needed reformatting to handle unnest array values
AI assist on code formatting

NO-JIRA: sql debug string array

---

sippy-ng/src/bugs/FileBug.js
sippy-ng/src/component_readiness/TestDetailsReport.js

Also adds a note to the modal that the fields are editable post-submission

TRT-2161: display the computed component name in the FileBug dialog

---

config/openshift-customizations.yaml
config/openshift.yaml

add jobs defined in https://github.com/openshift/release/pull/68612 to sippy version

add new prod jobs for separate regions

---

sippy-ng/src/jobs/JobAnalysis.css
sippy-ng/src/jobs/JobAnalysis.js
sippy-ng/src/jobs/JobTable.js

TRT-2272: Show matching jobs & variants on job analysis page

---

pkg/dataloader/bugloader/bugloader.go

I noticed this issue when starting work on displaying the audit logs. Every time `bugloader` runs, it updates any triage entry that is unresolved. It doesn't actually change anything, but it saves it which results in an audit_log entry being created...

NO-JIRA: bugloader should not re-save the triage when no changes have been made

---

pkg/db/suites.go

As title, address this https://redhat-internal.slack.com/archives/CBN38N3MW/p1757036358616519?thread_ts=1756698465.278659&cid=CBN38N3MW

add olm performance suites to allowlist

---

sippy-ng/src/component_readiness/UpdateTriagePanel.js

This will significantly improve the usability within the remove regressions panel on the update triage modal.
Before:
After:
Assisted by Cursor

NO-JIRA: remove regressions UX improvements

---

AGENTS.md

Some basic principles we'd like coding agents to adhere to in Sippy.

Add AGENTS.md to direct cursor and other tools

---

sippy-ng/src/component_readiness/CompReadyTestPanel.js
sippy-ng/src/component_readiness/ComponentReadiness.css
sippy-ng/src/component_readiness/JobArtifactQuery.js

Cleaned up some of the UI issues for how this displays on test_details pages. The dialog now looks like a dialog, scrolls better, and is more visually compact and delineated.
Also added a standard query for finding one symptom of last week's AWS incident.
Cursor was helpful in getting the CSS sorted out, although it also provided many red herrings.

TRT-2101: Job Artifact Query updates

---

pkg/api/componentreadiness/triage.go

I noticed this today when triaging something to an issue that was restricted. We cannot comment on issues in this state. I don't think we should increase the permissions of the bot as that may open us up to leaks. Instead, we will just not throw errors as they are not actionable by the user and will just lead to confusion. Instead we can add warnings to the logs, and discover the problem if we notice failures to post the comment in other cases.

NO-JIRA: do not surface error when failing to comment on jira issue used for triage
